### DISCUSSION TITLE
Proper way upgrading local tarantool docker-compose from 2.x to 3.x

### DISCUSSION THREAD

**Discussion by kokizzu** [tarantool/tarantool#10076] [General]
So I have local docker-compose containing something like this:
```
services:
  tarantool1:
    image: tarantool/tarantool:2.11
    environment:
      TARANTOOL_USER_NAME: "user1"
      TARANTOOL_USER_PASSWORD: "password1"
      TT_READAHEAD: '1632000' # 10x
      TT_VINYL_MEMORY: '268435456' # 20x
      TT_VINYL_CACHE: '2684354560' # 20x
      TT_NET_MSG_MAX: '76800' # 100x
      TT_MEMTX_MEMORY: '268435456' # 1x
      TT_VINYL_PAGE_SIZE: '8192' # 1x
    volumes:
      - ./_tmpdb/var_lib_tarantool:/var/lib/tarantool
    ports:
      - "3302:3301"
```

to convert to 3.x i change `docker-compose.yaml` into something like this:
```
services:
  tarantool1:
    image: tarantool/tarantool:3.1
    # https://github.com/tarantool/tarantool/tree/master/docker
    environment:
      TT_APP_NAME: default
      TT_INSTANCE_NAME: instance-001
    volumes:
      - ./opt__tarantool__app__config.yaml:/opt/tarantool/app/config.yaml
      - ./_tmpdb/var_lib_tarantool:/var/lib/tarantool
      - ./_tmpdb/var_run_tarantool:/var/run/tarantool # without this, it failed to create directory
    ports:
      - "3302:3301"
```

and create `opt__tarantool__app__config.yaml` contain this:
```
credentials:
  users:
    user1:
      roles: [ super ]
      password: 'password1'

iproto:
  listen:
    - uri: 0.0.0.0:3301

groups:
  group-001:
    replicasets:
      replicaset-001:
        instances:
          instance-001: { }
```

it seems to be working fine, but previously i run:
```
docker exec -it project1-tarantool1-1 tarantoolctl connect user1:password1@127.0.0.1:3301
```

the question are:

1. how can i connect now if using docker? I tried:
```
 docker exec -it project1-tarantool1-1 bash
root@f264d653a6d7:/opt/tarantool# tt connect app:instance-001 tcp://user1:password1@127.0.0.1:3301
   ⨯ can't collect instance information for app:instance-001: "/etc/tarantool/instances.enabled/app" doesn't exist or not a directory
```

2. how can i use old 2.11 data, it seems to create a new instance instead of using old data
3. how to set old environment variable config on new docker 3.x image?
