### DISCUSSION TITLE
memcs: API for including columns into secondary index

### DISCUSSION THREAD

**Discussion by nshy** [tarantool/tarantool#10810] [RFC]
## Reviewers

- [x] Team Lead: @sergepetrenko 
- [x] CTO: @sergos
- [x] Guest reviewer: @locker 

### 2025-01-14
- add API/Introspection section
- add Persistence section
- add details to API/Creation section

### 2024-11-13
- rename option from `include` to `covers`
- mention possible option (will not be supported in the scope of the issue) to return only covered columns in `get`, `select` and such

## Problem statement

The task is described in https://github.com/tarantool/tarantool-ee/issues/893. Existing scanner API allows to pass index id so this document is merely to come to terms how to specify which columns besides mentioned in the `parts` include into the index.

## Proposed API

Proposed API is:

### Creation
`index:create_index(name, {parts = {key_column_1, ..., key_column_K}, covers={column_1, ..., column_N}})`

`covers` may reference columns by name or by position as `parts`. The index key columns and primary index key columns are implicitly covered. The order of columns in the `covers` is not significant. The default value for option is `{}`. It is error if same column is specified twice. It is allowed to specify implicitly covered columns explicitly.

As proposed in the issue scan can be done only among covered columns. `select` and `get` an such will return all columns. In future we may introduce an option for these operations to return only covered columns, like `index:select(key, {column_set = 'covered'})`.

### Introspection

Covered columns, both explicit and implicit, are visible in index object under `covers` key. The key is missing for the primary index. Column number in array are 1-based just as in case of describing index parts. The column numbers are sorted.

Example:
```
tarantool> box.space.test.index.sk
---
- unique: true
  parts:
  - fieldno: 3
    sort_order: asc
    type: string
    exclude_null: false
    is_nullable: false
  covers: [1, 3, 7, 10]
  id: 1
  space_id: 512
  type: TREE
  name: sk
...
```

## Persistence

The covered columns are stored as an array of column numbers in existing `opts` field of `_index` space under `covers` key. Only explicitly covered columns are stored. Column numbers are 0-based just as in case of `parts` field of the space.
