### ISSUE TITLE
Assertion `l->owner != fiber()` fails after replication reconfiguration and split brain 

### ISSUE THREAD

**Issue by filonenko-mikhail** [tarantool/tarantool#10073]
**Bug description**

* OS: MacOS m1
* OS Version: m1
* Architecture: arm64

Place `tarantool --version` output here.

```
tarantool --version
Tarantool Enterprise 3.1.0-0-g663f509
Target: Darwin-arm64-Debug
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/Users/michael.filonenko/work/tarantool-ee-3.1/static-build/tarantool-prefix -DENABLE_BACKTRACE=TRUE
Compiler: Clang-15.0.0.15000309
C_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common  -fmacro-prefix-map=/Users/michael.filonenko/work/tarantool-ee-3.1=. -std=c11 -Wall -Wextra -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror -g -ggdb -O0
CXX_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common  -fmacro-prefix-map=/Users/michael.filonenko/work/tarantool-ee-3.1=. -std=c++11 -Wall -Wextra -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror -g -ggdb -O0
```

**Steps to reproduce**

Run tarantool cluster

- tt init
- cat instances.enabled/app/config.yaml
```
credentials:
  users:
    guest:
      roles: [super]

replication:
  failover: election

groups:
  group001:
    replicasets:
      replicaset001:
        instances:
          instance001:
            iproto:
              listen:
                - uri: "127.0.0.1:3301"
          instance002:
            iproto:
              listen:
                - uri: "127.0.0.1:3302"
          instance003:
            iproto:
              listen:
                - uri: "127.0.0.1:3303"
```

tt run

make workload using many fibers

make box.ctl.promote() under load

make a split brain replication fault

try to restart replication

`r = box.cfg.replication box.cfg{replication={}} box.cfg{replication=r}`

```
2024-05-30 15:11:12.253 [13918] main/129/applier/127.0.0.1:3301 I> RAFT: leader is 3, follow
Assertion failed: (l->owner != fiber()), function latch_lock_timeout, file latch.h, line 139.
Watchdog 2024/05/30 15:11:12 (WARN): "signal: abort trap".
Watchdog 2024/05/30 15:11:12 (INFO): the Instance has shutdown.
```

```
#1  0x102cb9270 in backtrace_collect+256
#2  0x102ad1e9c in latch_lock_timeout(latch*, double)+156
#3  0x102ad1df4 in latch_lock(latch*)+32
#4  0x102ad425c in applier_apply_tx(applier*, stailq*)+200
#5  0x102ad3c44 in applier_process_batch(cmsg*)+332
#6  0x102acc60c in applier_subscribe(applier*)+3068
#7  0x102ac8d84 in applier_f(char*)+1764
#8  0x102936100 in fiber_cxx_invoke(int (*)(char*), char*)+32
#9  0x102cb03e8 in fiber_loop+268
#10 0x103469b88 in coro_startup+8

Assertion failed: (l->owner != fiber()), function latch_lock_timeout, file latch.h, line 145.
```

A clear and concise description of what you see.

**Expected behavior**
