### ISSUE TITLE
Unable to downgrade from 3.1 to 2.11

### ISSUE THREAD

**Issue by yngvar-antonsson** [tarantool/tarantool#10150]
**Bug description**

Tarantool brakes replication after downgrade, which leaves replica with old schema version.

3.1.0-0-g96f6d88

**Steps to reproduce**
Simple config:
```yaml
---
credentials:
  users:
    admin:
      password: secret-cluster-cookie
      roles:
      - super
groups:
  default:
    replicasets:
      s-1:
        leader: s-1-1
        instances:
          s-1-1:
            iproto:
              listen:
              - uri: localhost:3302
          s-1-2:
            iproto:
              listen:
              - uri: localhost:3303
iproto:
  advertise:
    peer:
      login: admin
replication:
  failover: manual
...

```
Run two tarantool instances iteractively.

```bash
TT_SNAPSHOT_DIR=./tmp/data/myapp.s1-master TT_WAL_DIR=./tmp/data/myapp.s1-master/ tarantool --name s-1-1 --config test-config.yml
TT_SNAPSHOT_DIR=./tmp/data/myapp.s1-replica TT_WAL_DIR=./tmp/data/myapp.s1-replica/ tarantool --name s-1-2 --config test-config.yml
```

Downgrading:
```lua
box.schema.downgrade('2.11.1')
```

```yaml
---
- error: 'builtin/box/upgrade.lua:1563: builtin/box/upgrade.lua:2153: Replicaset name
    is set. It is supported from version 3.0.0 There are more downgrade issues. To
    list them all call box.schema.downgrade_issues.'
...
```

Removing names:
```lua
box.space._schema:run_triggers(false)
box.space._schema:delete('replicaset_name')
box.space._schema:run_triggers(true)

box.space._cluster:run_triggers(false)
box.atomic(function()
    for _, tuple in box.space._cluster:pairs() do
        pcall(box.space._cluster.update, box.space._cluster, {tuple.id}, {{'#', 'name', 1}})
    end
end)
box.space._cluster:run_triggers(true)
box.schema.downgrade('2.11.1')
box.snapshot()
```

Replication is broken now, and the schema isn't upgraded on replica:

```yaml
replication:
    1:
      id: 1
      uuid: 7b6aee4d-4d0f-434b-8433-14e7a80584ed
      lsn: 3
      upstream:
        peer: admin@localhost:3302
        lag: 0.00015497207641602
        status: stopped
        idle: 69.274161999987
        message: Tarantool does not support replicaset name change (without 'force_recovery')
```
```lua
box.space._schema:select()
```
```yaml
---
- - ['replicaset_name', 's-1']
  - ['replicaset_uuid', '6a327cfb-cce3-47d1-8285-f98d965f0a1a']
  - ['version', 3, 1, 0]
...
```

**Actual behavior**

Replica is not downgraded.

**Expected behavior**

I believe that replica should get schema downgrade from its leader.
