### ISSUE TITLE
Config wrongly sets default value of the `replication.sync_timeout`

### ISSUE THREAD

**Issue by Serpentian** [tarantool/tarantool#10280]
Compat options are set after `instance_config.lua` is executed, so `replication_sync_timeout` is always 0, regardless of the compat option set.

I start the tarantool instance with the following config:

```yaml
compat:
     box_cfg_replication_synchro_timeout: 'new'
     box_cfg_replication_sync_timeout: 'old'

credentials:
    users:
        guest:
            roles: [super]

groups:
  group001:
    replicasets:
      replicaset001:
        instances:
          instance001:
            database:
              mode: rw
            iproto:
              listen:
              - uri: '127.0.0.1:3301'
```

`sync_timeout` must be 300, if compat option is `old`, however it's 0:

```
localhost:3301> box.cfg.replication_sync_timeout
---
- 0
...

localhost:3301> c = require('compat')
---
...

localhost:3301> c
---
- - box_cfg_replication_synchro_timeout: new
  - box_cfg_replication_sync_timeout: old
  - sql_priv: default (new)
  - binary_data_decoding: default (new)
  - fiber_channel_close_mode: default (new)
  - sql_seq_scan_default: default (new)
  - box_error_serialize_verbose: default (old)
  - box_error_unpack_type_and_code: default (old)
  - yaml_pretty_multiline: default (new)
  - box_info_cluster_meaning: default (new)
  - box_tuple_new_vararg: default (new)
  - c_func_iproto_multireturn: default (new)
  - box_tuple_extension: default (new)
  - box_session_push_deprecation: default (old)
  - json_escape_forward_slash: default (new)
  - box_space_max: default (new)
  - fiber_slice_default: default (new)
  - box_space_execute_priv: default (new)
  - console_session_scope_vars: default (old)
...
```

`box.NULL` must be used instead of that if condition in `default` value:

https://github.com/tarantool/tarantool/blob/a3ef8fb60382e747eed2cb521ebb3329dd4058f7/src/box/lua/config/instance_config.lua#L1473-L1478
