### ISSUE TITLE
config: allow to grant access to specific functions using `lua_call`

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#10304]
The declarative configuration allows to grant access to all global Lua functions (except built-in ones).

```yaml
credentials:
  users:
    alice:
      privileges:
        - permissions: [execute]
          lua_call: [all]
```

<details>
<summary>An excerpt from the instance config schema</summary>

----

https://github.com/tarantool/tarantool/blob/c68e8a8e029d849d68c6018ed00b5a79cc769222/src/box/lua/config/instance_config.lua#L1572-L1576

----
</details>

It is a rough equivalent of the following `box.schema.{user,role}.grant()` call:

```lua
box.schema.user.create('alice')
box.schema.user.grant('alice', 'execute', 'lua_call')
```

`box.schema.{user,role}.grant()` allows to grant access to a particular global Lua function using `lua_call` since the 3.0.0 release (see #9360):

```lua
box.schema.user.create('alice')
box.schema.user.grant('alice', 'execute', 'lua_call', 'my_func')
```

We should support it in the declarative configuration too.

An example of such configuration:

```yaml
credentials:
  users:
    alice:
      privileges:
        - permissions: [execute]
          lua_call: [my_func]
```
