### ISSUE TITLE
config: expose configured instance/replicaset/group names

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#10308]
## Context

Any instance that is started from the YAML configuration has instance name, replicaset name and group name. However, there is no API to obtain all of them in all the situations.

<details>
<summary>Details</summary>

----

`box.info.name` (https://github.com/tarantool/doc/issues/3468) and `box.info.replicaset.name` (https://github.com/tarantool/doc/issues/3467) *usually* show configured instance and replicaset names. However, it is not so during an upgrade from an 2.x snapshot (before calling `box.schema.upgrade()`), because these values are about names written to the database. The names are written to the database after the upgrade.

A group name from the YAML configuration is not shown anywhere. It can be deduced from `config:instances()` (https://github.com/tarantool/doc/issues/4105) using an instance name.

----
</details>

There is an internal API that allows to obtain the names:

```yaml
# tarantool> config._configdata_applied:names()
---
- instance_uuid: null
  replicaset_uuid: null
  instance_name: instance-001
  replicaset_name: replicaset-001
  group_name: group-001
...
```

It shows the names from the configuration and works before `box.schema.upgrade()`.

## Proposal

Expose the names from the public API:

```yaml
# tarantool> config:info()
# or
# tarantool> config:info('v2')
# or
# tarantool> box.info.config
---
- <..status, alerts, meta..>
  hierarchy:
    instance_name: instance-001
    replicaset_name: replicaset-001
    group_name: group-001
...
```

## Motivation

A seamless upgrade sometimes requires a knowledge about instance/replicaset names of the current instance.

For example, the `crud` module [finds](https://github.com/tarantool/crud/blob/98b120ef7095fa34525ef9d335a1458a2edf0cca/crud/common/vshard_utils.lua#L7-L27) the replicaset in `vshard`'s configuration to [determine](https://github.com/tarantool/crud/blob/98b120ef7095fa34525ef9d335a1458a2edf0cca/crud/common/vshard_utils.lua#L58-L77) an appropriate username to grant permissions to the storage functions (at least to ensure that they're already exist).

----

Also tracked in TNTP-347.
