### ISSUE TITLE
config: proper message if there are two instances with the same name

### ISSUE THREAD

**Issue by georgiy-belyanin** [tarantool/tarantool#10347]
### Description

Setting up the configuration file with two instances with the same names in the different replicasets ends up with the failed assertion. Now it's assumed every instance has it's unique name

### Config file
```yaml
groups:
  group-001:
    replicasets:
      replicaset-001:
        instances:
          i-001: {}
          i-002: {}
          i-003: {}
      replicaset-002:
        instances:
          i-001: {}
```

### Result
```
LuajitError: builtin/config/configdata.lua:300: assertion failed!
fatal error, exiting the event loop
```
This message provides no useful information about the error.

### Expected
The preciser message is expected.
```
Found two instances with the name i-001 in two different replicasets: replicaset-001, replicaset-002
```

Also tracked in TNTP-330.
