### ISSUE TITLE
config: `credentials` section processing error is not quite verbose

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#10359]
`src/box/lua/config/applier/credentials.lua` just passes an error from a lower level upward to logs or alerts. It is not obvious from where the error comes.

For example, we have the following config:

```yaml
credentials:
  users:
    guest:
      roles: [super]

roles: [errinj]

groups:
  g-001:
    replicasets:
      r-001:
        instances:
          i-001: {}
```

And the following `errinj.lua` role (AFAIR, error injections are compiled into tarantol only with the debug build type):

```lua
return {
    validate = function(_cfg)
        -- No-op.
    end,
    apply = function(_cfg)
        box.error.injection.set('ERRINJ_WAL_IO', true)
    end,
    stop = function()
        box.error.injection.set('ERRINJ_WAL_IO', false)
    end,
}
```

Let's start tarantool (I use a build from PR #10248):

```sh
$ tarantool --config config.yaml --name i-001 -i
```

Add something into the `credentials` sections in config:

```yaml
credentials:
  users:
    guest:
      roles: [super]
    myuser: {}        # !!
```

And run `config:reload()` from the console.

The logs contains:

```syslog
2024-08-02 20:48:54.080 [28224] main/119/sync_credentials wal.c:1335 E> ER_WAL_IO: Failed to write to disk
2024-08-02 20:48:54.080 [28224] main/104/interactive/tarantool.config log.lua:130 E> Failed to write to disk
```

The alerts contains:

```yaml
# tarantool> config:info('v2')
---
- status: check_errors
  meta:
    last: []
    active: []
  alerts:
  - type: error
    message: Failed to write to disk
    timestamp: 2024-08-02T20:48:54.080304+0300
...
```

It is hard to deduce that the reason is an action performed by the `credentials` section applier. The fiber name that was added in PR #10248 helps a bit, though.

Ideally, we should accompany the error message with information about a certain operation that was failed: writing 'myuser' user into the database in this case.

Also tracked in TNTP-329.
