### ISSUE TITLE
config: `credentials` aren't re-applied after downgrading and upgrading

### ISSUE THREAD

**Issue by georgiy-belyanin** [tarantool/tarantool#10411]
### Steps to reproduce:
Still happens after the fix #10248 of `SCHEMA_NEEDS_UPGRADE` problem #9849.

Create a config with the `credentials` section.
```yaml
credentials:
  users:
    guest:
      roles: [super]
```

Execute the following: 
```lua
-- Technically, you may specify any version
-- on which the downgrade is supported
box.schema.downgrade('3.0.0')
box.snapshot()
```
Update the config by changing the credentials without restarting the instance, e.g. add the user:
```yaml
credentials:
  users:
    guest:
      roles: [super]
    not-guest:
      roles: [super]
```
Call the config reload and check if the user is available:
```
require('config'):reload()
box.schema.user.info('not-guest')
-- The last call results with:
-- ---
-- - error: User 'not-guest' is not found
-- ...
```

### The problem
It mainly occur even after the fix because the need of upgrade is checked only once at the start of the credentials upgrade worker. See [this section of the fix](https://github.com/tarantool/tarantool/blob/d5426d9139c208b1b56af6a961a2dec0abd52d0f/src/box/lua/config/applier/credentials.lua#L909-L930).

### Possible solutions
There are at least two possible solutions:
- Make the worker restart every `apply()` of the config.
- Put the schema upgraded status check in the worker loop
