### ISSUE TITLE
config: can't add new tarantool 3.x replica into 2.x replicaset

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#10426]
Let's start an instance using Tarantool 2.11.3 (the last 2.11 release at the moment of writing).

i-001.lua:

```lua
#!/usr/bin/env tarantool

local fio = require('fio')

pcall(fio.mktree, 'var/lib/i-001')

box.cfg({
    listen = 'localhost:3301',
    memtx_dir = 'var/lib/i-001',
    wal_dir = 'var/lib/i-001',
})
box.schema.user.grant('guest', 'super')
```

```sh
$ /path/to/tarantool-2.11.3/tarantool -i i-001.lua
```

And attempt to add a replica running on Tarantool 3.2.0-entrypoint-226-g0c1226b5ca (current `master`).

config.yaml:

```yaml
replication:
  failover: manual

groups:
  g-001:
    replicasets:
      r-001:
        database:
          replicaset_uuid: b93ccd9e-b38c-4193-bf4a-26ff573f238c # place your one from 2.11
        leader: i-001
        instances:
          i-001:
            database:
              instance_uuid: 9482d721-179d-4562-a6a9-62e4d450e7ac # place your one from 2.11
            iproto:
              listen:
                - uri: 'localhost:3301'
          i-002:
            iproto:
              listen:
                - uri: 'localhost:3302'
```

```sh
$ /path/to/tarantool-3.x/tarantool --config config.yaml --name i-002 -i
```

Result:

> F> can't initialize storage: Replicaset name mismatch: name 'r-001' provided in config confilcts with the instance one '<no-name>'

The instance is unable to start. Also, a lack or a presence of the replicaset UUID and the instance UUID for `i-001` doesn't change it.

The replicaset name is passed to `box.cfg()` from here in this case:

https://github.com/tarantool/tarantool/blob/12169c290b6cbed20ab60567b29da36bd8e5e6cf/src/box/lua/config/applier/box_cfg.lua#L581-L583
