### ISSUE TITLE
Roles configuration parameters aren't merged

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#10450]
**Bug description**

In contrast to built-in configuration entries, application role parameters aren't merged - instead the lowest defined configuration is used as is, without taking into account upper levels. This is inconsistent, unexpected, and inconvenient.

For example, consider an application role that implements sharding. It would have a bunch of parameters common for all storage shards, which are convenient to set at the group or global level, but sometimes one may need to set special parameters for a particular replicaset, for example, to mark a storage shard for decommission. Instead of extending the global configuration, this would reset it, so the user would have to copy all parameters from the global level, which is ugly.

The suggestion is to merge role configuration parameters by the following rules:
- If both entries are maps, recursively merge all keys.
- Otherwise, use the parameter defined at the lower level.

**Steps to reproduce**

Reproduced with Tarantool 3.2.0-entrypoint-234-gc3ed71f37ca1.

Run the application role and check the logs:

```yaml
# config.yaml

roles_cfg:
  greeter:
    greeting: Hello!

groups:
  group001:
    replicasets:
      replicaset001:
        instances:
          instance001:
            roles: [ greeter ]
            roles_cfg:
              greeter:
                name:  greeter_1
```

```lua
-- greeter.lua

local log = require('log').new("greeter")

local function validate()
end

local function apply(cfg)
    log.info("%s: %s", cfg.name, cfg.greeting)
end

local function stop()
end

return {
    validate = validate,
    apply = apply,
    stop = stop,
}
```

**Actual behavior**

```
2024-08-20 17:08:55.343 [385261] main/104/interactive/greeter I> greeter_1: nil
```

**Expected behavior**

```
2024-08-20 17:08:55.343 [385261] main/104/interactive/greeter I> greeter_1: Hello!
```

----

Also tracked in TNTP-308.

**Comment by oleg-jukovec** [comment]
How to exclude some upper-level parameter in this case?

**Comment by locker** [comment]
> How to exclude some upper-level parameter in this case?

Reset them at a lower level.

**Comment by locker** [comment]
> > > How to exclude some upper-level parameter in this case?
> > 
> > 
> > Reset them at a lower level.
> 
> Do you mean that?
> 
> ```yaml
> roles_cfg:
>   greeter:
>     name:  greeter_1
>     greeting: nil
> ```

I meant resetting them with a proper value:

```yaml
roles_cfg:
  greeter:
    name:  greeter_1
    greeting: My greeting
```

Like it's done with the built-in parameters.
