### ISSUE TITLE
config: vshard cluster can't have instances without configured router or storage

### ISSUE THREAD

**Issue by AndreyOrlovSP** [tarantool/tarantool#10458]
*(The description is a bit edited by @Totktonada.)*

----

If you add instances into the Tarantool configuration without specifying `sharding.roles`, other Tarantool instances will not start with the following error:

```lua
main utils.c:679 E> LuajitError: builtin/config/configdata.lua:182: bad argument #1 to 'pairs' (table expected, got nil)
```

Part of configuration:

``` yaml                   
groups:
  g:
    replicasets:
      r:
        instances:
          i-1:
            iproto:
              advertise:
                client: 10.0.1.19:3311
              listen:
              - uri: 10.0.1.19:3311
          i-2:
            iproto:
              advertise:
                client: 10.0.1.12:3312
              listen:
              - uri: 10.0.1.12:3312
```

* OS Version: [Astra Linux SE 1.7 Орел]
* Architecture: [amd64]

Tarantool version 3.1.0-0-g663f509a2

**Actual behavior**

Tarantool instances will not start with the error ```main utils.c:679 E> LuajitError: builtin/config/configdata.lua:182: bad argument #1 to 'pairs' (table expected, got nil)```.

**Expected behavior**

It is necessary to give an instruction to action in the error text, or to start Tarantool instances.

**Details**

The problem is that we assume that if any instance in the cluster has some sharding role, all the instances in the cluster should have some sharding role.

https://github.com/tarantool/tarantool/blob/d33b14793bea58520139172599621daaaf66b947/src/box/lua/config/configdata.lua#L180-L187

We should handle `nil`/`box.NULL` value of `sharding.roles` here.

Also tracked in TNTP-307.
