### ISSUE TITLE
Backtrace is broken in RPM builds

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#105]
The stock RPM builds provided at tarantool.org/dist do not have a proper backtrace.

Check: 

```
tarantool> show fiber
...
  - fid:    0
    csw: 2
    name: zombie
    stack: 0x7f6a40256000
    backtrace:
        - { frame: 0x7f6a40255f90, caller: 0x440c6f }
        - { frame: 0x7f6a40255fd0, caller: 0x45fdb7 }
        - { frame: 0x7f6a40256000, caller: 0x411a50 }
```

Should be:

```
tarantool> show fiber
#0  0x7ff5c4ccb038 in ?
  - fid:    0
    csw: 2
    name: zombie
    stack: 0x7ff5bc999000
    backtrace:
#0  0x44f1e5 in fiber_yield()+128
#1  0x44f73f in fiber_loop(void*)+127
#2  0x47d6b0 in coro_init+68
#3  0x412940 in ?
```

This is because at build:

```
kostja@olah ~/work/tarantool % cmake .
-- ENABLE_BACKTRACE: ON (symbol resolve: False)
```

Should be:

```
kostja@olah ~/work/tarantool % cmake .
-- ENABLE_BACKTRACE: ON (symbol resolve: True)
```

This is autodetected at configuration time. To enable symbols resolve, you should install binutils-devel at compile time.
