### ISSUE TITLE
config: use supervised failover priorities to select the bootstrap leader

### ISSUE THREAD

**Issue by georgiy-belyanin** [tarantool/tarantool#10552]
After merging #10316 the priorities to select the master by the supervised failover coordinator could be specified in the config file. Though if you're running the cluster for the first time the bootstrap leader is still the first instance sorted by the name in the lexicographical order. This is a bit confusing.

The bootstrap leader selection in `replication.failover: supervised` mode should consider the `failover.replicasets.<replicaset-id>.priority` section by choosing the instance with the highest priority.

For example when bootstrapping the `replicaset-001` with five instances and the failover configured like this:
```yaml
replication:
  failover: supervised
failover:
  replicasets:
    replicaset-001:
      priority:
        instance-002: 5
        instance-003: -3
        instance-004: 3
        instance-005: 4
```
The `instance-002` should be chosen as a leader.

Part of TNTP-194
