### ISSUE TITLE
config: context variables do not work in roles_cfg.<...> and app.cfg.<...>

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#10595]
Version: all existing tarantool 3.x (tested on 3.2.0).

Config:

```yaml
config:
  context:
    title:
      from: env
      env: TITLE

process:
  title: '{{ context.title }}'

app:
  cfg:
    title: '{{ context.title }}'

roles_cfg:
  foo:
    title: '{{ context.title }}'

groups:
  g:
    replicasets:
      r:
        instances:
          i-001: {}
```

Test:

```lua
$ TITLE=xxx tarantool -i --name i-001 --config config.yaml
tarantool> config = require('config')

tarantool> config:get('process.title')
---
- xxx
...

tarantool> config:get('app.cfg.title')
---
- '{{ context.title }}'
...

tarantool> config:get('roles_cfg.foo.title')
---
- '{{ context.title }}'
...
```

<details>
<summary>And the same for built-in replacements</summary>

```yaml
process:
  title: '{{ instance_name }}'

app:
  cfg:
    title: '{{ instance_name }}'

roles_cfg:
  foo:
    title: '{{ instance_name }}'

groups:
  g:
    replicasets:
      r:
        instances:
          i-001: {}
```

```lua
$ tarantool -i --name i-001 --config config.yaml
tarantool> config = require('config')

tarantool> config:get('process.title')
---
- i-001
...

tarantool> config:get('app.cfg.title')
---
- '{{ instance_name }}'
...

tarantool> config:get('roles_cfg.foo.title')
---
- '{{ instance_name }}'
...
```
</details>

The reason is that `app.cfg.<...>` and `roles_cfg.<...>` have `any` type and this type is not traversed down by the `<schema object>:map()` method.

https://github.com/tarantool/tarantool/blob/f1144c533b6c52c324ffe1cc4fcaeab1f2f6cd9f/src/box/lua/config/instance_config.lua#L444

Also tracked in TNTP-372
