### ISSUE TITLE
config: show a raw cluster configuration

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#10617]
## Context

Let's assume that a remote configuration storage (etcd-based or tarantool-based) in in use and it stores several `<prefix>/config/*` keys.

The configuration is processed in the following steps (simplified):

1. Merge cluster configurations from `<prefix>/config/*` into a single cluster configuration.
2. Merge global-group-replicaset-instance level options of the single cluster configuration to an instance configuration.
3. Apply default values and expand `{{ <...> }}` variables.

A user is able to show the resulting instance configuration using `config:get()` for the current instance and other instances.

However, the user is not able to see the intermediate cluster configuration that is produced by merging from the `<prefix>/config/*` keys.

It complicates understanding how this merging mechanism works.

## Example

Let's consider an example.

We have some common settings in `/foo/config/all`:

```yaml
groups:
  g:
    roles_cfg:
      myrole:
        mode: general
    replicasets:
      r:
        instances:
          i-001: {}
```

And we have a separate key `/foo/config/dynamic` to change the `myrole.mode` value dynamically:

```yaml
roles_cfg:
  myrole:
    mode: specific
```

In this case, `config:get('roles_cfg.myrole.mode')` gives `general` and it is not very clear why.

The reason is that the resulting cluster configuration is the following:

```yaml
roles_cfg:
  myrole:
    mode: specific

groups:
  g:
    roles_cfg:
      myrole:
        mode: general
    replicasets:
      r:
        instances:
          i-001: {}
```

The group-level option has a higher priority than the global-level one. So, the resulting instance config is the following (excluding defaults):

```yaml
roles_cfg:
  myrole:
    mode: general
```

A user should specify the role's configuration on the group level too if it is set on this level in the main configuration:

```yaml
groups:
  g:
    roles_cfg:
      myrole:
        mode: specific
```

## Proposal

Add a method that return the single cluster configuration after merging all the keys. The name of the method is to be defined.

## History

We considered this method before, in scope of #9680. At this time it was looked like all our needs are resolved by `config:get(<...>, {instance = <...>})` and `config:instances()`. We [discarded](https://github.com/tarantool/tarantool/pull/9808#discussion_r1524447470) this method.

However, now it looks like it would be convenient for diagnostic purposes.
