### ISSUE TITLE
crush when run HEALTHCHECK script of docker image

### ISSUE THREAD

**Issue by 1azar** [tarantool/tarantool#10627]
**Bug description**

in docker container i got crush of `/usr/local/bin/status` script when trying create master-master replicaset

* OS: Linux
* OS Version: Ubuntu 22.04.4 LTS
* Architecture: amd64

```
Tarantool 3.0.1-0-g31c2ddb310
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/tarantool/static-build/tarantool-prefix -DENABLE_BACKTRACE=TRUE
Compiler: GNU-8.3.1
C_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -static-libstdc++ -fno-common -msse2  -fmacro-prefix-map=/tarantool=. -std=c11 -Wall -Wextra -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type -O2 -g -DNDEBUG -ggdb -O2
CXX_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -static-libstdc++ -fno-common -msse2  -fmacro-prefix-map=/tarantool=. -std=c++11 -Wall -Wextra -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -O2 -g -DNDEBUG -ggdb -O2
```

**Steps to reproduce**

docker compose file `./docker-compose.yml`:
```
services:
  instance-001:
    image: tarantool/tarantool:3.1.2
    container_name: shard_1_replica_0
    volumes:
      - ./app:/opt/tarantool/app
#      - ./data:/var/lib/tarantool
    environment:
      - TT_APP_NAME=app
      - TT_INSTANCE_NAME=instance-001
      - REPLICATOR_PASSWORD=secret
    networks:
      - tarantool
    ports:
      - "3301:3301"

  instance-002:
    image: tarantool/tarantool:3.0.1
    container_name: shard_1_replica_1
    volumes:
      - ./app:/opt/tarantool/app
#      - ./data:/var/lib/tarantool
    environment:
      - TT_APP_NAME=app
      - TT_INSTANCE_NAME=instance-002
      - REPLICATOR_PASSWORD=secret
    networks:
      - tarantool
    ports:
      - "3302:3302"

networks:
  tarantool:
    driver: bridge
```

tarantool config file `./app/config.yml`:
```
config:
  context:
    replicator_password:
      from: env
      env: REPLICATOR_PASSWORD

credentials:
  users:
    replicator:
      password: '{{ context.replicator_password }}'
      roles: [replication]
      
iproto:
  advertise:
    peer:
      login: replicator

replication:
  failover: off

groups:
  group-001:
    replicasets:
      replicaset-001:
        instances:
          instance-001:
            database:
                mode: rw
            iproto:
              listen:
                - uri: instance-001:3301
          instance-002:
            database:
                mode: rw
            iproto:
              listen:
                - uri: instance-002:3302
```

1. run `docker compose up -d`

now i see 2 containers firs is healthy second is unhealthy, according to container status:
```
CONTAINER ID   IMAGE                       COMMAND                  CREATED      STATUS                   PORTS
               NAMES
0811789eab6e   tarantool/tarantool:3.0.1   "/docker-entrypoint.…"   2 days ago   Up 7 hours (healthy)     3301/tcp, 0.0.0.0:3302->3302/tcp, :::3302->3302/tcp   shard_1_replica_1
32772d7ecf05   tarantool/tarantool:3.1.2   "/docker-entrypoint.…"   2 days ago   Up 7 hours (unhealthy)   0.0.0.0:3301->3301/tcp, :::3301->3301/tcp             shard_1_replica_0
```

2. tryed to run healthcheck script manually: 
on healthy container:
```
root@0811789eab6e:/usr/local/bin# ./status
running
```
on unhealthy container:
```
root@32772d7ecf05:/usr/local/bin# ./status
2024/09/28 21:24:13 whoops! It looks like something is wrong with this version of Tarantool CLI.
Error: Unhandled internal error: runtime error: index out of range [0] with length 0
Version: Tarantool CLI version 2.4.0, linux/amd64. commit: 060408f
Stacktrace:
goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.22.5/x64/src/runtime/debug/stack.go:24 +0x5e
github.com/tarantool/tt/cli/util.InternalError({0x13dee24, 0x1c}, 0xc00061f5a8?, {0xc00061f560, 0x1, 0x1})
        /home/runner/work/tt/tt/cli/util/util.go:137 +0x98
main.main.func1()
        /home/runner/work/tt/tt/cli/main.go:18 +0x5a
panic({0x1341ce0?, 0xc000150138?})
        /opt/hostedtoolcache/go/1.22.5/x64/src/runtime/panic.go:770 +0x132
github.com/tarantool/tt/cli/connect.Eval({{0x0, 0x0}, {0x0, 0x0}, {0x7ffc746c0908, 0x1}, 0x0, 0x0, {0x0, 0x0}, ...}, ...)
        /home/runner/work/tt/tt/cli/connect/connect.go:125 +0x6a5
github.com/tarantool/tt/cli/cmd.internalConnectModule(0x1f49a60, {0xc000378d40, 0x1, 0x2})
        /home/runner/work/tt/tt/cli/cmd/connect.go:216 +0x2db
github.com/tarantool/tt/cli/modules.RunCmd(0x1f49a60, {0xc000525970, 0xa}, 0x2aed88ae00000000?, 0x152e888, {0xc000378d40, 0x1, 0x2})
        /home/runner/work/tt/tt/cli/modules/run.go:36 +0xb2
github.com/tarantool/tt/cli/cmd.NewConnectCmd.func1(0xc0000d4008, {0xc000378d40, 0x1, 0x2})
        /home/runner/work/tt/tt/cli/cmd/connect.go:65 +0x94
github.com/spf13/cobra.(*Command).execute(0xc0000d4008, {0xc000136020, 0x2, 0x2})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xab1
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000b8308)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/tarantool/tt/cli/cmd.Execute()
        /home/runner/work/tt/tt/cli/cmd/root.go:212 +0x1e
main.main()
        /home/runner/work/tt/tt/cli/main.go:23 +0x35
not running
```

PS:
I also have the same problem when trying to create master-master on 2 different VMs. In this case i have tarantool 3.1.2 and 2 unhealthy container which got same panic when run status script:
```
root@aab63484f46f:/usr/local/bin# ./status
2024/09/28 21:28:21 whoops! It looks like something is wrong with this version of Tarantool CLI.
Error: Unhandled internal error: runtime error: index out of range [0] with length 0
Version: Tarantool CLI version 2.4.0, linux/amd64. commit: 060408f
Stacktrace:
goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.22.5/x64/src/runtime/debug/stack.go:24 +0x5e
github.com/tarantool/tt/cli/util.InternalError({0x13dee24, 0x1c}, 0xc00061f5a8?, {0xc00061f560, 0x1, 0x1})
        /home/runner/work/tt/tt/cli/util/util.go:137 +0x98
main.main.func1()
        /home/runner/work/tt/tt/cli/main.go:18 +0x5a
panic({0x1341ce0?, 0xc000152120?})
        /opt/hostedtoolcache/go/1.22.5/x64/src/runtime/panic.go:770 +0x132
github.com/tarantool/tt/cli/connect.Eval({{0x0, 0x0}, {0x0, 0x0}, {0x7ffc645027ee, 0x1}, 0x0, 0x0, {0x0, 0x0}, ...}, ...)
        /home/runner/work/tt/tt/cli/connect/connect.go:125 +0x6a5
github.com/tarantool/tt/cli/cmd.internalConnectModule(0x1f49a60, {0xc000370fa0, 0x1, 0x2})
        /home/runner/work/tt/tt/cli/cmd/connect.go:216 +0x2db
github.com/tarantool/tt/cli/modules.RunCmd(0x1f49a60, {0xc000015970, 0xa}, 0x41c8bb0b00000000?, 0x152e888, {0xc000370fa0, 0x1, 0x2})
        /home/runner/work/tt/tt/cli/modules/run.go:36 +0xb2
github.com/tarantool/tt/cli/cmd.NewConnectCmd.func1(0xc0006abb08, {0xc000370fa0, 0x1, 0x2})
        /home/runner/work/tt/tt/cli/cmd/connect.go:65 +0x94
github.com/spf13/cobra.(*Command).execute(0xc0006abb08, {0xc000134020, 0x2, 0x2})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xab1
github.com/spf13/cobra.(*Command).ExecuteC(0xc0006aa008)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/tarantool/tt/cli/cmd.Execute()
        /home/runner/work/tt/tt/cli/cmd/root.go:212 +0x1e
main.main()
        /home/runner/work/tt/tt/cli/main.go:23 +0x35
not running
```
