### ISSUE TITLE
config: scaling a replicaset down to one instance doesn't work

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#10716]
For example, we have the following configuration with two instances in a replicaset:

```yaml
credentials:
  users:
    replicator:
      password: secret
      roles: [replication]

iproto:
  listen:
  - uri: 'unix/:./{{ instance_name }}.iproto'
  advertise:
    peer:
      login: 'replicator'

replication:
  failover: manual

groups:
  g-001:
    replicasets:
      r-001:
        leader: i-001
        instances:
          i-001: {}
          i-002: {}
```

1. Start the replicaset:

   ```sh
   $ tarantool -i --config config.yaml --name i-001
   ```

   ```sh
   $ tarantool -i --config config.yaml --name i-002
   ```

2. Drop `i-002` from the config.
3. Reload configuration on `i-001`:

   ```yaml
   i-001> config = require('config')
   i-001> config:reload()
   ```

   It is expected that `i-002` is removed from `box.cfg.replication`.

   Actual result:

   ```yaml
   i-001> box.cfg.replication
   ---
   - - password: secret
       uri: unix/:./i-001.iproto
       login: replicator
     - password: secret
       uri: unix/:./i-002.iproto
       login: replicator
   ...
   ```
4. Stop `i-002`.
5. Observe warnings in `box.info.replication`:

   ```yaml
   i-001> box.info.replication
   ---
   - 1:
       id: 1
       uuid: 3a19e457-5984-4e70-b7a5-5645e962d8f3
       lsn: 7
       name: i-001
     2:
       id: 2
       uuid: ca16036d-7d51-4c82-aa18-ca1d7f1d1844
       lsn: 0
       upstream:
         peer: replicator@unix/:./i-002.iproto
         lag: 0.00017929077148438
         status: disconnected
         idle: 122.068509099
         message: 'connect to unix/:./i-002.iproto, called on fd 25, aka unix/:(socket):
           No such file or directory'
         system_message: No such file or directory
       name: i-002
       downstream:
         status: stopped
         message: 'unexpected EOF when reading from socket, called on fd 25, aka unix/:(socket),
           peer of unix/:(socket): Broken pipe'
         system_message: Broken pipe
   ...
   ```
6. Fix it:

   ```lua
   i-001> box.cfg{replication = box.cfg.replication[1]}
   ```
7. Observe less warnings in `box.info.replication`:

   ```yaml
   i-001> box.info.replication
   ---
   - 1:
       id: 1
       uuid: 3a19e457-5984-4e70-b7a5-5645e962d8f3
       lsn: 7
       name: i-001
     2:
       id: 2
       uuid: ca16036d-7d51-4c82-aa18-ca1d7f1d1844
       lsn: 0
       downstream:
         status: stopped
         message: 'unexpected EOF when reading from socket, called on fd 25, aka unix/:(socket),
           peer of unix/:(socket): Broken pipe'
         system_message: Broken pipe
       name: i-002
   ...
   ```

The reason is `return nil` in the following code:

https://github.com/tarantool/tarantool/blob/b33f17b25de6bcbe3ebc236250976e4a0250e75e/src/box/lua/config/applier/box_cfg.lua#L8-L12

This `nil` is passed to `box.cfg({replication = <...>})` and interpreted by `box.cfg()` as an instruction to leave the parameter as is. We should pass `box.NULL` instead.

Also tracked in TNTP-243.
