### ISSUE TITLE
config: log.modules removal has no effect

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#10728]
```yaml
log:
  modules:
    foo: debug

groups:
  g-001:
    replicasets:
      r-001:
        instances:
          i-001: {}
```

```sh
$ tarantool -i --config config.yaml --name i-001
```

Verify the configuration:

```lua
tarantool> require('log').new('foo').debug('hello')
2024-10-21 21:07:01.174 [14573] main/104/interactive/foo D> hello
```

Change `config.yaml`: remove the `log` section from it:

```yaml
groups:
  g-001:
    replicasets:
      r-001:
        instances:
          i-001: {}
```

Reload the configuration:

```lua
tarantool> require('config'):reload()
```

Verify that `log.modules` is dropped to its default:

```lua
tarantool> require('log').new('foo').debug('hello')
2024-10-21 21:09:17.950 [14573] main/104/interactive/foo D> hello
```

Nope, it doesn't. Expected no log message.

Jira issue: TNTP-243.
