### ISSUE TITLE
config: temporary exclude an instance from the replicaset

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#10776]
The proposal is to add an option to temporary exclude an instance from the replicaset.

```yaml
groups:
  g:
    replicasets:
      r:
        instances:
          i-001: {}
          i-002: {}
          i-003: {}
          i-004:
            replication:
              disabled: true
```

When the option is enabled:

1. The instance can't be bootstrapped (a local snapshot is required to start).
2. `i-004` has an empty upstreams list (`box.cfg.replication`).
3. Other replicaset members have no `i-004` in the upstreams list.

The effect of the option is mostly equivalent to removal of the instance from the config, but it is sometimes more convenient to add such a marker instead. Useful for repairing activities.

Jira: TNTP-364
