### ISSUE TITLE
cluster cannot start  when advertise peer login defined

### ISSUE THREAD

**Issue by R-omk** [tarantool/tarantool#10800]
**Bug description**

can't run a simple replicaset from crud example when iproto advertise peer login defined

version: 3.3.0-entrypoint-196-gf69e2ae488
version: 3.2.0-0-g6df312b1971

```
C> failed  to connect to 3 out of 3 replicas
E> ER_CFG: Incorrect value for option 'replication': failed to connect to one or more replicas
```

**Steps to reproduce**

docker compose  build 
docker compose  up
docker compose  down

**Actual behavior**

 failed  to connect to 3 out of 3 replicas

**Expected behavior**

the cluster starts, all nodes are added to the replicaset, there is an elected leader.

assets: 

<details>
  <summary>docker-compose.yaml</summary>
  

  
```yaml

x-common-env: &common-env
  TT_APP_NAME: app

x-common-config: &common-config
  image: tt-app
  build:
    dockerfile_inline: |
      FROM tarantool/tarantool:3.2.0
      RUN apt update  \
          && apt install -y git gcc  build-essential cmake autoconf automake make zlib1g-dev libssl-dev libtool libreadline-dev libncurses5-dev libunwind-dev libicu-dev
      RUN tt rocks install crud
    #context: docker     # try build latest master - same issue
    #dockerfile: Dockerfile # master
  volumes:
    - ./app:/opt/tarantool/app
#    - ./data:/var/lib/tarantool
  environment:
    <<: *common-env
  networks:
    - tarantool

services:
  instance-001:
    <<: *common-config
    container_name: app-instance-001
    environment:
      <<: *common-env
      TT_INSTANCE_NAME: instance-001

  instance-002:
    <<: *common-config
    container_name: app-instance-002
    environment:
      <<: *common-env
      TT_INSTANCE_NAME: instance-002

  instance-003:
    <<: *common-config
    container_name: app-instance-003
    environment:
      <<: *common-env
      TT_INSTANCE_NAME: instance-003

networks:
  tarantool:
    driver: bridge
```
  
</details>

<details>
  <summary>app/config.yaml</summary>
  
  
```yaml

# works with this conf [credentials, iproto]

# credentials:
#   users:
#     guest:
#       roles:
#         - super
#         - sharding
#         - replication

# iproto:
#   listen:
#   - uri: 0.0.0.0:3301


# stuck with this conf [credentials, iproto]

credentials:
  users:
    replicator:
      password: replicating
      roles:
        - replication
    storage:
      password: storing-buckets
      roles:
        - sharding
    guest:
      roles:
        - super

iproto:
  advertise:
    peer:
      login: replicator
    sharding:
      login: storage


sharding:
  bucket_count: 1000

replication:
  failover: election
  #failover: manual

groups:
  group-001:
    sharding:
      roles:
      - router
      - storage
    roles: [ roles.crud-router, roles.crud-storage ]
    roles_cfg: {}
    # app:
    #   module: my    # simple example from crud repo
    replicasets:
      replicaset-001:
        #leader: instance-001 #  for replication: failover: manual
        instances:
          instance-001:
            iproto:
              advertise:
                peer:
                  uri: instance-001:3301
          instance-002:
            iproto:
              advertise:                
                peer:
                  uri: instance-002:3301                
          instance-003:
            iproto:
              advertise:
                peer:
                  uri: instance-003:3301                

```
  
</details>

**Comment by Totktonada** [comment]
If `iproto.listen` is not set, tarantool doesn't listen on any TCP port.

**Comment by Totktonada** [comment]
BTW, you may also be interested in the discussion in #10560.

**Comment by R-omk** [comment]
> If iproto.listen is not set, tarantool doesn't listen on any TCP port.

@Totktonada 
Indeed, I missed this, but still I can’t achieve stable operation of the cluster, if possible, try it yourself.

```diff
iproto:
+  listen:
+    - uri: 0.0.0.0:3301
  advertise:
    peer:
      login: replicator
    sharding:
      login: storage

```

one of the three hosts still can't start

```
2024-11-11 07:43:22.351 [1] main/123/sync_credentials/tarantool.config log.lua:130 W> box.schema.role.grant("sharding", "execute", "function", "vshard.storage.buckets_discovery") has failed because either the object has not been created yet, a database schema upgrade has not been performed, or the privilege write has failed (separate alert reported)
2024-11-11 07:43:22.351 [1] main/123/sync_credentials/tarantool.config log.lua:130 W> box.schema.role.grant("sharding", "execute", "function", "vshard.storage.bucket_recv") has failed because either the object has not been created yet, a database schema upgrade has not been performed, or the privilege write has failed (separate alert reported)
2024-11-11 07:43:22.353 [1] main/104/interactive/tarantool.config log.lua:130 W> sharding configuration: unsuitable URI "0.0.0.0:3301": INADDR_ANY (0.0.0.0) cannot be used to create a client socket
2024-11-11 07:43:22.354 [1] main utils.c:687 E> LuajitError: No suitable URI provided for instance "instance-003"
2024-11-11 07:43:22.354 [1] main main.cc:1085 F> fatal error, exiting the event loop

```

it is possible to start only if I disable "storage" role

**Comment by Totktonada** [comment]
`advertise.sharding` is set, so `advertise.peer` is ignored when configuring sharding. You need to add the `uri` field to it similarly to how it is done for `advertise.peer`. If you are (really) interested, there is a diagram in https://github.com/tarantool/doc/issues/4120#issuecomment-2167667791.

BTW, it seems, you can make it shorter:

```yaml
iproto:
  listen:
    - uri: 0.0.0.0:3301
  advertise:
    peer:
      login: replicator
      uri: '{{ instance_name }}:3301'
    sharding:
      login: storage
      uri: '{{ instance_name }}:3301'
```
