### ISSUE TITLE
config: don't make a learner instance a bootstrap leader

### ISSUE THREAD

**Issue by georgiy-belyanin** [tarantool/tarantool#10842]
After merging #10805 and tarantool/tarantool-ee#992 there is an option `failover.replicasets.<replicaset-id>.learners` for the supervised failover to ignore some instances as master candidates. Even though it's still possible for the specified instances to be RW since the instance need to be RW after finishing bootstrapping.

This makes the failover wait until instance goes RO before appointing other instances.

It's suggested to select only non-learner instances as candidates when choosing the bootstrap leader and using `replication.failover: supervised` and `replication.bootstrap_strategy: auto`. 

For example in this scenario `i-002` should be chosen as a bootstrap leader since `i-001` is marked as a learner:
```yaml
replication:
  failover: supervised

failover:
  replicasets:
    r-001:
      learners:
        - i-001

groups:
  g-001:
    replicasets:
      r-001:
        instances:
          i-001: {}
          i-002: {}
```

A question to discuss: what to do if all of the instances are marked as non-appointable?

Jira task: [TNTP-792](https://jira.vk.team/browse/TNTP-792).
