### ISSUE TITLE
config: config:get() changes option path if it is a table

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#10855]
Config:

```yaml
credentials:
  users:
    guest:
      roles: [super]

iproto:
  listen:
  - uri: 'unix/:./{{ instance_name }}.iproto'

groups:
  g-001:
    replicasets:
      r-001:
        instances:
          i-001: {}
```

How to run:

```shell
$ tarantool -i --config config.yaml --name i-001
```

Testing scenario:

```yaml
tarantool> config = require('config')
tarantool> path = {'fiber', 'slice'}
tarantool> config:get(path)
---
- err: 1
  warn: 0.5
...

tarantool> path
---
- []
...
```

`path` shouldn't be changed.

The cause is the `<schema object>:get()` implementation. `<schema object>:set()` is also affected.

We should copy the user-provided table:

```diff
diff --git a/src/box/lua/config/utils/schema.lua b/src/box/lua/config/utils/schema.lua
index 16f6c04dab..8e06107cba 100644
--- a/src/box/lua/config/utils/schema.lua
+++ b/src/box/lua/config/utils/schema.lua
@@ -888,7 +888,7 @@ function methods.get(self, data, path)
         -- The `path` field is already in the context and it means
         -- the passed path. Let's name the remaining path as
         -- `journey`.
-        journey = path,
+        journey = path, -- XXX: table.copy
     })
     return get_impl(schema, data, ctx)
 end
@@ -1064,7 +1064,7 @@ function methods.set(self, data, path, rhs)
         -- The `path` field is already in the context and it means
         -- the passed path. Let's name the remaining path as
         -- `journey`.
-        journey = path,
+        journey = path, -- XXX: table.copy
     })
     return set_impl(schema, data, rhs, ctx)
 end
```

And cover it with a test.

Jira: TNTP-806.
