### ISSUE TITLE
ER_REPLICASET_UUID_MISMATCH does not disappear

### ISSUE THREAD

**Issue by alvid76** [tarantool/tarantool#10888]
**Bug description**

If, at the first launch, one of the replicas has an incorrect replica set identifier, an ER_REPLICASET_UUID_MISMATCH error occurs, which does not disappear after correcting the identifier and restarting the Tarantool instances.

**Tarantool version**
Tarantool 2.11.5-0-g12a9ceb870
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_BACKTRACE=TRUE
Compiler: GNU-8.3.1
C_FLAGS:-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -fopenmp -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/build/usr/src/debug/tarantool-2.11.5=. -std=c11 -Wall -Wextra -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type -Werror
CXX_FLAGS:-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -fopenmp -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/build/usr/src/debug/tarantool-2.11.5=. -std=c++11 -Wall -Wextra -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror

**Code**
init_t1.lua
```
box.cfg {
    listen = 3301,
    replication = {
      'replicator:password@t1:3301',
      'replicator:password@t2:3301'
    },
    replicaset_uuid = 'aaaa1111-0000-0000-0000-000000000000',
    --replicaset_uuid = 'bbbb1111-0000-0000-0000-000000000000',
    instance_uuid = 'aaaa1111-1111-0000-0000-000000000000',
    read_only = false,
    election_fencing_mode = 'strict',
    election_mode = 'candidate',
    feedback_enabled = false
  }

  box.once(
    "schema",
    function()
      box.schema.user.create('replicator', {password = 'password'})
      box.schema.user.grant('replicator', 'replication') -- grant replication role
      box.schema.space.create("test")
      box.space.test:create_index("primary")
      print('box.once executed on master')
    end
  )
```
init_t2.lua
```
box.cfg {
    listen = 3301,
    replication = {
      'replicator:password@t1:3301',
      'replicator:password@t2:3301'
    },
    replicaset_uuid = 'bbbb1111-0000-0000-0000-000000000000',
    instance_uuid = 'bbbb1111-1111-0000-0000-000000000000',
    read_only = false,
    election_fencing_mode = 'strict',
    election_mode = 'candidate',
    feedback_enabled = false
  }

  box.once(
    "schema",
    function()
      box.schema.user.create('replicator', {password = 'password'})
      box.schema.user.grant('replicator', 'replication') -- grant replication role
      box.schema.space.create("test")
      box.space.test:create_index("primary")
      print('box.once executed on master')
    end
  )
```
docker-compose.yml
```yaml
services:
  t1:
    image: tarantool/tarantool:2.11.5-centos7
    user: 1000:1000
    container_name: t1
    environment:
      - TARANTOOL_WORK_DIR=/var/lib/tarantool
    command:
      - tarantool
      - /init.lua
    volumes:
      - ./init_t1.lua:/init.lua
      - ./t1:/var/lib/tarantool

  t2:
    image: tarantool/tarantool:2.11.5-centos7
    user: 1000:1000
    container_name: t2
    environment:
      - TARANTOOL_WORK_DIR=/var/lib/tarantool
    command:
      - tarantool
      - /init.lua
    volumes:
      - ./init_t2.lua:/init.lua
      - ./t2:/var/lib/tarantool
```

**Steps to reproduce**

1) $ docker compose up
as expected, we get the ER_REPLICASET_UUID_MISMATCH error on instance t2
2) $ docker compose down
3) edit init_t1.lua file and assign the correct replicaset_uuid 'bbbb1111-1111-0000-0000-000000000000' (comment line 7 and uncomment line 8)
4) $ docker compose up
- we get the ER_REPLICASET_UUID_MISMATCH error on instances t1 (and sometimes on t2 too), which should not be there
- $ tarantoolctl cat t2/XXXXXX.snap shows that an incorrect value was written to space _cluster during an unsuccessful attempt to include in the replicaset:
```
---
HEADER:
  lsn: 395
  type: INSERT
  timestamp: 1733233039.2632
BODY:
  space_id: 320
  tuple: [1, 'aaaa1111-1111-0000-0000-000000000000']
---
HEADER:
  lsn: 396
  type: INSERT
  timestamp: 1733233039.2632
BODY:
  space_id: 320
  tuple: [2, 'bbbb1111-1111-0000-0000-000000000000']
---
```
