### ISSUE TITLE
config: implicit overwriting in the cluster config is allowed

### ISSUE THREAD

**Issue by georgiy-belyanin** [tarantool/tarantool#10917]
### Description

Currently, if you configure two instances with the same name in the same replicaset the latter instance implicitly overwrites the definition of the previous one. The same problem holds for replicasets within the same groups and for the groups in general. This may be a problem for large configurations since overwriting is implicit and may not be recognized quickly due to large group configurations.

### Configuration examples

Implicit overwrite of the `i-001` instance:
```yaml
groups:
  g-001:
    replicasets:
      r-001:
        instances:
          i-001: 
            ...
          i-001:
            ...
```

Implicit overwrite of the `r-001` replicaset:
```yaml
groups:
  g-001:
    replicasets:
      r-001:
        ...
      r-001:
        ...
```

Implicit overwrite of the whole group `g-001`:
```yaml
groups:
  g-001:
    ...
  g-001:
    ...
```

### Expected
The preciser message is expected. E.g. such error should be thrown for instances:
```
found instances with the same name `i-001` in the replicaset `r-001` in the group `g-001`.
```

See also #10347 on instances with the same names.
