### ISSUE TITLE
config: on_event callback recieves wrong argument for the config

### ISSUE THREAD

**Issue by grafin** [tarantool/tarantool#10934]
**Bug description**

The `on_event(config, key, value)` callback of a role should receive it's roles config as its first argument. Currently it receives the whole config object instead, which is not the intended behavior.

* OS: Linux
* OS Version: NixOS 24.11 (Vicuna)
* Architecture: amd64

`tarantool -v` output:
```
Tarantool 3.4.0-entrypoint-13-g7731d13d0a
Target: Linux-x86_64-Debug
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/home/boris/dev/github/tarantool/tarantool/build/install -DENABLE_BACKTRACE=TRUE
Compiler: Clang-18.1.8
C_FLAGS:--sysroot=/ -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -fprofile-arcs -ftest-coverage -fsanitize=address -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/boris/dev/github/tarantool/tarantool=. -std=c11 -Wall -Wextra  -fno-omit-frame-pointer -fsanitize=undefined -fno-sanitize=object-size,pointer-overflow,null,nonnull-attribute,function -fno-sanitize-recover=undefined -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror -Werror -g -ggdb -O0
CXX_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -fprofile-arcs -ftest-coverage -fsanitize=address -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/boris/dev/github/tarantool/tarantool=. -std=c++11 -Wall -Wextra  -fno-omit-frame-pointer -fsanitize=undefined -fno-sanitize=object-size,pointer-overflow,null,nonnull-attribute,function -fno-sanitize-recover=undefined -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror -Werror -g -ggdb -O0
```

**Steps to reproduce**

Using the following role `one.lua`:
```lua
_G.foo = nil

return {
    validate = function() end,
    apply = function() end,
    stop = function() end,
    on_event = function(config, _, _)
        _G.foo = config
    end,
}
```

With the config `config.yaml`:
```yaml
---
credentials:
  users:
    guest:
      roles:
      - super
groups:
  group-001:
    replicasets:
      replicaset-001:
        instances:
          instance-001: []
roles_cfg:
  one: 12345
iproto:
  listen:
  - uri: unix/:./{{ instance_name }}.iproto
roles:
- one
...
```

How to run:
`tarantool --name instance-001 --config config.yaml -i`

**Actual behavior**
```
tarantool> print(_G.foo)
table: 0x41bd6308
```

**Expected behavior**
`_G.foo` should contain the config for the role 'one'

```
tarantool> print(_G.foo)
12345
```

Jira: TNTP-941
