### ISSUE TITLE
Memory information

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1093]
"Why Tarantool uses so much memory?" is the one of most popular question by our customers.
Really, why? How to understand which subsystem is heavily utilizes memory on the production installation?

Currently Tarantool 1.6 totally lacks **useful** memory information utils.
We even dropped old "show palloc", which was last useful tool for investigating memory problems.

Let's take a look on current tools.

### box.runtime.info()

```
- maxalloc: 4398046510080
  used: 12582912
...
```

* `maxalloc` - a constant distance to a some remote galaxy.
* `used` - indicates how many memory used by some internal subsystems but nobody knowns by which one.

I don't think that our users want to `grep` our sources to understand that `runtime` means a special **runtime** `arena` for non-data allocations. Moreover, 99.99999% of our current and potential customers don't know WTF is [arena](https://www.google.com/search?q=arena&num=20&safe=off&source=lnms&tbm=isch&sa=X&biw=1278&bih=932). I think that our users should not care about details of Tarantool internal structure..

###  box.slab.info()        

```                                                                                                                          
---
- quota_used: 8388608
  arena_used_ratio: 0.8%
  items_used_ratio: 1.9%
  arena_size: 2325384
  quota_size: 1073741824
  arena_used: 1102088
```

Ohh, arena again. Anyway, let's take a look on `arena_size`, `arena_used` and `arena_used_ratio`:

* `arena_size` is 2325384
* `arena_used` is 1102088
*  `arena_used_ratio` is 0.8%

Arena is [utilized](http://hdwallpaperhub.net/wallpapers/l/1280x1024/26/fight_men_people_arena_bull_football_afl_1280x1024_25743.jpg) by `1102088 / 2325384 = ~ 47%`. But why `arena_used_ratio` is **0.8%** and not **47%**?
Let's move on to `items`. WTF is items? Tuples? Spaces? Whatever?
Next. What is `items_used_ratio`?

`quota_size` and `quota_used` is mostly OK. I'm just curious, how to change `quota_size`?
I found nothing about quota on http://tarantool.org/doc/singlehtml.html

`slabs` is mostly OK, except my note about `items` above.

### box.fiber.info()

```
---
- 101:
    memory:
      total: 65760
      used: 0
    fid: 101
    name: interactive
    csw: 6
```

Mostly OK. How to understand who used this memory?

### space.space.index[x]:bsize()

```
tarantool> box.space._space.index[0]:bsize()
---
- 49152
...
```

OK. I think that users are also interested in total memory usage by space (e.g. space:bsize()).

### What should be done

* Add a new box.memory.info():

```
- tx: -- per each cord
    - indexes: xxx
    - tuples: xxx
    - fibers:  xxx-- including fiber stack and fiber->gc
    - sessions: xx
    - lua: xx
    - malloc: xxx
    - total:
       - allocated: xxx
       - used: xxx
       - fragmentation: xx%

# assert(sum(categories) == used)

- iproto:
    - input_buffers: xxx
    - output_buffers: xxx
    - connections: xxx
    - cbus: xxxx
    - fibers:  xxx-- including fiber stack and fiber->gc
    - malloc: xxx 
    - total:
       - allocated: xxx
       - used: xxx
       - fragmentation: xx%
    

- wal:
    - fibers:  xxx-- including fiber stack and fiber->gc
    - total:
       - allocated: xxx
       - used: xxx
       - fragmentation: xx%

- sophia_merger:
    - malloc: xxx
    - total:
       - allocated: xxx
       - used: xxx
       - fragmentation: xx%

- total:
     - allocated: xxx
     - used: xxx
     - fragmentation: xxx

# assert(used == RSS in top(1))
# assert(allocated == VIRT in top(1))
```

Take a look on malloc_stats(3) for inspiration:

```
tarantool> ffi.C.malloc_stats()
Arena 0:
system bytes     =     860160
in use bytes     =     714704
Arena 1:
system bytes     =     135168
in use bytes     =     134736
Total (incl. mmap):
system bytes     =     995328
in use bytes     =     849440
max mmap regions =          1
max mmap bytes   =     163840
```

* Fix incorrect (mostly random) numbers in box.slab.info()
* Remove `box.runtime.info()` as totally confusing and uninformative tool.
* Add space:bsize()

I understand that this ticket is very hard.
Please implement basic structure of box.memory.info() and then add sections step by step.
Section names provided as for example.
