### ISSUE TITLE
Allow to specify min supported Tarantool version in application role code

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#10987]
If an application role uses a new Tarantool feature, it's best not to load it on older Tarantool versions because it may result in confusing failures at runtime. Indeed, a role may check the Tarantool version in the `validate()` callback, like this:

```lua
local tarantool = require('tarantool')
local version = require('version')

return {
    validate = function()
        if version.fromstr(tarantool.version) < version.new(3, 4, 1) then
            error('Cannot run on Tarantool < 3.4.1')
        end
    end,
    apply = function() end,
    stop = function() end,
}
```

However, it's not really convenient. Also, it generates a confusing error message:

```
2024-12-25 14:43:39.817 [87390] main utils.c:700 E> LuajitError: Wrong config for role my_role: /tmp/test/my_role.lua:7: Cannot run on Tarantool < 3.4.1
```

It'd be nice if it a role could specify the minimal supported Tarantool version.

Jira: TNTP-1016

**Comment by grafin** [comment]
@locker What is the desired behavior if the tarantool version is not supported by the role:

- An error is raised and the tarantool doesn't start at all.
- An error is logged and tarantool continues running without loading the role.

**Comment by grafin** [comment]
The idea is to add `skip_if` or `fail_if` tag to metadata with syntax similar to https://github.com/tarantool/tarantool/pull/9461:
```yaml
--- #tarantool.metadata.v1
early_load: true
skip_if: "tarantool_version < 3.0 && tarantool_version == 3.1"
...
```
or
```yaml
--- #tarantool.metadata.v1
early_load: true
fail_if: "tarantool_version < 3.0 && tarantool_version == 3.1"
...
```

The difference between `skip_if` and `fail_if` is that the first one will skip loading the role if the condition is false, and the later will fail, simmilar to failing the `validate` callback. After discussing with @Totktonada and asking here, we decided to stick to the `fail_if: "tarantool_version < 3.0 && tarantool_version == 3.1"` tag.
