### ISSUE TITLE
Custom template variables in config

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#11002]
It's possible to refer to variables in config values as `{{ var_name }}`. It can come in really handy when one wants to run a bunch of similar instances that differ from each other by just one option, for example:

```yaml
groups:
  my-group:
    iproto:
      listen:
      - uri: 'unix/:./{{ instance_name }}.sock'
    replicasets:
      my-replicaset-001:
        instances:
          my-instance-001:
          my-instance-002:
          # ...
```

Currently, there are three predefined variables: `group_name`, `replicaset_name`, `instance_name`. Besides, the user may define a custom variable in the global section `config.context` using an environment variable or a file as a source. However, this doesn't really help in the use case described above. For example, one can't define a template for instances that differ by the TCP/IP port. It'd be nice if it was possible to define custom variables at any level:

```yaml
groups:
  my-group:
    iproto:
      listen:
      - uri: '0.0.0.0:{{ port }}'
    replicasets:
      my-replicaset-001:
        instances:
          my-instance-001:
            port: 3301
          my-instance-002:
            port: 3302
          # ...
```

**Comment by Godrik0** [comment]
Hi! I'd like to propose the following approach.

Variables are explicitly declared in `config.context` with a `from` field specifying the source. The values live in a dedicated `extras` section under each instance/group/replicaset. 

```yaml
config:
  context:
    port:
      from: extras

groups:
  my-group:
    iproto:
      listen:
      - uri: '0.0.0.0:{{ context.port }}'
    replicasets:
      my-replicaset-001:
        instances:
          my-instance-001:
            extras:
              port: 3301
          my-instance-002:
            extras:
              port: 3302
```

If variables were pulled directly from regular config fields, a user-declared variable name could collide with a built-in config section added in a future Tarantool version (e.g., a user defines `log` as a variable, then Tarantool 3.10 introduces a native `log` section — conflict). The `extras` namespace avoids this entirely: user variables and built-in config are completely separate, so upgrades are always safe.

**Pros**
* Simple JSON schema — `extras` is just a `map[string: any]` field.
* Safe upgrades — new built-in sections can never conflict with user variables.
* Explicit source — `from: extras` can be switched to `from: env` later, giving a clear migration path. No ambiguity about where a value comes from.

**Cons**
* More verbose — users have to write more
* Less ad-hoc flexibility for multi-group clusters — if you have 5 groups, each needing different custom options (A/B/C for group 1, D/E/F for group 2, etc.), all of them must be declared centrally in `config.context`, which can become an unstructured pile of unrelated options. Without the explicit declaration, each group's `extras` would naturally contain only what's relevant to that group.

Let me know what you think about it!
