### ISSUE TITLE
Missing system space replication rows

### ISSUE THREAD

**Issue by DifferentialOrange** [tarantool/tarantool#11028]
**Bug description**

While starting the test cluster with my own custom helpers, sometimes I fail on "server is ready" luatest check since shard replica misses some crucial rows on bootstrap (while master displays no errors).

```
cluster_ab-storage-2-2 | 2025-01-15 17:31:11.746 [44611] main/115/applier/peer@localhost:13314 applier.cc:1075 I> initial data received
cluster_ab-storage-2-2 | 2025-01-15 17:31:11.747 [44611] main/105/interactive box.cc:5987 F> can't initialize storage: Can't modify space '_bucket': can not add a secondary key before primary
cluster_ab-storage-2-2 | 2025-01-15 17:31:11.747 [44611] main/115/applier/peer@localhost:13314 applier.cc:314 E> error applying row: {type: 'INSERT', replica_id: 1, lsn: 43, space_id: 288, index_id: 0, tuple: [512, 1, "status", "tree", {"unique": false}, [[1, "string"]]]}
cluster_ab-storage-2-2 | 2025-01-15 17:31:11.747 [44611] main/115/applier/peer@localhost:13314 applier.cc:112 I> can't read row
cluster_ab-storage-2-2 | 2025-01-15 17:31:11.747 [44611] main/115/applier/peer@localhost:13314 alter.cc:2580 E> ER_ALTER_SPACE: Can't modify space '_bucket': can not add a secondary key before primary
cluster_ab-storage-2-2 | 2025-01-15 17:31:11.747 [44611] main/105/interactive alter.cc:2580 E> ER_ALTER_SPACE: Can't modify space '_bucket': can not add a secondary key before primary
cluster_ab-storage-2-2 | 2025-01-15 17:31:11.747 [44611] main/105/interactive box.cc:5987 F> can't initialize storage: Can't modify space '_bucket': can not add a secondary key before primary
```

* OS: Linux
* OS Version: Ubuntu 22.04
* Architecture: amd64

Tarantool Enterprise 3.3.1-0-g9cdba1a40 Linux-x86_64-RelWithDebInfo

**Steps to reproduce**

Sorry for not reducing the reproducer.

Configuration: two vshard routers, two vshard storage shard, each one has a master and a single replica.

Cluster uses etcd centralized configuration storage.

<details>
<summary>config.yaml</summary>

```yaml
fiber:
  slice:
    warn: 2
    err: 3
credentials:
  users:
    peer:
      password: peering
      roles:
      - replication
      privileges:
      - permissions:
        - execute
        lua_call:
        - box.info
    admin:
      password: cluster_ab_cookie
      roles:
      - super
    replicator:
      password: SuPPerSECreT_PAssw0rd
      roles:
      - super
    storage:
      password: storing-buckets
      roles:
      - sharding
    guest:
      roles:
      - super
    dml_user_1:
      password: dml_user_1_password
      roles:
      - super
groups:
  routers:
    sharding:
      roles:
      - router
    roles:
    - roles.httpd
    - roles.tcf-worker
    - roles.tcf-coordinator
    replicasets:
      cluster_ab-router-rs-1:
        leader: cluster_ab-router-1
        instances:
          cluster_ab-router-1:
            iproto:
              listen:
              - uri: localhost:13310
            roles_cfg:
              roles.tcf-coordinator: []
              roles.tcf-worker:
                http:
                  server: default
                dml_users:
                - dml_user_1
                replication_password: SuPPerSECreT_PAssw0rd
                initial_status: passive
                replication_user: replicator
                status_ttl: 10
                cluster_1: cluster_ab
                cluster_2: cluster_aa
              roles.httpd:
                default:
                  listen: 8090
      cluster_ab-router-rs-2:
        leader: cluster_ab-router-2
        instances:
          cluster_ab-router-2:
            iproto:
              listen:
              - uri: localhost:13311
            roles_cfg:
              roles.tcf-coordinator: []
              roles.tcf-worker:
                http:
                  server: default
                dml_users:
                - dml_user_1
                replication_password: SuPPerSECreT_PAssw0rd
                initial_status: passive
                replication_user: replicator
                status_ttl: 10
                cluster_1: cluster_ab
                cluster_2: cluster_aa
              roles.httpd:
                default:
                  listen: 8091
  storages:
    sharding:
      roles:
      - storage
    roles:
    - roles.httpd
    - roles.tcf-worker
    replicasets:
      cluster_ab-storage-rs-2:
        leader: cluster_ab-storage-2-1
        instances:
          cluster_ab-storage-2-2:
            iproto:
              listen:
              - uri: localhost:13315
            roles_cfg:
              roles.httpd:
                default:
                  listen: 8095
              roles.tcf-worker:
                http:
                  server: default
                dml_users:
                - dml_user_1
                replication_password: SuPPerSECreT_PAssw0rd
                initial_status: passive
                replication_user: replicator
                status_ttl: 10
                cluster_1: cluster_ab
                cluster_2: cluster_aa
          cluster_ab-storage-2-1:
            iproto:
              listen:
              - uri: localhost:13314
            roles_cfg:
              roles.httpd:
                default:
                  listen: 8094
              roles.tcf-worker:
                http:
                  server: default
                dml_users:
                - dml_user_1
                replication_password: SuPPerSECreT_PAssw0rd
                initial_status: passive
                replication_user: replicator
                status_ttl: 10
                cluster_1: cluster_ab
                cluster_2: cluster_aa
      cluster_ab-storage-rs-1:
        leader: cluster_ab-storage-1-1
        instances:
          cluster_ab-storage-1-1:
            iproto:
              listen:
              - uri: localhost:13312
            roles_cfg:
              roles.httpd:
                default:
                  listen: 8092
              roles.tcf-worker:
                http:
                  server: default
                dml_users:
                - dml_user_1
                replication_password: SuPPerSECreT_PAssw0rd
                initial_status: passive
                replication_user: replicator
                status_ttl: 10
                cluster_1: cluster_ab
                cluster_2: cluster_aa
          cluster_ab-storage-1-2:
            iproto:
              listen:
              - uri: localhost:13313
            roles_cfg:
              roles.httpd:
                default:
                  listen: 8093
              roles.tcf-worker:
                http:
                  server: default
                dml_users:
                - dml_user_1
                replication_password: SuPPerSECreT_PAssw0rd
                initial_status: passive
                replication_user: replicator
                status_ttl: 10
                cluster_1: cluster_ab
                cluster_2: cluster_aa
sharding:
  bucket_count: 3000
log:
  file: '{{ instance_name }}.log'
  to: pipe
  pipe: tee {{ instance_name }}.log
roles_cfg:
  roles.tcf-coordinator:
    max_suspect_counts: 3
    failover_timeout: 20
    health_check_delay: 1
iproto:
  advertise:
    peer:
      login: peer
    sharding:
      login: storage
replication:
  timeout: 0.1
  failover: manual
...
```

</details>

Artifacts (log, snap, xlog):  [test-artifacts-016aca37-58ed-4b65-8a47-f6e7857ac32e.tar.gz](https://github.com/user-attachments/files/18435036/test-artifacts-016aca37-58ed-4b65-8a47-f6e7857ac32e.tar.gz).

I have also seen
```
applier.cc:314 E> error applying row: {type: 'REPLACE', replica_id: 1, lsn: 47, space_id: 312, index_id: 0, tuple: [1, 32, "function", 71, 4, {"origins": {"config": 4}}]}
alter.cc:3930 E> ER_NO_SUCH_FUNCTION: Function '71' does not exist
```
failure, but don't have any artifacts.

It may be misleading, but it seems that we started to get this failure after introducing Tarantool 3.3 to our CI pipeline.

**Actual behavior**

Cluster instance fails to start.

**Expected behavior**

Cluster starts.

**Comment by sergepetrenko** [comment]
Unfortunately I couldn't reproduce the issue locally so far. Here's the test I've put together:

<details><summary>gh_11028_missing_row_replication_test.lua</summary>

```lua
local t = require('luatest')
local server = require('luatest.server')
local replica_set = require('luatest.replica_set')

local g = t.group()

g.before_each(function(cg)
    cg.replica_set = replica_set:new{}
    cg.master = cg.replica_set:build_and_add_server{
        alias = 'master',
        box_cfg = {
            replication_timeout = 0.1,
        },
    }
    cg.replica = cg.replica_set:build_and_add_server{
        alias = 'replica',
        box_cfg = {
            replication = {
                server.build_listen_uri('master', cg.replica_set.id),
            },
            replication_timeout = 0.1,
        }
    }
end)

g.test_row_skipping_during_join = function(cg)
    cg.master:start()
    cg.replica:start({wait_until_ready=false})
    cg.master:exec(function()
        local num_spaces = 500
        local filler_iters = 0
        local fiber = require('fiber')
        local log = require('log')
        local function fill()
            for i = 1, filler_iters do
                box.space._schema:replace{'asd'}
            end
        end
        fiber.new(function()
            for i = 1,num_spaces do
                fill()
                local space = box.schema.space.create('space'..i)
                box.schema.func.create('function'..i)
                log.info('created space %s', space.name)
                fill()
                space:create_index('pk')
                fill()
                space:create_index('sk', {parts = {{2, 'unsigned'}}})
                fill()
                space:create_index('tk', {parts = {{3, 'unsigned'}}})
                log.info('created last index of space %s', space.name)
            end
        end)
        log.info('Fill fiber created')
    end)
    cg.replica:wait_until_ready()
    t.helpers.retrying({}, function()
        cg.replica:assert_follows_upstream(1)
    end)
end

g.after_each(function(cg)
    cg.replica_set:drop()
end)
```

</details>

**Comment by sergepetrenko** [comment]
Ok, I managed to reproduce the issue by running cluster-federation tests like this multiple times (usually 3 or 4 is enough:
```
luatest -v --no-clean --coverage -p 'integration.tcf_multi_tcf.setup_config_storage_with_env:true.storage:"config_storage".test_toggle_independed'
```

A part of `cluster_ba-storage-2-2` (replica) log with an error:
```
2025-01-17 18:58:10.707 [96536] main/117/applier/peer@localhost:23304 applier.cc:315 E> error applying row: {type: 'INSERT',        replica_id: 1, lsn: 43, space_id: 288, index_id: 0, tuple: [512, 1, "status", "tree", {"unique": false}, [[1, "string"]]]}
2025-01-17 18:58:10.707 [96536] main/117/applier/peer@localhost:23304 applier.cc:112 I> can't read row 
2025-01-17 18:58:10.707 [96536] main/117/applier/peer@localhost:23304 alter.cc:2582 E> ER_ALTER_SPACE: Can't modify space           '_bucket': can not add a secondary key before primary
2025-01-17 18:58:10.707 [96536] main/105/interactive alter.cc:2582 E> ER_ALTER_SPACE: Can't modify space '_bucket': can not add a   secondary key before primary
2025-01-17 18:58:10.707 [96536] main/105/interactive box.cc:5987 F> can't initialize storage: Can't modify space '_bucket': can not add a secondary key before primary
```

I've ran the tests on Tarantool Enterprise 3.3.1-0-g9cdba1a with the following patches on CE tarantool for extra logging:
<details><summary>Tarantool patch</summary>

```diff
diff --git a/src/box/applier.cc b/src/box/applier.cc
index 38bf76f0bf..195f3a7a3a 100644
--- a/src/box/applier.cc
+++ b/src/box/applier.cc
@@ -259,6 +259,7 @@ apply_snapshot_row(struct xrow_header *row)
        struct request request;
        if (xrow_decode_dml(row, &request, dml_request_key_map(row->type)) != 0)
                return -1;
+       say_info("Apply snapshot request at %d:%lld,  %s", row->replica_id, row->lsn, request_str(&request));
        struct space *space = space_cache_find(request.space_id);
        if (space == NULL)
                return -1;
@@ -789,6 +790,7 @@ applier_wait_snapshot(struct applier *applier)
                struct vclock vclock;
                xrow_decode_vclock_ignore0_xc(&row, &vclock);
                box_init_instance_vclock(&vclock);
+               say_info("initial join vclock is %s", vclock_to_string(&vclock));
        }
 
        coio_read_xrow(io, ibuf, &row);
@@ -1013,6 +1015,7 @@ applier_wait_register(struct applier *applier, uint64_t row_count)
                                                  next)->row);
                        break;
                }
+               say_info("Receive a tx with replica_id: %d, lsn: %lld", first_row->replica_id, first_row->lsn);
                if (applier_apply_tx(applier, &rows) != 0)
                        diag_raise();
        }
@@ -1580,6 +1583,7 @@ applier_synchro_filter_tx(struct stailq *rows)
        }
        stailq_foreach_entry(item, rows, next) {
                row = &item->row;
+               say_info("NOPIFY %d:%lld", row->replica_id, row->lsn);
                row->type = IPROTO_NOP;
                row->bodycnt = 0;
                memset(&item->req.dml, 0, sizeof(item->req.dml));
@@ -1658,6 +1662,8 @@ applier_apply_tx(struct applier *applier, struct stailq *rows)
        }
        if (vclock_get(&replicaset.applier.vclock,
                       last_row->replica_id) >= last_row->lsn) {
+               say_info("SKIP ROW %d:%lld, replicaset_applier_vclock is %s", last_row->replica_id, last_row->lsn,
+                        vclock_to_string(&replicaset.applier.vclock));
                goto finish;
        } else if (vclock_get(&replicaset.applier.vclock,
                              first_row->replica_id) >= first_row->lsn) {
@@ -1678,6 +1684,8 @@ applier_apply_tx(struct applier *applier, struct stailq *rows)
                                break;
                        }
                }
+               say_info("SKIP PART OF ROWS %d:%lld, replicaset_applier_vclock is %s", first_row->replica_id, first_row->lsn,
+                        vclock_to_string(&replicaset.applier.vclock));
        }
        rc = applier_synchro_filter_tx(rows);
        if (rc != 0)
```

</details>

Below are the `cluster_ba-storage-2-1` (master) xlog contents. As you can see, the rows with space `_bucket` and its indexes creation have lsns `34`, `40`, `43`:

```
HEADER:                                                                          
  lsn: 34                                                                        
  replica_id: 1                                                                  
  type: INSERT                                                                   
  timestamp: 1737129490.5494                                                     
BODY:                                                                            
  space_id: 280                                                                  
  tuple: [512, 1, '_bucket', 'memtx', 0, {}, []]
```

```
HEADER:                                                                          
  lsn: 40                                                                        
  replica_id: 1                                                                  
  type: INSERT                                                                   
  timestamp: 1737129490.5953                                                     
BODY:                                                                            
  space_id: 288                                                                  
  tuple: [512, 0, 'pk', 'tree', {'unique': true}, [[0, 'unsigned']]]
```

```
HEADER:                                                                          
  lsn: 43                                                                        
  replica_id: 1                                                                  
  type: INSERT                                                                   
  timestamp: 1737129490.6221                                                     
BODY:                                                                            
  space_id: 288                                                                  
  tuple: [512, 1, 'status', 'tree', {'unique': false}, [[1, 'string']]]
```

<details><summary>tt cat output</summary>

```
• Result of cat: the file "/tmp/artifacts/cluster_ba-storage-2-1/var/lib/cluster_ba-storage-2-1/00000000000000000000.xlog" is processed below •
---
HEADER:
  lsn: 1
  replica_id: 1
  type: INSERT
  tsn: 1
  timestamp: 1737129490.4729
BODY:
  space_id: 304
  tuple: [32, 1, 'sharding', 'role', {}, [], 1737129490]
---
HEADER:
  lsn: 2
  replica_id: 1
  type: INSERT
  tsn: 1
  timestamp: 1737129490.4729
BODY:
  space_id: 304
  tuple: [33, 1, 'peer', 'user', {}, [], 1737129490]
---
HEADER:
  lsn: 3
  replica_id: 1
  type: REPLACE
  tsn: 1
  timestamp: 1737129490.4729
BODY:
  space_id: 312
  tuple: [1, 33, 'role', 2, 4]
---
HEADER:
  lsn: 4
  replica_id: 1
  type: REPLACE
  tsn: 1
  timestamp: 1737129490.4729
BODY:
  space_id: 312
  tuple: [1, 33, 'user', 33, 128]
---
HEADER:
  lsn: 5
  replica_id: 1
  type: REPLACE
  tsn: 1
  timestamp: 1737129490.4729
BODY:
  space_id: 312
  tuple: [1, 33, 'universe', 0, 24]
---
HEADER:
  lsn: 6
  replica_id: 1
  type: UPDATE
  tsn: 1
  timestamp: 1737129490.4729
BODY:
  space_id: 304
  index_base: 1
  key: [33]
  tuple: [['=', 5, {'chap-sha1': 'EFJsQ7Tcw9h4K79/xMzytiZGX4U='}], ['=', 6, []], [
      '=', 7, 1737129490]]
---
HEADER:
  lsn: 7
  replica_id: 1
  type: INSERT
  tsn: 1
  timestamp: 1737129490.4729
BODY:
  space_id: 304
  tuple: [34, 1, 'storage', 'user', {}, [], 1737129490]
---
HEADER:
  lsn: 8
  replica_id: 1
  type: REPLACE
  tsn: 1
  timestamp: 1737129490.4729
BODY:
  space_id: 312
  tuple: [1, 34, 'role', 2, 4]
---
HEADER:
  lsn: 9
  replica_id: 1
  type: REPLACE
  tsn: 1
  timestamp: 1737129490.4729
BODY:
  space_id: 312
  tuple: [1, 34, 'user', 34, 128]
---
HEADER:
  lsn: 10
  replica_id: 1
  type: REPLACE
  tsn: 1
  timestamp: 1737129490.4729
BODY:
  space_id: 312
  tuple: [1, 34, 'universe', 0, 24]
---
HEADER:
  lsn: 11
  replica_id: 1
  type: UPDATE
  tsn: 1
  timestamp: 1737129490.4729
BODY:
  space_id: 304
  index_base: 1
  key: [34]
  tuple: [['=', 5, {'chap-sha1': 'Oblj+vheJshyHYy6JoxIKQaBplM='}], ['=', 6, []], [
      '=', 7, 1737129490]]
---
HEADER:
  lsn: 12
  replica_id: 1
  type: INSERT
  tsn: 1
  timestamp: 1737129490.4729
BODY:
  space_id: 304
  tuple: [35, 1, 'replicator', 'user', {}, [], 1737129490]
---
HEADER:
  lsn: 13
  replica_id: 1
  type: REPLACE
  tsn: 1
  timestamp: 1737129490.4729
BODY:
  space_id: 312
  tuple: [1, 35, 'role', 2, 4]
---
HEADER:
  lsn: 14
  replica_id: 1
  type: REPLACE
  tsn: 1
  timestamp: 1737129490.4729
BODY:
  space_id: 312
  tuple: [1, 35, 'user', 35, 128]
---
HEADER:
  lsn: 15
  replica_id: 1
  type: REPLACE
  tsn: 1
  timestamp: 1737129490.4729
BODY:
  space_id: 312
  tuple: [1, 35, 'universe', 0, 24]
---
HEADER:
  lsn: 16
  replica_id: 1
  type: UPDATE
  tsn: 1
  timestamp: 1737129490.4729
BODY:
  space_id: 304
  index_base: 1
  key: [35]
  tuple: [['=', 5, {'chap-sha1': 'mmYeTaiG7wRK6Z8JjC79wpMd/5U='}], ['=', 6, []], [
      '=', 7, 1737129490]]
---
HEADER:
  lsn: 17
  replica_id: 1
  type: UPDATE
  tsn: 1
  timestamp: 1737129490.4729
BODY:
  space_id: 304
  index_base: 1
  key: [1]
  tuple: [['=', 5, {'chap-sha1': 'QY3apGHjXWm32iTHyVBwThd8E5c='}], ['=', 6, []], [
      '=', 7, 1737129490]]
---
HEADER:
  lsn: 18
  replica_id: 1
  type: INSERT
  tsn: 1
  timestamp: 1737129490.4729
BODY:
  space_id: 304
  tuple: [36, 1, 'dml_user_1', 'user', {}, [], 1737129490]
---
HEADER:
  lsn: 19
  replica_id: 1
  type: REPLACE
  tsn: 1
  timestamp: 1737129490.4729
BODY:
  space_id: 312
  tuple: [1, 36, 'role', 2, 4]
---
HEADER:
  lsn: 20
  replica_id: 1
  type: REPLACE
  tsn: 1
  timestamp: 1737129490.4729
BODY:
  space_id: 312
  tuple: [1, 36, 'user', 36, 128]
---
HEADER:
  lsn: 21
  replica_id: 1
  type: REPLACE
  tsn: 1
  timestamp: 1737129490.4729
BODY:
  space_id: 312
  tuple: [1, 36, 'universe', 0, 24]
---
HEADER:
  lsn: 22
  replica_id: 1
  type: UPDATE
  tsn: 1
  timestamp: 1737129490.4729
BODY:
  space_id: 304
  index_base: 1
  key: [36]
  tuple: [['=', 5, {'chap-sha1': 'zWr9JbDKvojumzsDMX4HxkwmNdE='}], ['=', 6, []], [
      '=', 7, 1737129490]]
---
HEADER:
  lsn: 23
  replica_id: 1
  type: REPLACE
  tsn: 1
  timestamp: 1737129490.4729
BODY:
  space_id: 312
  tuple: [1, 33, 'lua_call', 'box.info', 4, {'origins': {'config': 4}}]
---
HEADER:
  lsn: 24
  replica_id: 1
  type: REPLACE
  tsn: 1
  timestamp: 1737129490.4729
BODY:
  space_id: 312
  tuple: [1, 33, 'role', 3, 4, {'origins': {'config': 4}}]
---
HEADER:
  lsn: 25
  replica_id: 1
  type: REPLACE
  tsn: 1
  timestamp: 1737129490.4729
BODY:
  space_id: 312
  tuple: [1, 34, 'role', 32, 4, {'origins': {'config': 4}}]
---
HEADER:
  lsn: 26
  replica_id: 1
  type: REPLACE
  tsn: 1
  timestamp: 1737129490.4729
BODY:
  space_id: 312
  tuple: [1, 35, 'role', 31, 4, {'origins': {'config': 4}}]
---
HEADER:
  lsn: 27
  replica_id: 1
  type: REPLACE
  tsn: 1
  timestamp: 1737129490.4729
BODY:
  space_id: 312
  tuple: [1, 1, 'role', 31, 4, {'origins': {'config': 4}}]
---
HEADER:
  lsn: 28
  replica_id: 1
  type: REPLACE
  tsn: 1
  timestamp: 1737129490.4729
BODY:
  space_id: 312
  tuple: [1, 0, 'role', 31, 4, {'origins': {'config': 4}}]
---
HEADER:
  lsn: 29
  replica_id: 1
  type: REPLACE
  tsn: 1
  timestamp: 1737129490.4729
BODY:
  space_id: 312
  tuple: [1, 36, 'role', 31, 4, {'origins': {'config': 4}}]
---
HEADER:
  lsn: 30
  commit: true
  replica_id: 1
  type: REPLACE
  tsn: 1
  timestamp: 1737129490.4729
BODY:
  space_id: 312
  tuple: [1, 32, 'role', 3, 4, {'origins': {'config': 4}}]
---
HEADER:
  lsn: 31
  replica_id: 1
  type: INSERT
  timestamp: 1737129490.5258
BODY:
  space_id: 296
  tuple: [66, 1, 'vshard.storage.bucket_stat', 1, 'LUA', '', 'function', [], 'any',
    'none', 'none', false, false, true, ['LUA'], {}, '', '2025-01-17 18:58:10', '2025-01-17
      18:58:10', []]
---
HEADER:
  lsn: 32
  replica_id: 1
  type: REPLACE
  timestamp: 1737129490.5488
BODY:
  space_id: 312
  tuple: [1, 32, 'function', 66, 4, {'origins': {'config': 4}}]
---
HEADER:
  lsn: 33
  replica_id: 1
  type: INSERT
  timestamp: 1737129490.5488
BODY:
  space_id: 296
  tuple: [67, 1, 'vshard.storage.bucket_force_create', 1, 'LUA', '', 'function', [],
    'any', 'none', 'none', false, false, true, ['LUA'], {}, '', '2025-01-17 18:58:10',
    '2025-01-17 18:58:10', []]
---
HEADER:
  lsn: 34
  replica_id: 1
  type: INSERT
  timestamp: 1737129490.5494
BODY:
  space_id: 280
  tuple: [512, 1, '_bucket', 'memtx', 0, {}, []]
---
HEADER:
  lsn: 35
  replica_id: 1
  type: REPLACE
  timestamp: 1737129490.5716
BODY:
  space_id: 312
  tuple: [1, 32, 'function', 67, 4, {'origins': {'config': 4}}]
---
HEADER:
  lsn: 36
  replica_id: 1
  type: INSERT
  timestamp: 1737129490.5716
BODY:
  space_id: 296
  tuple: [68, 1, 'vshard.storage._call', 1, 'LUA', '', 'function', [], 'any', 'none',
    'none', false, false, true, ['LUA'], {}, '', '2025-01-17 18:58:10', '2025-01-17
      18:58:10', []]
---
HEADER:
  lsn: 1
  group_id: 1
  type: REPLACE
  timestamp: 1737129490.5716
BODY:
  space_id: 388
  tuple: ['b0128b68-398c-48bc-b815-41dffeb72b03', {1: 33}, {'type': 'replica'}]
---
HEADER:
  lsn: 37
  replica_id: 1
  type: UPDATE
  timestamp: 1737129490.5719
BODY:
  space_id: 280
  index_base: 1
  key: [512]
  tuple: [['=', 7, [{'name': 'id', 'type': 'unsigned'}, {'name': 'status', 'type': 'string'},
        {'type': 'string', 'name': 'destination', 'is_nullable': true}]]]
---
HEADER:
  lsn: 38
  replica_id: 1
  type: REPLACE
  timestamp: 1737129490.5953
BODY:
  space_id: 312
  tuple: [1, 32, 'function', 68, 4, {'origins': {'config': 4}}]
---
HEADER:
  lsn: 39
  replica_id: 1
  type: INSERT
  timestamp: 1737129490.5953
BODY:
  space_id: 296
  tuple: [69, 1, 'vshard.storage.bucket_send', 1, 'LUA', '', 'function', [], 'any',
    'none', 'none', false, false, true, ['LUA'], {}, '', '2025-01-17 18:58:10', '2025-01-17
      18:58:10', []]
---
HEADER:
  lsn: 40
  replica_id: 1
  type: INSERT
  timestamp: 1737129490.5953
BODY:
  space_id: 288
  tuple: [512, 0, 'pk', 'tree', {'unique': true}, [[0, 'unsigned']]]
---
HEADER:
  lsn: 41
  replica_id: 1
  type: REPLACE
  timestamp: 1737129490.6221
BODY:
  space_id: 312
  tuple: [1, 32, 'function', 69, 4, {'origins': {'config': 4}}]
---
HEADER:
  lsn: 42
  replica_id: 1
  type: INSERT
  timestamp: 1737129490.6221
BODY:
  space_id: 296
  tuple: [70, 1, 'vshard.storage.rebalancer_request_state', 1, 'LUA', '', 'function',
    [], 'any', 'none', 'none', false, false, true, ['LUA'], {}, '', '2025-01-17 18:58:10',
    '2025-01-17 18:58:10', []]
---
HEADER:
  lsn: 43
  replica_id: 1
  type: INSERT
  timestamp: 1737129490.6221
BODY:
  space_id: 288
  tuple: [512, 1, 'status', 'tree', {'unique': false}, [[1, 'string']]]
---
HEADER:
  lsn: 44
  replica_id: 1
  type: REPLACE
  timestamp: 1737129490.647
BODY:
  space_id: 312
  tuple: [1, 32, 'function', 70, 4, {'origins': {'config': 4}}]
---
HEADER:
  lsn: 45
  replica_id: 1
  type: INSERT
  timestamp: 1737129490.647
BODY:
  space_id: 296
  tuple: [71, 1, 'vshard.storage.bucket_collect', 1, 'LUA', '', 'function', [], 'any',
    'none', 'none', false, false, true, ['LUA'], {}, '', '2025-01-17 18:58:10', '2025-01-17
      18:58:10', []]
---
HEADER:
  lsn: 46
  replica_id: 1
  type: REPLACE
  timestamp: 1737129490.647
BODY:
  space_id: 272
  tuple: ['vshard_version', 0, 1, 15, 0]
---
HEADER:
  lsn: 47
  replica_id: 1
  type: REPLACE
  timestamp: 1737129490.6747
BODY:
  space_id: 312
  tuple: [1, 32, 'function', 71, 4, {'origins': {'config': 4}}]
---
HEADER:
  lsn: 48
  replica_id: 1
  type: INSERT
  timestamp: 1737129490.6747
BODY:
  space_id: 296
  tuple: [72, 1, 'vshard.storage.sync', 1, 'LUA', '', 'function', [], 'any', 'none',
    'none', false, false, true, ['LUA'], {}, '', '2025-01-17 18:58:10', '2025-01-17
      18:58:10', []]
---
HEADER:
  lsn: 49
  replica_id: 1
  type: REPLACE
  timestamp: 1737129490.6747
BODY:
  space_id: 272
  tuple: ['vshard_version', 0, 1, 16, 0]
---
HEADER:
  lsn: 50
  replica_id: 1
  type: INSERT
  timestamp: 1737129490.6749
BODY:
  space_id: 320
  tuple: [2, 'b0128b68-398c-48bc-b815-41dffeb72b03', 'cluster_ba-storage-2-2']
---
HEADER:
  lsn: 51
  replica_id: 1
  type: REPLACE
  timestamp: 1737129490.7056
BODY:
  space_id: 312
  tuple: [1, 32, 'function', 72, 4, {'origins': {'config': 4}}]
---
HEADER:
  lsn: 52
  replica_id: 1
  type: INSERT
  timestamp: 1737129490.7056
BODY:
  space_id: 296
  tuple: [73, 1, 'vshard.storage.bucket_force_drop', 1, 'LUA', '', 'function', [],
    'any', 'none', 'none', false, false, true, ['LUA'], {}, '', '2025-01-17 18:58:10',
    '2025-01-17 18:58:10', []]
---
HEADER:
  lsn: 53
  replica_id: 1
  type: DELETE
  timestamp: 1737129490.7056
BODY:
  space_id: 272
  key: ['oncevshard:storage:1']
---
HEADER:
  lsn: 54
  replica_id: 1
  type: REPLACE
  timestamp: 1737129490.7307
BODY:
  space_id: 312
  tuple: [1, 32, 'function', 73, 4, {'origins': {'config': 4}}]
---
HEADER:
  lsn: 55
  replica_id: 1
  type: INSERT
  timestamp: 1737129490.7307
BODY:
  space_id: 296
  tuple: [74, 1, 'vshard.storage.buckets_info', 1, 'LUA', '', 'function', [], 'any',
    'none', 'none', false, false, true, ['LUA'], {}, '', '2025-01-17 18:58:10', '2025-01-17
      18:58:10', []]
---
HEADER:
  lsn: 56
  replica_id: 1
  type: REPLACE
  timestamp: 1737129490.7307
BODY:
  space_id: 272
  tuple: ['vshard_version', 0, 1, 16, 0]
---
HEADER:
  lsn: 2
  group_id: 1
  type: UPDATE
  timestamp: 1737129490.7309
BODY:
  space_id: 388
  key: ['b0128b68-398c-48bc-b815-41dffeb72b03']
  tuple: [['=', 1, {1: 53}]]
---
HEADER:
  lsn: 57
  replica_id: 1
  type: REPLACE
  timestamp: 1737129490.757
BODY:
  space_id: 312
  tuple: [1, 32, 'function', 74, 4, {'origins': {'config': 4}}]
---
HEADER:
  lsn: 58
  replica_id: 1
  type: INSERT
  timestamp: 1737129490.757
BODY:
  space_id: 296
  tuple: [75, 1, 'vshard.storage.rebalancer_apply_routes', 1, 'LUA', '', 'function',
    [], 'any', 'none', 'none', false, false, true, ['LUA'], {}, '', '2025-01-17 18:58:10',
    '2025-01-17 18:58:10', []]
---
HEADER:
  lsn: 59
  replica_id: 1
  type: REPLACE
  timestamp: 1737129490.7842
BODY:
  space_id: 312
  tuple: [1, 32, 'function', 75, 4, {'origins': {'config': 4}}]
---
HEADER:
  lsn: 60
  replica_id: 1
  type: INSERT
  timestamp: 1737129490.7842
BODY:
  space_id: 296
  tuple: [76, 1, 'vshard.storage.call', 1, 'LUA', '', 'function', [], 'any', 'none',
    'none', false, false, true, ['LUA'], {}, '', '2025-01-17 18:58:10', '2025-01-17
      18:58:10', []]
...
    
```

</details>
