### ISSUE TITLE
Replica bootstrap / rebootstrap fails if role writes to sync space

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#11039]
**Bug description**

Application role that writes to a synchronous space at startup fails to bootstrap in the election failover mode.

Tarantool version:

```
Tarantool 3.4.0-entrypoint-75-g714052225ebd
Target: Linux-x86_64-Debug
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/home/vlad/src/tarantool/tarantool/build/debug/install -DENABLE_BACKTRACE=TRUE
Compiler: GNU-13.2.0
C_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/vlad/src/tarantool/tarantool=. -std=c11 -Wall -Wextra -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type -Werror -g -ggdb -O0
CXX_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/vlad/src/tarantool/tarantool=. -std=c++11 -Wall -Wextra -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror -g -ggdb -O0
```

**Steps to reproduce**

1. Download [test.zip](https://github.com/user-attachments/files/18490883/test.zip). It contains the configuration and code of the failing application role. See the appendix for more details.

2. Unzip the downloaded archive and enter the application directory.
   ```sh
   unzip test.zip && cd test
   ```

3. Run the application.
   ```sh
   tt stop -y && tt clean -f && tt start
   ```

4. Wait for a few seconds and check the status.
   ```sh
   tt status
   ```

**Actual behavior**

One instance fails to start:

```
$ tt status
 INSTANCE          STATUS       PID     MODE  CONFIG  BOX      UPSTREAM
 test:instance001  NOT RUNNING
 test:instance002  RUNNING      522949  RO    ready   running  disconnected
 test:instance003  RUNNING      522947  RW    ready   running  disconnected

The status of some instances requires attention.
Please rerun the command with the --details flag to see more information
```

The instance log contains `ER_SYNC_QUORUM_TIMEOUT` error:

```
$ tt log test:instance001
test:instance001: 2025-01-21 15:38:42.096 [522990] main/116/applier/replicator@127.0.0.1:3303 replication.cc:563 I> assigned id 2 to replica 3d876a78-21bd-40ba-abc4-fffe25c11d01
test:instance001: 2025-01-21 15:38:42.096 [522990] main/116/applier/replicator@127.0.0.1:3303 replication.cc:581 I> assigned name instance001 to replica 3d876a78-21bd-40ba-abc4-fffe25c11d01
test:instance001: 2025-01-21 15:38:42.096 [522990] main/116/applier/replicator@127.0.0.1:3303 box.cc:2274 I> update replication_synchro_quorum = 2
test:instance001: 2025-01-21 15:38:42.096 [522990] main/116/applier/replicator@127.0.0.1:3303 raft.c:637 I> RAFT: fencing paused
test:instance001: 2025-01-21 15:38:42.096 [522990] main/116/applier/replicator@127.0.0.1:3303 applier.cc:1088 I> final data received
test:instance001: 2025-01-21 15:38:47.098 [522990] main/104/interactive box.cc:5407 E> failed to create a checkpoint
test:instance001: 2025-01-21 15:38:47.098 [522990] main/104/interactive txn_limbo.c:980 E> ER_SYNC_QUORUM_TIMEOUT: Quorum collection for a synchronous transaction is timed out
test:instance001: 2025-01-21 15:38:47.098 [522990] main/104/interactive box.cc:5987 F> can't initialize storage: Quorum collection for a synchronous transaction is timed out
test:instance001: Watchdog 2025/01/21 15:38:47 (WARN): "exit status 1".
test:instance001: Watchdog 2025/01/21 15:38:47 (INFO): the Instance has shutdown.
```

Note that the issue isn't 100% reproducible. If all instances start successfully, try doing step 3 again.

**Expected behavior**

All instances start successfully.

**Appendix**

The test application simulates the use case when the role wants to initialize some spaces right after the startup. To do that, it installs a `box.status` watcher, which creates a synchronous space and writes to it once the instance becomes writable. The loop between space creation and write is required to increase the probability of failure: it waits for a new instance to register in the cluster.

<details><summary>Application role code (test.lua)</summary>

```lua
local fiber = require('fiber')

local function test_apply()
    box.watch('box.status', function(_, value)
        if not value.is_ro then
            box.schema.space.create('test', {
                is_sync = true,
                if_not_exists = true,
            })
            box.space.test:create_index('primary', {
                if_not_exists = true,
            })
            while box.space._cluster:count() == 1 do
                fiber.yield()
            end
            box.space.test:replace({1})
        end
    end)
end

return {
    validate = function() end,
    apply = test_apply,
    stop = function() end,
}
```

</details>

<details><summary>Application config (config.yaml)</summary>

```yaml
credentials:
  users:
    replicator:
      password: 'topsecret'
      roles: [replication]
iproto:
  advertise:
    peer:
      login: replicator
replication:
  failover: election
roles:
- test
groups:
  group001:
    replicasets:
      replicaset001:
        instances:
          instance001:
            iproto:
              listen:
              - uri: '127.0.0.1:3301'
          instance002:
            iproto:
              listen:
              - uri: '127.0.0.1:3302'
          instance003:
            iproto:
              listen:
              - uri: '127.0.0.1:3303'
```

</details>
