### ISSUE TITLE
config: non-detailed ER_BOOTSTRAP_READONLY message

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#11116]
## Context

A replicaset can't start if all the instances are read-only and neither of them has previously written data (a snapshot). In particular, if the replicaset contains just one instance and there is no snapshot, this instance can't start if the read-only mode is enforced.

This is the expected behavior.

## Problem

However, it is a problem, if we report this situation to the user in an unclear way.

If a cluster configuration is incorrect, we should report the problem in terms of the cluster configuration.

The particular scenario we meet with @ochaton today (on tarantool 3.2.1) is the following:

* a replicaset with one instance
* no snapshot
* `replication.failover: manual`
* no `leader` option set for the replicaset

Currently, this problem is reported as follows:

> E> ER_BOOTSTRAP_READONLY: Trying to bootstrap a local read-only instance as master

However, it is non-trivial to match this message with the forgotten `leader` option needed in the `replication.failover` mode.

## Reproduce

`config.yaml`:

```yaml
credentials:
  users:
    replicator:
      password: secret
      roles: [replication]

iproto:
  listen:
  - uri: 'unix/:./var/run/{{ instance_name }}/tarantool.iproto'
  advertise:
    peer:
      login: 'replicator'

replication:
  failover: manual

groups:
  g-001:
    replicasets:
      r-001:
        # !! no leader option !!
        instances:
          i-001: {}
```

Run:

```sh
$ tarantool -n i-001 -c config.yaml
```

Output:

> <...>
> 2025-02-07 21:07:53.396 [9539] main/105/interactive box.cc:5279 E> ER_BOOTSTRAP_READONLY: Trying to bootstrap a local read-only instance as master
> 2025-02-07 21:07:53.396 [9539] main/105/interactive box.cc:5987 F> can't initialize storage: Trying to bootstrap a local read-only instance as master
> <..exit with non-zero exit code..>

## Analyze

There is code that catch similar situations, but it works only for a replicaset with two or more instances.

https://github.com/tarantool/tarantool/blob/e0c6126742e1ba9016f8dcb5b749210f6020e9a7/src/box/lua/config/applier/box_cfg.lua#L943-L954

Jira: TNTP-1548
