### ISSUE TITLE
Can't override metrics in case of workdir change

### ISSUE THREAD

**Issue by DifferentialOrange** [tarantool/tarantool#11427]
**Bug description**

In case instance uses a `work_dir` with rocks contents, Tarantool uses built-in `metrics` package instead of overrided until manually reloaded.

* OS: Linux
* OS Version: Ubuntu 22.04
* Architecture: amd64

Tarantool Enterprise 3.3.1-0-g9cdba1a40

**Steps to reproduce**

```bash
mkdir workdir
cd ./workdir
tt rocks install metrics
cd ..
```

**config.yaml**
```yaml
credentials:
  users:
    guest:
      roles: [super]

groups:
  group001:
    replicasets:
      replicaset001:
        instances:
          instance001:
            iproto:
              listen:
              - uri: '127.0.0.1:3301'

process:
  work_dir: './workdir'
```

(Same thing in case work_dir path is absolute.)

```bash
tarantool --config ./config.yaml --name instance001
```

```bash
tt connect localhost:3301
```

**Actual behavior**

```
localhost:3301> debug.getinfo(require('metrics').counter).source
---
- '@builtin/third_party/metrics/metrics/api.lua'
...

localhost:3301> for k, _ in pairs(package.loaded) do if k:startswith('metrics') then package.loaded[k] = nil end end; require('metrics')
---
...

localhost:3301> debug.getinfo(require('metrics').counter).source
---
- '@/tmp/override-repro/workdir/.rocks/share/tarantool/override/metrics/api.lua'
...
```

**Expected behavior**

```
localhost:3301> debug.getinfo(require('metrics').counter).source
---
- '@/tmp/override-repro/workdir/.rocks/share/tarantool/override/metrics/api.lua'
...
```
