### ISSUE TITLE
config credentials/users/<username>/privileges/*/permissions should be mandatory field

### ISSUE THREAD

**Issue by ochaton** [tarantool/tarantool#11441]
**Bug description**

Tarantool 3.4.0

**Reproduce**

Set following config

```yaml
credentials:
  users:
    peer:
      password: "<redacted>"
      roles: [ replication ]
      privileges:
          - lua_call:
             - "all"
```

Do reload: `config:reload()`

See error message:

```
builtin/config/applier/credentials.lua:1010: builtin/config/applier/credentials.lua:207: bad argument #1 to 'ipairs' (table expected, got nil) (LuajitError, code 0x20), see src/lua/utils.c line 700
```

**My expectations**

Clear error message in validation parameters, and json-schema of config should fill `permissions` with some values to highlight for me, that this fields should be filled

Jira: TNTP-2728
