### ISSUE TITLE
Let's serialize values of box.stat() and box.stat.net() as map, not mapping

### ISSUE THREAD

**Issue by ochaton** [tarantool/tarantool#11599]
Let's print it like this
```
tarantool> t = box.stat(); for k, v in pairs(t) do setmetatable(v, {__serialize='map'}) end; return t
---
- DELETE: {'total': 0, 'rps': 0}
  COMMIT: {'total': 0, 'rps': 0}
  SELECT: {'total': 0, 'rps': 0}
  ROLLBACK: {'total': 0, 'rps': 0}
  INSERT: {'total': 0, 'rps': 0}
  EVAL: {'total': 0, 'rps': 0}
  ERROR: {'total': 0, 'rps': 0}
  INSERT_ARROW: {'total': 0, 'rps': 0}
  CALL: {'total': 0, 'rps': 0}
  BEGIN: {'total': 0, 'rps': 0}
  PREPARE: {'total': 0, 'rps': 0}
  REPLACE: {'total': 0, 'rps': 0}
  UPSERT: {'total': 0, 'rps': 0}
  AUTH: {'total': 0, 'rps': 0}
  EXECUTE: {'total': 0, 'rps': 0}
  UPDATE: {'total': 0, 'rps': 0}
...
```

not like this

```
tarantool> box.stat()
---
- DELETE:
    total: 0
    rps: 0
  COMMIT:
    total: 0
    rps: 0
  SELECT:
    total: 1
    rps: 0
  ROLLBACK:
    total: 0
    rps: 0
  INSERT:
    total: 0
    rps: 0
  EVAL:
    total: 0
    rps: 0
  ERROR:
    total: 0
    rps: 0
  INSERT_ARROW:
    total: 0
    rps: 0
  CALL:
    total: 0
    rps: 0
  BEGIN:
    total: 0
    rps: 0
  PREPARE:
    total: 0
    rps: 0
  REPLACE:
    total: 0
    rps: 0
  UPSERT:
    total: 0
    rps: 0
  AUTH:
    total: 0
    rps: 0
  EXECUTE:
    total: 0
    rps: 0
  UPDATE:
    total: 0
    rps: 0
...
```

same for box.stat.net():

```
tarantool> t = box.stat.net() for k, v in pairs(t) do setmetatable(v, {__serialize='map'}) end return t
---
- CONNECTIONS: {'current': 0, 'rps': 0, 'total': 0}
  REQUESTS: {'current': 0, 'rps': 0, 'total': 0}
  REQUESTS_IN_PROGRESS: {'current': 0, 'rps': 0, 'total': 0}
  SENT: {'total': 0, 'rps': 0}
  REQUESTS_IN_STREAM_QUEUE: {'current': 0, 'rps': 0, 'total': 0}
  STREAMS: {'current': 0, 'rps': 0, 'total': 0}
  RECEIVED: {'total': 0, 'rps': 0}
...
```

```
tarantool> box.stat.net()
---
- CONNECTIONS:
    current: 0
    rps: 0
    total: 0
  REQUESTS:
    current: 0
    rps: 0
    total: 0
  REQUESTS_IN_PROGRESS:
    current: 0
    rps: 0
    total: 0
  SENT:
    total: 0
    rps: 0
  REQUESTS_IN_STREAM_QUEUE:
    current: 0
    rps: 0
    total: 0
  STREAMS:
    current: 0
    rps: 0
    total: 0
  RECEIVED:
    total: 0
    rps: 0
...
```
