### ISSUE TITLE
[uri]: improving to return parsed params

### ISSUE THREAD

**Issue by zloidemon** [tarantool/tarantool#1175]
Improving URI parser to parse parameters from query.

```
uri.parse('agi://10.10.80.23:3004/notify?callid=5432aca9-b35ae1c3@192.168.0.121&xxx=123')

---
- host: 10.10.80.23
  scheme: agi
  query: callid=5432aca9-b35ae1c3@192.168.0.121&xxx=123
  service: '3004'
  ipv4: 10.10.80.23
  path: /notify
...
```

I guess pass parsed params more better than parse its by custom code.

```
uri.parse('agi://10.10.80.23:3004/notify?callid=5432aca9-b35ae1c3@192.168.0.121&xxx=123')

---
- host: 10.10.80.23
  scheme: agi
  query: callid=5432aca9-b35ae1c3@192.168.0.121&xxx=123
  service: '3004'
  ipv4: 10.10.80.23
  path: /notify
  params:
    - callid: 5432aca9-b35ae1c3@192.168.0.121
      xxx: 123
...
```
