### ISSUE TITLE
vinyl: refactor box.info.vinyl() and index:info() output

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1662]
Per-Index Statistics
====================

Ranges
-------

index:info().range[id]:
  - begin - tuple, range begin key
  - end - tuple, range end key
  - rows - guage, number of rows stored in the range (approximate)
  - bytes - gauge, number of bytes stored in the range, uncompressed (approximate)
  - pages - gauge, number of pages in the range (approximate)
  - runs - gauge, the number of run lices in the range
  - levels - gauge, the number of logical levels
  - compress_ratio - gauge
  - compact:
    - count - counter, number of times runs in the range have been compacted
    - major_count - counter, number of times all runs in the range have been compacted
    - in
      - rows - counter
      - bytes - counter
    - out
      - rows - counter
      - bytes - counter
  - dump: -- calculated on vy_task_dump_complete()
    - count - counter
    - in
      - rows - counter
      - bytes - counter
    - out
      - rows - counter
      - bytes - counter
  - read:
    - rows - counter
    - bytes - counter
    - disk
      - rows - counter
      - bytes - counter
      - pages - counter
  - bloom
    - hit - counter - number of times bloom filter spared disk read
    - miss - counter - number of times bloom filter failed to spare disk read
    - fpr - guage   - measured false-positive rate, 0.00 - 1.00
    - size - gauge   - total size occupied by bloom filters in memory, in bytes

index:info().range.total: - cumulative information about ranges in the same format

Mems
----

index:info().mems[id]:
  - rows - guage
  - bytes - gauge
  - write:
    - rows - counter
    - bytes - counter

index:info().mems.total - the cumulative information about mems in the same format

Configuration options:

 - range_size
 - index_size
 - run_count_per_level
 - run_size_ratio
 - bloom_fpr

Global Statistics
=================

Memory
------

box.info.vinyl().memory:
  - used - gauge, quota used, in bytes
  - limit - gauge, quota limit, in bytes
  - ratio - gauge, = used / limit
  - watermark - gauge, quota watermark, in bytes
  - fill_rate - gauge, quota consumption rate, bytes per sec
  - dump_rate - gauge, quota release rate, bytes per sec

Configuration options:

- box.cfg.vinyl_memory

Cache
-----

box.info.vinyl().cache
  - rows - gauge, number of cached statements
  - bytes - gauge, size of cached statements, in bytes
  - hits - counter
  - misses - counter
  - evictions - counter
  - ratio - gauge = hits / (hits + misses)

Configuration options:

- box.cfg.vinyl_cache

Transactions
------------

box.info.vinyl().tx
  - commit - counter, number of transactions committed
  - rollback - counter, number of transactions roll-backed
  - conflict - counter, number of transactions aborted due to conflict
  - active - gauge, number of transactions in-flight

Q: Why there are no per-index cache and tx statistics?
A: Because cache && tx are database-wide and can be only configured
  per database basis

--------------------------------------------------------------------------------

**counter** - A counter is a cumulative metric that represents a single numerical value that only ever goes up. A counter is typically used to count requests served, tasks completed, errors occurred, etc. Counters should not be used to expose current counts of items whose number can also go down
**gauge** - A gauge is a metric that represents a single numerical value that can arbitrarily go up and down.
**histogram** - A histogram samples observations (usually things like request durations or response sizes) and counts them in configurable buckets. It also provides a sum of all observed values.

**Comment by rtsisyk** [comment]
@kostja:
> Do nothing for now. The whole concept of calling Lua functions to
get this data is broken is too slow, we shouldn't materialize
it every time.

**Comment by rtsisyk** [comment]
Discussed on scrum, move to 1.7.3

**Comment by rtsisyk** [comment]
Actually, this is a breaking changed. I need feedback on this ticket.

**Comment by kostja** [comment]
OK, we agreed to move this to box.space.<space-name>:info()

**Comment by rtsisyk** [comment]
Postponed.

**Comment by rtsisyk** [comment]
```
box.space.vinyl.index.primary:info():
---
- count: 10 -- the number of tuples in the index
  memory:
    data:
      fragmentation: 97.9%
      allocated: 211848
    index:
      used: 999424 
      fragmentation: 52.3%
      allocated: 2097048
...
```

**Comment by rtsisyk** [comment]
Per index:

```
box.space.vinyl.index.primary:info():
---
- count: 10 -- the number of tuples in the index
  memory:
    used: 999424 # total size of data stored in-memory
    allocated: 2097048
  disk:
    used: 21321321 # total size of data stored on disk
    seeks: 500
    reads: 13131232
  ranges: 5 # the numbe rof ranges
  runs: # histogram of run count per range
   - 1: 67%
     2: 38%
     3: 3%
     4: 2%
  pages: # the number of pages in all runs
  cache:
    hits: 300
    misses: 200
...
```

Per space:  cumulative information for all indexes in the same format

**Comment by rtsisyk** [comment]
```
box.space.vinyl.index:stat()
---
- SEEKS:
    total: 0
    rps: 0
  READS:
    total: 2
    rps: 0
  WRITES:
    total: 2
    rps: 0
  ERRORS:
    total: 0
    rps: 0

```

**Comment by alyapunov** [comment]
```
Alternative
box.space.vinyl.index:io()
--
-IN_THROUGHPUT: 1Mb/s
-DISC_WRITE_THROUGHPUT : 4Mb/s
-DISC_READ_THROUGHPUT : 7Mb/s
```

**Comment by alyapunov** [comment]
In terms of brainstorm
```
box.space.vinyl.index:iter_stats()
--
RANGE:
  lookups:
    total: 100
    rps: 10
  steps:
    total: 100
    rps: 10
TXW:
  lookups:
    total: 100
    rps: 10
  steps:
    total: 100
    rps: 10
CACHE:
  lookups:
    total: 100
    rps: 10
  steps:
    total: 100
    rps: 10
MEM:
  lookups:
    total: 100
    rps: 10
  steps:
    total: 100
    rps: 10
RUN:
  lookups:
    total: 100
    rps: 10
  steps:
    total: 100
    rps: 10
```

**Comment by racktear** [comment]
Some raw feedback:

   - Number of runs per ranges is in %-s. Why? If it's a fraction of maximum
     number of rans per range, it should be a fraction, and not %-s. But
     anyway, the meaning is puzzling.
   - `pages` will be clearer if named `pages_total`.
   - Cache hits and misses should probably go to box.stat. Right now we have
     a separation of immediate and statistical values. The same goes for
     disk seeks and reads.
   - `count` should be renamed to something like `tuples_per_index`
   - As with box.cfg, values that have units will look better with a unit
     suffix, e.g. memory.used_bytes or memory.allocated_bytes

**Comment by rtsisyk** [comment]
I implemented required infrastructure for space:info()/index:info().  Please review.

**Comment by rtsisyk** [comment]
The first step is done - `box.info.vinyl().db['512/0']` garbage has been moved to` index:info()` without any changes. I also removed `box.info.vinyl().vinyl` and `box.info.vinyl().metric` sections.

It seems we are not ready to freeze `box.info().vinyl()` and `index:info()` format in 1.7.4. Let's keep this API for **internal** use only. Please don't document, it will change in the future. Since the API is for internal use, I remove "breaking change" label.

**Comment by locker** [comment]
**Proposal**
1. Both per index and global stats:
```
   keys
   bytes
   keys_read
   bytes_read
   keys_written
   bytes_written

   mem_keys
   mem_bytes
   mem_keys_read
   mem_bytes_read
   mem_keys_written
   mem_bytes_written

   cache_keys
   cache_bytes
   cache_keys_read
   cache_bytes_read
   cache_keys_written
   cache_bytes_written
   cache_keys_evicted
   cache_bytes_evicted

   bloom_hit
   bloom_miss

   disk_pages
   disk_keys
   disk_bytes
   disk_pages_read
   disk_keys_read
   disk_bytes_read
   disk_pages_written
   disk_keys_written
   disk_bytes_written
   disk_pages_written_compact
   disk_keys_written_compact
   disk_bytes_written_compact
   disk_pages_written_dump
   disk_keys_written_dump
   disk_bytes_written_dump

   wa			(write amplification)

   ra			(read amplification in bytes read from disk)
   ra_seeks		(read amplification in disk seeks)

   read_latency_avg
   read_latency_max

   bloom_size		(in memory)
   page_index_size	(in memory)
```
2. Global stats (box.info.vinyl)
```
   quota_used
   quota_watermark
   quota_limit

   write_rate
   dump_bandwidth

   tx_commit
   tx_rollback
   tx_conflict
   tx_active
```
3. Index stats (index.info)
```
   range_count
   run_count
   runs_in_range	(histogram)

   dump_count
   range_split_count
   range_coalesce_count
```
4. Range stats (index.info.ranges)
```
   begin_key
   end_key

   run_count

   est_pages		(this and the following two counters are estimated)
   est_keys
   est_bytes

   compact_count
   maj_compact_count
```

**Comment by locker** [comment]
This is how it will look in yaml:
```
tarantool> box.info.vinyl()
---
- mem_keys_read: 2008
  cache_bytes_written: 3245343
  bytes: 1288069
  read_latency_max: 0.11
  cache_keys_read: 3244
  cache_used_ratio: 87%
  write_ampl: 11.2
  cache_keys_written: 2343
  read_latency_avg: 0.02
  disk_keys: 23424
  cache_keys: 323
  tx_active: 0
  quota_used_ratio: 55%
  bytes_written: 40404586
  tx_rollback: 23
  mem_keys_written: 44000
  dump_bandwidth: 34535
  page_index_size: 2342452
  quota_watermark: 7000000
  cache_keys_evicted: 2342
  disk_keys_written: 23422
  tx_conflict: 12
  quota_used: 5500000
  disk_pages_written_dump: 1231
  mem_bytes: 4008080
  upsert_applied: 234243
  bloom_miss: 324
  write_rate: 12321
  mem_bytes_read: 2003888
  read_ampl_seeks: 6.8
  bloom_size: 123143
  disk_pages_read: 3245
  disk_bytes_written_dump: 234234
  cache_bytes: 3243245
  quota_limit: 10000000
  mem_bytes_written: 44099307
  disk_pages_written_compact: 12334
  disk_bytes_written_compact: 2342425
  disk_keys_written_dump: 12313
  tx_commit: 1322
  cache_bytes_read: 4324536
  read_ampl: 5.5
  keys: 1233
  mem_keys: 400
  keys_written: 40300
  bytes_read: 2004004
  disk_keys_written_compact: 234255
  cache_bytes_evicted: 23453254
  keys_read: 20040
  upsert_squashed: 32342
  bloom_hit: 23423
  disk_bytes_read: 2342432
  disk_pages: 2342
  disk_bytes: 2342324
  disk_keys_read: 34324
  disk_pages_written: 2342
...
```
It would look better if we sorted it:
```
tarantool> box.info.vinyl()
---
- bloom_hit: 23423
  bloom_miss: 324
  bloom_size: 123143
  bytes: 1288069
  bytes_read: 2004004
  bytes_written: 40404586
  cache_bytes: 3243245
  cache_bytes_evicted: 23453254
  cache_bytes_read: 4324536
  cache_bytes_written: 3245343
  cache_keys: 323
  cache_keys_evicted: 2342
  cache_keys_read: 3244
  cache_keys_written: 2343
  cache_used_ratio: 87%
  disk_bytes: 2342324
  disk_bytes_read: 2342432
  disk_bytes_written_compact: 2342425
  disk_bytes_written_dump: 234234
  disk_keys: 23424
  disk_keys_read: 34324
  disk_keys_written: 23422
  disk_keys_written_compact: 234255
  disk_keys_written_dump: 12313
  disk_pages: 2342
  disk_pages_read: 3245
  disk_pages_written: 2342
  disk_pages_written_compact: 12334
  disk_pages_written_dump: 1231
  dump_bandwidth: 34535
  keys: 1233
  keys_read: 20040
  keys_written: 40300
  mem_bytes: 4008080
  mem_bytes_read: 2003888
  mem_bytes_written: 44099307
  mem_keys: 400
  mem_keys_read: 2008
  mem_keys_written: 44000
  page_index_size: 2342452
  quota_limit: 10000000
  quota_used: 5500000
  quota_used_ratio: 55%
  quota_watermark: 7000000
  read_ampl: 5.5
  read_ampl_seeks: 6.8
  read_latency_avg: 0.02
  read_latency_max: 0.11
  tx_active: 0
  tx_commit: 1322
  tx_conflict: 12
  tx_rollback: 23
  upsert_applied: 234243
  upsert_squashed: 32342
  write_ampl: 11.2
  write_rate: 12321
...
```
Alternatively, we could group statistics in tables by category:
```
tarantool> box.info.vinyl()
---
- write_rate: 12321
  bytes_written: 40404586
  page_index_size: 2342452
  bytes: 1288069
  cache:
    keys_evicted: 2342
    keys: 323
    bytes_written: 3245343
    bytes: 3243245
    bytes_evicted: 23453254
    bytes_read: 4324536
    keys_read: 3244
    keys_written: 2343
    used: 87%
  write_ampl: 11.2
  dump_bandwidth: 34535
  read_ampl: 5.5
  keys: 1233
  keys_written: 40300
  read_latency:
    avg: 0.02
    max: 0.11
  quota:
    watermark: 7000000
    used_ratio: 55%
    limit: 10000000
    used: 5500000
  mem:
    keys: 400
    bytes_written: 44099307
    bytes_read: 2003888
    keys_written: 44000
    bytes: 4008080
    keys_read: 2008
  upsert:
    applied: 234243
    squashed: 32342
  read_ampl_seeks: 6.8
  disk:
    pages_read: 3245
    bytes_written_compact: 2342425
    keys_written: 23422
    pages_written_compact: 12334
    bytes: 2342324
    bytes_written_dump: 234234
    keys_written_compact: 234255
    pages_written_dump: 1231
    pages_written: 2342
    keys_written_dump: 12313
    bytes_read: 2342432
    pages: 2342
    keys: 23424
    keys_read: 34324
  tx:
    conflict: 12
    active: 0
    commit: 1322
    rollback: 23
  bytes_read: 2004004
  bloom_size: 123143
  bloom:
    hit: 23423
    miss: 324
  keys_read: 20040
...
```
