### ISSUE TITLE
show fibers does not show function names

### ISSUE THREAD

**Issue by whiteglasses** [tarantool/tarantool#176]
tarantool-1.5.2-41

```

---
fibers:
  - fid: 11328
    csw: 395
    name: admin/127.0.0.1:33487
    stack: 0x7f67fa573000
    backtrace:
#0  0x7f6d024ac4f9 in ?
#1  0x444a53 in ?
#2  0x445cdb in ?
#3  0x4532a5 in ?
#4  0x4452c8 in ?
#5  0x464f77 in ?
#6  0x413478 in ?
  - fid: 11034
    csw: 162
    name: iproto
    stack: 0x7f67fa593000
    backtrace:
#0  0x454a6d in ?
#1  0x4452c8 in ?
#2  0x464f77 in ?
#3  0x413478 in ?
```
