### ISSUE TITLE
Package net in Tarantool 1.7

### ISSUE THREAD

**Issue by bigbes** [tarantool/tarantool#1813]
It's exported into global environment:

```
blikh@bigbes-laptop:~/src/work/tarantool/extra/dist$ tarantool
tarantool: version 1.7.2-8-g75a1ffa
type 'help' for interactive help
tarantool> net
---
- box:
    lib:
      encode_call_16: 'function: 0x093570a0'
      encode_call: 'function: 0x093570f0'
      encode_ping: 'function: 0x09357050'
      encode_replace: 'function: 0x09357230'
      encode_auth: 'function: 0x09357370'
      encode_select: 'function: 0x09357190'
      communicate: 'function: 0x09357410'
      encode_insert: 'function: 0x093571e0'
      decode_greeting: 'function: 0x093573c0'
      encode_eval: 'function: 0x09357140'
      encode_delete: 'function: 0x09357280'
      encode_upsert: 'function: 0x09357320'
      encode_update: 'function: 0x093572d0'
...
```

It shouldn't.
