### ISSUE TITLE
Start master-master cluster node when one or more nodes dead

### ISSUE THREAD

**Issue by cyanide-burnout** [tarantool/tarantool#1870]
Existing behavior: at this moment when I try to restart one of servers the restart failed.
Expected behavior: successful restart with following attempts to reconnect

**Comment by aensidhe** [comment]
I confirm issue.

docker-compose.yml:
```
version: '2'

services:
  tarantool1:
    image: tarantool/tarantool:1.7
    command: tarantool /usr/local/share/tarantool/sample.init.lua
    volumes:
      - $PWD/tarantool:/usr/local/share/tarantool
    environment:
      TARANTOOL_REPLICATION_SOURCE: "replicator:234234@tarantool1,replicator:234234@tarantool2"
      TARANTOOL_REPLICATION_USER: replicator
      TARANTOOL_USER_PASSWORD: "234234"

  tarantool2:
    image: tarantool/tarantool:1.7
    command: tarantool /usr/local/share/tarantool/sample.init.lua
    volumes:
      - $PWD/tarantool:/usr/local/share/tarantool
    environment:
      TARANTOOL_REPLICATION_SOURCE: "replicator:234234@tarantool1,replicator:234234@tarantool2"
      TARANTOOL_REPLICATION_USER: replicator
      TARANTOOL_USER_PASSWORD: "234234"
```

```
aensidhe@DESKTOP-KE96P1V  /d/Repos/OSS/tarantool-csharp/samples/docker-compose (fix/tests/cleanup)
$ docker-compose up tarantool1
Creating network "dockercompose_default" with the default driver
Creating dockercompose_tarantool1_1
Attaching to dockercompose_tarantool1_1
[36mtarantool1_1  |[0m /usr/local/bin/tarantool-entrypoint.lua: Creating configuration file: /etc/tarantool/config.yml
[36mtarantool1_1  |[0m /usr/local/bin/tarantool-entrypoint.lua: Config:
[36mtarantool1_1  |[0m ---
[36mtarantool1_1  |[0m snap_dir: /var/lib/tarantool
[36mtarantool1_1  |[0m snapshot_period: 3600
[36mtarantool1_1  |[0m log_level: 5
[36mtarantool1_1  |[0m pid_file: /var/run/tarantool/tarantool.pid
[36mtarantool1_1  |[0m listen: 3301
[36mtarantool1_1  |[0m background: false
[36mtarantool1_1  |[0m replication_source:
[36mtarantool1_1  |[0m - replicator:234234@tarantool1:3301
[36mtarantool1_1  |[0m - replicator:234234@tarantool2:3301
[36mtarantool1_1  |[0m wal_dir: /var/lib/tarantool
[36mtarantool1_1  |[0m ...
[36mtarantool1_1  |[0m
[36mtarantool1_1  |[0m 2016-10-26 13:42:15.835 [1] main/101/tarantool-entrypoint.lua C> version 1.7.2-1-g92ed6c4
[36mtarantool1_1  |[0m 2016-10-26 13:42:15.835 [1] main/101/tarantool-entrypoint.lua C> log level 5
[36mtarantool1_1  |[0m 2016-10-26 13:42:15.835 [1] main/101/tarantool-entrypoint.lua I> mapping 1073741824 bytes for tuple arena...
[36mtarantool1_1  |[0m 2016-10-26 13:42:15.846 [1] iproto/102/iproto I> binary: started
[36mtarantool1_1  |[0m 2016-10-26 13:42:15.846 [1] iproto/102/iproto I> binary: bound to 0.0.0.0:3301
[36mtarantool1_1  |[0m 2016-10-26 13:42:15.863 [1] main/103/applier/tarantool1:3301 I> connected to 1.7.2 at 172.20.0.2:3301
[36mtarantool1_1  |[0m
[36mtarantool1_1  |[0m 2016-10-26 13:42:15.896 [1] main/104/applier/tarantool2:3301 I> can't connect to master
[36mtarantool1_1  |[0m 2016-10-26 13:42:15.896 [1] main/104/applier/tarantool2:3301 coio.cc:205 !> SystemError getaddrinfo, called on fd -1: No error information
[36mtarantool1_1  |[0m 2016-10-26 13:42:15.896 [1] main/104/applier/tarantool2:3301 I> will retry every 1 second
[36mtarantool1_1  |[0m 2016-10-26 13:42:45.847 [1] main/101/tarantool-entrypoint.lua applier.cc:663 E> ER_CFG: Incorrect value for option 'replication_source': failed to connect to one or more servers
[36mtarantool1_1  |[0m 2016-10-26 13:42:45.847 [1] main/101/tarantool-entrypoint.lua F> can't initialize storage: Incorrect value for option 'replication_source': failed to connect to one or more servers
[36mdockercompose_tarantool1_1 exited with code 1
```
