### ISSUE TITLE
Rename values in box.slab.info() report

### ISSUE THREAD

**Issue by lenkis** [tarantool/tarantool#1883]
Currently, the term "item" means different things in `box.slab` reports:
 1) in `box.slab.info()`, "item" means "only tuples, no indexes" (for "tuples+indexes together" we use the term "arena" there)
 2) in `box.slab.stats()`, "item" means "tuples+indexes together" (`mem_used` in this report = `arena_used` in `info()` report)

 To avoid confusion, I suggest changing the following terms in `info()` report:
1) "items" --> "tuples" (while "items" in `stats()` report remains an aggregation for "tuples+ indexes together")
2) "arena" --> "items"

Then both reports will use the same terminology: tuples = tuples,  items = tuples+indexes.

**Comment by rtsisyk** [comment]
Should be discussed with @kostja 
See also #933 #934

**Comment by rtsisyk** [comment]
This is a breaking change which should be discussed.

**Comment by kostja** [comment]
[1.txt](https://github.com/tarantool/tarantool/files/633696/1.txt)

We agreed to implement a new function, box.memory.info(), largely along the lines of the attached diff.

Differences from the attached diff: 
- malloc memory, as well as Lua and runtime memory, in a single view
- vinyl/memtx memory each in its own group

**Comment by racktear** [comment]
This will (probably) break the prometheus module, as it currently reports memory usage.
Will there be backwards compatibility?

**Comment by rtsisyk** [comment]
My proposal is to add a new box.info.memory section and keep box.slab.info() as is:

```
box.info.memory
---
- lua:
    maxalloc: 1073741824
    used: 23432432
  runtime:
    fragmentation: 22%
    maxalloc: 1073741824
    used: 23432432
  memtx:
    data:
      fragmentation: 97.9%
      allocated: 211848
      used: 211848
    index:
      fragmentation: 52.3%
      allocated: 2097048
      used: 999424
  vinyl:
    cache:
      fragmentation: 97.9%
      allocated: 211848
      used: 211848
    data:
      fragmentation: 97.9%
      allocated: 211848
      used: 211848
    index:
      fragmentation: 52.3%
      allocated: 2097048
      used: 999424
...
```
