### ISSUE TITLE
Request statistic by masters

### ISSUE THREAD

**Issue by whiteglasses** [tarantool/tarantool#2034]
Tarantool can receive requests directly or by replication from another tarantool(s). All of these requests are accounted in box.stat().
But i need to know how many requests came directly from clients and how many by replication.

it will be very useful to have something like

```
box.stat_by_source()
  total:
    DELETE:
      total: 1873949
      rps: 123
    SELECT:
      total: 1237723
      rps: 4099
...
  3: #(index of replication source)
    DELETE:
      total: 20
      rps: 1
    SELECT:
      total: 0
      rps: 0
  4: #(index of replication source)
    DELETE:
      total: 25
      rps: 1
    SELECT:
      total: 0
      rps: 0
```
