### ISSUE TITLE
tarantoolctl: `cat` command ignores space filter

### ISSUE THREAD

**Issue by rtokarev** [tarantool/tarantool#2543]
```
# tarantoolctl cat --space 00000000000000010960.xlog  --space=514 | head -n20
Processing file '00000000000000010960.xlog'
---
HEADER:
  lsn: 10961
  replica_id: 1
  type: DELETE
  timestamp: 1498150403.1942
BODY:
  space_id: 513
  key: [1000014131]
---
HEADER:
  lsn: 10962
  replica_id: 1
  type: DELETE
  timestamp: 1498150403.1942
BODY:
  space_id: 514
  key: [1000014131, 2]
---
HEADER:
...
```
[xlog.zip](https://github.com/tarantool/tarantool/files/1095787/xlog.zip)
