### ISSUE TITLE
vinyl: crash in vy_tx_rollback_after_prepare

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#2588]
100% reproducibility on all versions:

```
tarantool> box.schema.space.create('vinyl', { engine = 'vinyl' })
---
- index: []
  on_replace: 'function: 0x401253c8'
  temporary: false
  id: 514
  engine: vinyl
  enabled: false
  name: vinyl
  field_count: 0
- created
...

tarantool> box.space.vinyl:create_index('primary')
---
- unique: true
  parts:
  - type: unsigned
    fieldno: 1
  id: 0
  space_id: 514
  options:
    page_size: 8192
    run_count_per_level: 2
    run_size_ratio: 3.5
    bloom_fpr: 0.05
    range_size: 1073741824
  name: primary
  type: TREE
...

tarantool> box.space.vinyl:replace({1, string.rep('x', 10 * 1024 * 1024)})
tarantool: /home/roman/tarantool/1.7/src/box/vinyl.c:5868: vy_tx_rollback_after_prepare: Assertion `xm->last_prepared_tx == tx' failed.

Thread 1 "tarantool" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff55383fa in __GI_abort () at abort.c:89
#2  0x00007ffff552fe37 in __assert_fail_base (fmt=<optimized out>, assertion=assertion@entry=0x5555558c24de "xm->last_prepared_tx == tx",
    file=file@entry=0x5555558c0d30 "/home/roman/tarantool/1.7/src/box/vinyl.c", line=line@entry=5868,
    function=function@entry=0x5555558c34f0 <__PRETTY_FUNCTION__.19230> "vy_tx_rollback_after_prepare") at assert.c:92
#3  0x00007ffff552fee2 in __GI___assert_fail (assertion=0x5555558c24de "xm->last_prepared_tx == tx",
    file=0x5555558c0d30 "/home/roman/tarantool/1.7/src/box/vinyl.c", line=5868,
    function=0x5555558c34f0 <__PRETTY_FUNCTION__.19230> "vy_tx_rollback_after_prepare") at assert.c:101
#4  0x0000555555601843 in vy_tx_rollback_after_prepare (tx=0x7ffff110c0e0) at /home/roman/tarantool/1.7/src/box/vinyl.c:5868
#5  0x00005555556019a3 in vy_tx_rollback (tx=0x7ffff110c0e0) at /home/roman/tarantool/1.7/src/box/vinyl.c:5896
#6  0x0000555555601dde in vy_rollback (tx=0x7ffff110c0e0) at /home/roman/tarantool/1.7/src/box/vinyl.c:5988
#7  0x00005555555e74af in VinylEngine::rollback (this=0x555555dc95f0, txn=0x7ffff1102090)
    at /home/roman/tarantool/1.7/src/box/vinyl_engine.cc:181
#8  0x000055555564b029 in txn_rollback () at /home/roman/tarantool/1.7/src/box/txn.cc:293
#9  0x000055555564aef4 in txn_rollback_stmt () at /home/roman/tarantool/1.7/src/box/txn.cc:270
#10 0x000055555564db74 in process_rw (request=0x7ffff1102038, space=0x555555dfcef0, result=0x7ffff101fe00)
    at /home/roman/tarantool/1.7/src/box/box.cc:230
#11 0x000055555564f636 in box_process1 (request=0x7ffff1102038, result=0x7ffff101fe00) at /home/roman/tarantool/1.7/src/box/box.cc:724
#12 0x000055555564f8a2 in box_replace (space_id=514, tuple=0x7fffcabfe048 "\222", <incomplete sequence \333>, tuple_end=0x7fffcb5fe04f "",
    result=0x7ffff101fe00) at /home/roman/tarantool/1.7/src/box/box.cc:778
#13 0x0000555555670ead in lbox_replace (L=0x40000378) at /home/roman/tarantool/1.7/src/box/lua/index.c:72
#14 0x00005555556c554b in lj_BC_FUNCC ()
#15 0x00005555556e78df in lua_pcall (L=0x40000378, nargs=0, nresults=0, errfunc=0) at lj_api.c:1129
#16 0x000055555569fc43 in luaT_call (L=0x40000378, nargs=0, nreturns=0) at /home/roman/tarantool/1.7/src/lua/utils.c:931
#17 0x0000555555698e46 in run_script_f (ap=0x7ffff1000208) at /home/roman/tarantool/1.7/src/lua/init.c:496
#18 0x00005555555a08de in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=0x555555698acd <run_script_f>,
    ap=0x7ffff1000208) at /home/roman/tarantool/1.7/src/fiber.h:647
#19 0x00005555556aee38 in fiber_loop (data=0x0) at /home/roman/tarantool/1.7/src/fiber.c:641
#20 0x000055555587fdbf in coro_init () at /home/roman/tarantool/1.7/third_party/coro/coro.c:110
```
