### ISSUE TITLE
SIGSEGV in space:truncate

### ISSUE THREAD

**Issue by iskandarov-egor** [tarantool/tarantool#2673]
my space:

```
tarantool> box.space.images_faces
---
- index:
    0: &0
      unique: true
      parts:
      - type: string
        fieldno: 1
      id: 0
      space_id: 515
      options:
        page_size: 8192
        run_count_per_level: 2
        run_size_ratio: 3.5
        bloom_fpr: 0.05
        range_size: 1073741824
      name: primary
      type: TREE
    1: &1
      unique: false
      parts:
      - type: string
        fieldno: 2
      - type: string
        fieldno: 3
      - type: string
        fieldno: 4
      id: 1
      space_id: 515
      options:
        page_size: 8192
        run_count_per_level: 2
        run_size_ratio: 3.5
        bloom_fpr: 0.05
        range_size: 1073741824
      name: user_image_face
      type: TREE
    2: &2
      unique: true
      parts:
      - type: string
        fieldno: 2
      - type: string
        fieldno: 4
      - type: string
        fieldno: 3
      - type: string
        fieldno: 1
      id: 2
      space_id: 515
      options:
        page_size: 8192
        run_count_per_level: 2
        run_size_ratio: 3.5
        bloom_fpr: 0.05
        range_size: 1073741824
      name: user_face_image_id
      type: TREE
    3: &3
      unique: true
      parts:
      - type: string
        fieldno: 2
      - type: string
        fieldno: 4
      - type: unsigned
        fieldno: 6
      - type: string
        fieldno: 1
      id: 3
      space_id: 515
      options:
        page_size: 8192
        run_count_per_level: 2
        run_size_ratio: 3.5
        bloom_fpr: 0.05
        range_size: 1073741824
      name: user_face_mtime_id
      type: TREE
    primary: *0
    user_face_mtime_id: *3
    user_face_image_id: *2
    user_image_face: *1
  on_replace: 'function: 0x40959b48'
  temporary: false
  id: 515
  engine: vinyl
  enabled: true
  name: images_faces
  field_count: 0
...
````

this code causes SIGSEGV:

```
for j=1,60 do
	box.space.images_faces:truncate()
	self = {}
	self.end2018 = os.time{year=2018, month=12, day=31, hour=23, min=59, sec=59}
	self.start2019 = os.time{year=2019, month=1, day=1, hour=0, min=0, sec=0}
	self.week1end = os.time{year=2019, month=1, day=6, hour=23, min=59, sec=59}
	self.week2start = os.time{year=2019, month=1, day=7, hour=0, min=0, sec=0}
	local iface1 = box.space.images_faces:insert{'id1', 'uid1', 'iid1', 'fid1', {1, 2, 3, 4}, self.end2018}
	local iface2 = box.space.images_faces:insert{'id2', 'uid1', 'iid1', 'fid1', {1, 2, 3, 4}, self.start2019}
	local iface3 = box.space.images_faces:insert{'id3', 'uid1', 'iid1', 'fid1', {1, 2, 3, 4}, self.week1end}
	local iface4 = box.space.images_faces:insert{'id4', 'uid1', 'iid1', 'fid1', {1, 2, 3, 4}, self.week2start}

	local f, ctx, state = box.space.images_faces.index.user_face_mtime_id:pairs({'uid1', 'fid1', 0x7FFFFFFF}, { iterator='LE' })
	state, tup = f(ctx, state)
	state, tup = f(ctx, state)
end

```

backtrace:
```
(gdb) where
#0  0x00007ff96c6775f7 in raise () from /lib64/libc.so.6
#1  0x00007ff96c678ce8 in abort () from /lib64/libc.so.6
#2  0x000000000040e42d in sig_fatal_cb (signo=<optimized out>) at /build/usr/src/debug/tarantool-1.7.4.372/src/main.cc:186
#3  <signal handler called>
#4  0x00000000004662a6 in tuple_compare (key_def=0x0, tuple_b=0x22ddcf0, tuple_a=0x2241bb0)
    at /build/usr/src/debug/tarantool-1.7.4.372/src/box/tuple_compare.h:88
#5  vy_tuple_compare (cmp_def=0x0, b=0x22ddcf0, a=0x2241bb0) at /build/usr/src/debug/tarantool-1.7.4.372/src/box/vy_stmt.h:338
#6  vy_stmt_compare (key_def=0x0, b=0x22ddcf0, a=0x2241bb0) at /build/usr/src/debug/tarantool-1.7.4.372/src/box/vy_stmt.h:385
#7  read_set_cmp (a=0x7ff96252b3d0, b=0x7ff96252b470) at /build/usr/src/debug/tarantool-1.7.4.372/src/box/vy_tx.c:65
#8  0x0000000000466390 in read_set_remove (rbtree=0x2198c98, node=node@entry=0x7ff96252b3d0) at /build/usr/src/debug/tarantool-1.7.4.372/src/box/vy_tx.h:123
#9  0x0000000000468855 in vy_tx_destroy (tx=tx@entry=0x7ff9625351a0) at /build/usr/src/debug/tarantool-1.7.4.372/src/box/vy_tx.c:278
#10 0x00000000004467e8 in vy_cursor_delete (env=0x2198810, c=0x7ff9625351a0) at /build/usr/src/debug/tarantool-1.7.4.372/src/box/vinyl.c:4984
#11 0x0000000000438602 in vinyl_iterator_free (ptr=0x22284c0) at /build/usr/src/debug/tarantool-1.7.4.372/src/box/vinyl_index.cc:190
#12 0x00000000004e7a33 in lj_vm_ffi_call () at buildvm_x86.dasc:2576
#13 0x000000000052a7df in lj_ccall_func (L=L@entry=0x41b12378, cd=<optimized out>) at lj_ccall.c:1150
#14 0x000000000053ec16 in lj_cf_ffi_meta___call (L=0x41b12378) at lib_ffi.c:230
#15 0x00000000004e5a87 in lj_BC_FUNCC () at buildvm_x86.dasc:809
#16 0x00000000004e7b7b in gc_call_finalizer (g=g@entry=0x41b123b8, L=L@entry=0x41b12378, mo=mo@entry=0x7ff96241fa10, o=o@entry=0x40b5f4e8) at lj_gc.c:502
#17 0x00000000004e7ce3 in gc_finalize (L=0x41b12378) at lj_gc.c:536
#18 0x00000000004e8717 in gc_onestep (L=L@entry=0x41b12378) at lj_gc.c:695
#19 0x00000000004e8d94 in lj_gc_step (L=0x41b12378) at lj_gc.c:725
#20 0x00000000004e8e46 in lj_gc_step_fixtop (L=L@entry=0x41b12378) at lj_gc.c:748
#21 0x00000000004ec4bb in lj_func_newL_gc (L=0x41b12378, pt=0x40ee2668, parent=0x40f8f9f0) at lj_func.c:159
#22 0x00000000004e4d21 in lj_BC_FNEW () at buildvm_x86.dasc:539
#23 0x00000000004b3e63 in lbox_fillspace (i=4, space=0x2248120, L=0x41b12378) at /build/usr/src/debug/tarantool-1.7.4.372/src/box/lua/space.cc:246
#24 box_lua_space_new (L=0x41b12378, space=space@entry=0x2248120) at /build/usr/src/debug/tarantool-1.7.4.372/src/box/lua/space.cc:281
#25 0x0000000000494e31 in space_cache_replace (space=space@entry=0x2248120) at /build/usr/src/debug/tarantool-1.7.4.372/src/box/schema.cc:172
#26 0x000000000048b610 in on_replace_dd_truncate (event=0x7ff9624080a0) at /build/usr/src/debug/tarantool-1.7.4.372/src/box/alter.cc:1553
#27 0x000000000049a194 in trigger_run (event=<optimized out>, list=<optimized out>) at /build/usr/src/debug/tarantool-1.7.4.372/src/trigger.h:77
#28 txn_commit_stmt (txn=txn@entry=0x7ff9624080a0, request=request@entry=0x7ff962408048) at /build/usr/src/debug/tarantool-1.7.4.372/src/box/txn.cc:179
#29 0x000000000049b7a8 in process_rw (request=request@entry=0x7ff962408048, space=space@entry=0x220dc00, result=result@entry=0x0)
    at /build/usr/src/debug/tarantool-1.7.4.372/src/box/box.cc:224
#30 0x000000000049d629 in box_process1 (request=0x7ff962408048, result=0x0) at /build/usr/src/debug/tarantool-1.7.4.372/src/box/box.cc:753
#31 0x000000000049e1db in box_upsert (space_id=space_id@entry=330, index_id=index_id@entry=0, tuple=<optimized out>, tuple_end=<optimized out>, 
    ops=ops@entry=0x7ff96241fdf0 "\221\223\241+\001\001", ops_end=ops_end@entry=0x7ff96241fdf6 "", index_base=0, result=0x0)
    at /build/usr/src/debug/tarantool-1.7.4.372/src/box/box.cc:868
#32 0x000000000049e3b0 in space_truncate (space=<optimized out>) at /build/usr/src/debug/tarantool-1.7.4.372/src/box/box.cc:894
#33 box_truncate (space_id=515) at /build/usr/src/debug/tarantool-1.7.4.372/src/box/box.cc:904
---Type <return> to continue, or q <return> to quit---
#34 0x00000000004b298d in lbox_truncate (L=0x41b12378) at /build/usr/src/debug/tarantool-1.7.4.372/src/box/lua/index.c:292
#35 0x00000000004e5a87 in lj_BC_FUNCC () at buildvm_x86.dasc:809
#36 0x00000000004f6b51 in lua_pcall (L=L@entry=0x41b12378, nargs=<optimized out>, nresults=nresults@entry=0, errfunc=errfunc@entry=0) at lj_api.c:1129
#37 0x00000000004c2aa5 in luaT_call (L=L@entry=0x41b12378, nargs=<optimized out>, nreturns=nreturns@entry=0)
    at /build/usr/src/debug/tarantool-1.7.4.372/src/lua/utils.c:931
#38 0x00000000004bd569 in run_script_f (ap=<error reading variable: value has been optimized out>)
    at /build/usr/src/debug/tarantool-1.7.4.372/src/lua/init.c:508
#39 0x000000000040defc in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=<optimized out>, ap=<optimized out>)
    at /build/usr/src/debug/tarantool-1.7.4.372/src/fiber.h:644
#40 0x00000000004cde40 in fiber_loop (data=<optimized out>) at /build/usr/src/debug/tarantool-1.7.4.372/src/fiber.c:626
#41 0x00000000005b11df in coro_init () at /build/usr/src/debug/tarantool-1.7.4.372/third_party/coro/coro.c:110
```
