### ISSUE TITLE
show replication peer ip:port

### ISSUE THREAD

**Issue by whiteglasses** [tarantool/tarantool#2689]
```
box.info.replication
---
  replication:
    1:
      id: 1
      uuid: b8a7db60-745f-41b3-bf68-5fcce7a1e019
      lsn: 88
    2:
      id: 2
      uuid: cd3c7da2-a638-4c5d-ae63-e7767c3a6896
      lsn: 31
      upstream:
        status: follow
        idle: 43.187747001648
        lag: 0
      downstream:
     vclock: {1: 31}
    3:
      id: 3
      uuid: e38ef895-5804-43b9-81ac-9f2cd872b9c4
      lsn: 54
      upstream:
        status: follow
        idle: 43.187621831894
        lag: 2
      downstream:
        vclock: {1: 54}
```

Here i see only uuid of my replication peer. But i need to know ip address and port. Especially when i have multiple upsteams.

Please add fields like host and user (i want to check if i using coorrect username for replication)

```
    2:
      id: 2
      uuid: cd3c7da2-a638-4c5d-ae63-e7767c3a6896
      lsn: 31
      upstream:
        status: follow
        idle: 43.187747001648
        lag: 0
        host: 127.0.0.1:2324
        username: replicauser
      downstream:
     vclock: {1: 31}
```

**Comment by rtsisyk** [comment]
.peer

**Comment by rtsisyk** [comment]
1.7.6-64-g439102855

**Comment by rtsisyk** [comment]
```
tarantool> box.info.replication
---
- 1:
    id: 1
    uuid: cfcb8006-781b-4e2b-bbfb-c95594f15553
    lsn: 91208
    upstream:
      status: follow
      idle: 2.0781464660249
      peer: 127.0.0.1:3313
      lag: 0
  2:
    id: 2
    uuid: 21dbba9d-39cd-484c-b49a-b647710992df
    lsn: 0
...
```
