### ISSUE TITLE
duplicate fields in space despite unique index

### ISSUE THREAD

**Issue by iskandarov-egor** [tarantool/tarantool#2716]
my space "faces" has a unique index on two fields, but box.space.faces:pairs() reveals that there are some tuples with same values in these fields. any update() operation on some of these tuples causes a Duplicate key error, even if indexed fields are not being updated.

my space:
```
tarantool> box.space.faces
---
- index:
    0: &0
      unique: true
      parts:
      - type: string
        fieldno: 1
      id: 0
      space_id: 514
      options:
        page_size: 8192
        run_count_per_level: 2
        run_size_ratio: 3.5
        bloom_fpr: 0.05
        range_size: 1073741824
      name: primary
      type: TREE
    1: &1
      unique: true
      parts:
      - type: string
        fieldno: 2
      - type: unsigned
        fieldno: 6
      - type: unsigned
        fieldno: 5
      - type: string
        fieldno: 1
      id: 1
      space_id: 514
      options:
        page_size: 8192
        run_count_per_level: 2
        run_size_ratio: 3.5
        bloom_fpr: 0.05
        range_size: 1073741824
      name: user_hidden_count_id
      type: TREE
    2: &2
      unique: true
      parts:
      - type: string
        fieldno: 2
      - type: string
        fieldno: 3
      id: 2
      space_id: 514
      options:
        page_size: 8192
        run_count_per_level: 2
        run_size_ratio: 3.5
        bloom_fpr: 0.05
        range_size: 1073741824
      name: user_face
      type: TREE
    user_face: *2
    user_hidden_count_id: *1
    primary: *0
  on_replace: 'function: 0x40738450'
  temporary: false
  id: 514
  engine: vinyl
  enabled: true
  name: faces
  field_count: 0
...

tarantool>
```

code that causes the error:
```
for _, face in box.space.faces:pairs() do
	box.space.faces:update(face[1], {{'=', 5, 123123}})
end
```

xlogs and snapshots will be provided in person
