### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by gekpp** [tarantool/tarantool#2749]
I've been in tarantool-console for a long time and do nothing. I've got an error
> unix/:/var/run/tarantool/tarantool.sock> Segmentation fault
Current time: 1504851679
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed,
this may fail as well
#0  0x21e7c8cd49 in print_backtrace+9
#1  0x21e7bc1619 in _ZL12sig_fatal_cbi+89
#2  0x7f4643d5ee07 in sigwaitinfo+8
#3  0x21e7d65c1b in ev_invoke_pending+5b
#4  0x21e7d6917f in ev_run+89f
#5  0x21e7c79d1e in tarantool_lua_run_script+8e
#6  0x21e7bc074f in main+43f
#7  0x7f4643d36950 in __libc_start_main+36

OS:
>% uname -a
Darwin MacBook-Pro.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

**Comment by rtsisyk** [comment]
Hi, please paste your tarantool version. 
Thanks!

**Comment by gekpp** [comment]
```
- version: 1.7.5-0-g24b70de10
  id: 1
  ro: false
  vclock: {1: 12}
  uptime: 170672
  lsn: 12
  vinyl: []
  cluster:
    uuid: e547a080-f3b0-465e-b99a-5d2e9263fa2b
  pid: 1
  status: running
  signature: 12
  replication:
    1:
      id: 1
      uuid: 2b518fea-d629-4f9c-b2e8-1cb43e826f70
      lsn: 12
  uuid: 2b518fea-d629-4f9c-b2e8-1cb43e826f70
```
