### ISSUE TITLE
Broken snapshots and master-master replication fails

### ISSUE THREAD

**Issue by zloidemon** [tarantool/tarantool#2825]
When my one node in cluster lost free space on disk (example), I got an error with "can't save snapshot to disk" (unfortunatly terminal history's gone, can't copy output to the issue.

ENV
```
CentOS 7
> box.info.version
---
- 1.7.5-126-g223c626
...
```

Output from working server:
```
      id: 1
      uuid: c08433ac-5d7f-4c80-8864-286b4d5d5887
      lsn: 6564494
      upstream:
        status: stopped
        idle: 1199845.7135869
        message: 'Missing .xlog file between LSN 206433835 {1: 6564494, 2: 199869341}
          and 206433836 {1: 6564494, 2: 199869342}'
        lag: 1506607952.349
```

After cleanup the disk space and remove or remove snapshot, i tried to restart tarantool to bootstrap new master-master replica. In this case I the logs output like this:
```
2017-10-12 14:20:45.669 [11447] main/105/applier/replicator@ memtx_space.cc:276 E> rollback: Tuple field 6 type does not match one required by operation: expected string
2017-10-12 14:20:45.669 [11447] main/105/applier/replicator@ I> can't read row
```
That log output hasn't info about which space is broken, not enough info to solve issue.

This server is not so critical server of business part, It can stop and run both master nodes. I restarted tarantool on second server (the last server) with disabled master-master replication. It can not run even from snapshot. I see the last error above on both nodes without replication. Snapshot is corrupt and not possible to restore nodes by master-master bootstrap and snapshot.

I seem you have to make option to force startup by broken snapshot and skip corrupt rows and than replicate that to another node. Or some handler with questions on startup skip/solve the issue like `fsck` while checking broken blocks on hdd.

**Comment by locker** [comment]
@zloidemon Please post the tarantool version you use (including git commit hash).
Did you update tarantool (on master or slave) before trying to bootstrap the new replica?
It would also be helpful if you could attach tarantool log from both servers and the new replica.

**Comment by zloidemon** [comment]
@locker I didn't try to update, because tarantool had an issue with schema after adding new features and drivers can not load schema from the server. I still stay on that version to that deploy. @rtsisyk knows that issues with clients and fixed.

UPDATE:

You can reproduce issue if you configure tarantool with small amount of memory. Example might contain 2 M<-> tarantools and memory limit to memtx to 100mb or less. You must write data to two nodes until memory reach limit and stats will show like that on both instances:

```
      id: 5
      uuid: de299ab3-826d-4b27-a53e-9adb4e269a4e
      lsn: 55535905
      upstream:
        status: follow
        idle: 386303.5813904
        message: Failed to allocate 290 bytes in slab allocator for memtx_tuple
        lag: 0.0074071884155273
      downstream:
        vclock: {2: 149079, 5: 55563085, 4: 11700190, 7: 6273930, 1: 149116, 8: 164,
          9: 16581740}
```

After you have to continue write to both tarantools and do snapshot in the same time.  (i actually have limit to 10 snapshots and save every 3600s). When you will see a lot snapshots and xlogs in dir, you have to shutdown one of the M<->M instances and increase limit of memory +100 mb as example, and run it. It will call issue like this:


```
    9:
      id: 9
      uuid: 21880fe5-fae6-4ff1-ae8d-4660f711b4fe
      lsn: 16581739
      upstream:
        status: stopped
        idle: 197.67536700703
        message: 'Missing .xlog file between LSN 91212953 {1: 149116, 2: 149079, 4:
          11700190, 5: 56358735, 7: 6273930, 8: 164, 9: 16581739} and 90423362 {1:
          149116, 2: 149079, 4: 11700190, 5: 55535904, 7: 6273930, 8: 164, 9: 16614979}'
```

Not possible to fix without removing all snashots from one node and boostrap from scratch new one node. I have more info from tarantool channel to test [option](https://tarantool.org/en/doc/1.7/reference/configuration/index.html?highlight=lsn#cfg-binary-logging-snapshots-force-recovery) in this case. If i'll get the issue again i check new option to resolve my troubles with replication.
