### ISSUE TITLE
box.stat.net() misses fields described in 1.7 docs

### ISSUE THREAD

**Issue by narqo** [tarantool/tarantool#2830]
The documents for 1.7's `box.stat` submodule [stated][1] that `box.stat.net()` returns the following statistic

```
tarantool> box.stat.net()
---
- SENT:
    total: 0
    rps: 0
  EVENTS:
    total: 2
    rps: 0
  LOCKS:
    total: 6
    rps: 0
  RECEIVED:
    total: 0
    rps: 0
```

I haven't found any notices about changes in `box.stat` API in 1.7, but it seems that the response of the submodule has been changed. Currently, tarantool does not return `EVENTS` and `LOCKS` fields:

```
% docker run --rm -ti tarantool/tarantool:1.7
tarantool> box.stat.net()
---
- SENT:
    total: 0
    rps: 0
  RECEIVED:
    total: 0
    rps: 0
...
```

The change led to a small but not unexpected failure in one of our lua module, so I guess it'd be worth it to add a note to the changelog and docs.

[1]: https://tarantool.org/en/doc/1.7/book/box/box_stat.html
