### ISSUE TITLE
vinyl: statistics is broken

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#2861]
```
box.cfg{}
box.schema.space.create('test', {engine='vinyl'})
box.space.test:create_index('pk', {sequence=true})
fiber = require('fiber')
function foo() while true do box.space.test:insert{nil, fiber.time()} fiber.sleep(0.01) end end
fiber.create(foo)
```

Then try box.info.vinyl():

    tx_ops:
      total: 913312164573
      rps: 1310162910

Other statistics is also crazy.

Here's the full output from my laptop:
```
- lsn: 1553
  performance:
    cursor:
      total: 0
      rps: 0
    txv_allocated: 0
    tx_write:
      total: 134814
      rps: 7636
    dump_bandwidth: 10000000
    cache:
      used: 0
      count: 0
    cursor_ops:
      total: 0
      rps: 0
    read_view: 0
    tx:
      total: 1548
      rps: 96
    get:
      total: 1548
      rps: 96
    tx_allocated: 0
    read_interval: 0
    tx_ops:
      total: 913312164573
      rps: 1310162910
  memory:
    ratio: 0%
    limit: 134217728
    watermark: 134159207
    used: 134814
  tx:
    conflict: 0
    active: 0
    commit: 1548
    rollback: 0
```
