### ISSUE TITLE
Something weird with space format and nulls:

### ISSUE THREAD

**Issue by aensidhe** [tarantool/tarantool#2918]
I have a space with 4 fields and one index on first field:
```
unix/:/var/run/tarantool/tarantool.sock> box.space.channels
---
- index:
    0: &0
      unique: true
      parts:
      - type: unsigned
        is_nullable: false
        fieldno: 1
      sequence_id: 2
      id: 0
      space_id: 513
      name: primary
      type: TREE
    primary: *0
  on_replace: 'function: 0x40bf2180'
  temporary: false
  id: 513
  engine: memtx
  enabled: true
  name: channels
  field_count: 0

unix/:/var/run/tarantool/tarantool.sock> box.space.channels:format()
---
- [{'name': 'id', 'type': 'unsigned'}, {'name': 'name', 'type': 'string'}, {'name': 'deleted_utc',
    'type': 'scalar'}, {'name': 'is_private', 'type': 'boolean'}]
...
```

When I try to insert a tuple with a null in third element of tuple, I got an error:
```
unix/:/var/run/tarantool/tarantool.sock> null = require("msgpack").NULL
unix/:/var/run/tarantool/tarantool.sock> box.space.channels:insert{
                                       > null,
                                       > "123123123",
                                       > null,
                                       > false}
---
- error: 'Tuple field 3 type does not match one required by operation: expected scalar'
...
```

Version:
```
unix/:/var/run/tarantool/tarantool.sock> box.info
---
- version: 1.7.6-7-gce1a377
  id: 1
  ro: false
  vclock: {1: 19}
  uptime: 364
  lsn: 19
  vinyl: []
  cluster:
    uuid: 25d4d3bb-b2f5-473e-bbf7-801b87b6e991
  pid: 1
  status: running
  signature: 19
  replication:
    1:
      id: 1
      uuid: ce797faa-319a-4713-ada4-251ab1697019
      lsn: 19
  uuid: ce797faa-319a-4713-ada4-251ab1697019
...
```
