### ISSUE TITLE
Doesn't work force_recovery (master-master)

### ISSUE THREAD

**Issue by zloidemon** [tarantool/tarantool#2940]
After upgrade to latest version with replication fixes #2825. That issue didn't fixed, we have now both nodes in master-master:

```
- version: 1.7.6-7-gce1a377
  id: 3
  ro: false
  vclock: {1: 47341069, 2: 4421214, 3: 678218}
  uptime: 435481
  lsn: 678218
  vinyl: []
  cluster:
    uuid: 5117887b-16b7-42f0-9712-4b48735aa3f7
  pid: 21349
  status: running
  signature: 52440501
  replication:
    1:
      id: 1
      uuid: 9468d440-b5d7-4fb6-80f0-ab7e58e0af19
      lsn: 47341069
      upstream:
        status: stopped
        idle: 435039.9540113
        message: 'Missing .xlog file between LSN 51762606 {1: 47341069, 2: 4421214,
          3: 323} and 52262504 {1: 47840611, 2: 4421214, 3: 679}'
        lag: 1510908416.4887
      downstream:
        vclock: {1: 55321930, 2: 4421214, 3: 678218}
    2:
      id: 2
      uuid: 83cd64e4-43b4-4d29-9931-8ee18e4c1efd
      lsn: 4421214
    3:
      id: 3
      uuid: 8f7aeb44-5ade-41c7-830b-3ca310c72790
      lsn: 678218
  uuid: 8f7aeb44-5ade-41c7-830b-3ca310c72790
```

After apply `force_recovery` we got that

```
replication:
    1:
      id: 1
      uuid: 9468d440-b5d7-4fb6-80f0-ab7e58e0af19
      lsn: 47820380
      upstream:
        status: stopped
        idle: 85.411500473507
        message: Invalid MsgPack - packet length
        lag: 436159.434376
```

Logs:

```
2017-11-22 12:56:11.227 [16825] main/106/applier/replicator@ I> failed to authenticate
2017-11-22 12:56:11.227 [16825] main/106/applier/replicator@ xrow_io.cc:48 E> ER_INVALID_MSGPACK: Invalid MsgPack - packet length
```

We solved issue with boostrap new replica after remove all dumps and rollback to old snapshot.
