### ISSUE TITLE
replication: insane lag after reconnect

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#2965]
Branch 1.7 commit 4e960f7f9b031eb6f66ec380e8975b92fc4a2d7f

After a replica reconnects to a master (e.g. due to network issues), `box.info.replication` shows an incredible value of the replication lag. The value is reset back to normal when more data are received from the master.

Steps to reproduce:

1. Setup a master and a replica.
2. Suspend the replica process by pressing Ctrl-Z and wait until the master exits the relay loop:
```
2017-11-28 13:54:34.218 [14963] relay/127.0.0.1:39864/101/main C> exiting the relay loop
```
3. Resume the replica process (`fg`). Wait until it reconnects:
```
2017-11-28 13:55:01.343 [14969] main/104/applier/ I> can't read row
2017-11-28 13:55:01.343 [14969] main/104/applier/ xrow.c:776 E> ER_SYSTEM: timed out
2017-11-28 13:55:02.344 [14969] main/104/applier/ I> authenticated
```
4. Check out `box.info.replication` on the replica:
```
---
- 1:
    id: 1
    uuid: 72bb0d1f-49a2-45e0-ab59-342a804936e0
    lsn: 7
    upstream:
      status: follow
      idle: 75.950533088995
      lag: 1511866501.3431
  2:
    id: 2
    uuid: e64002bf-652e-45f2-9271-437969445e0b
    lsn: 0
...
```
