### ISSUE TITLE
Lua API to create box.error() objects without throwing them

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#3031]
Current it is not possible to create box.error() (`struct error`) objects without throwing them. Let's bind box_error_new() C API to Lua.

**Comment by Gerold103** [comment]
@TarantoolBot document
Title: box.error.new() - create an error object with no throw
`box.error.new(error_code, args)` - the way to create an error object and do not throw it, but just return as the simple object. It is useful when an error object must be saved to be got later, for example.
``` YAML
tarantool> e = box.error.new(box.error.CREATE_SPACE, "space", "error")
tarantool> e
---
- 'Failed to create space ''space'': error'
...
tarantool> e:unpack()
---
- type: ClientError
  code: 9
  message: 'Failed to create space ''space'': error'
  trace:
  - file: '[string "e = box.error.new(box.error.CREATE_SPACE, "sp..."]'
    line: 1
...
```
