### ISSUE TITLE
vinyl: ignore quota timeout on replication

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#3087]
If vinyl fails to do memory dumps in time on a replica (e.g. it ran out of disk space), replication will stop forever with an error:
```
replication:
    1:
      id: 1
      uuid: 4931d16d-1789-4778-9e4b-7d425a7d0141
      lsn: 104065559
      upstream:
        status: stopped
        idle: 3188.8436139524
        message: Timed out waiting for Vinyl memory quota
        lag: 61309.644038439
      downstream:
        vclock: {1: 1240345745}
```
And the admin will have to call box.cfg() to restart replication.

Since replication is asynchronous anyway, we shouldn't stop it on vinyl timeout - it isn't critical as the replica will recover as soon as the admin fixes the problem. That said, let's ignore vinyl timeout altogether for applier fibers (currently we ignore it only on join) - the admin can monitor how badly replica lags behind via box.info.replication lag/idle.

See also #2873
