### ISSUE TITLE
Delete from _cluster table does not update replicaset vclock

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#3109]
When deleting a component from cluster table,  replicaset_vclock is not updated, so box.info.replication keeps showing trash:
```
unix/:/var/run/tarantool/notify_instance_008.control> box.space._cluster:select()
---
- - [3, '2fe3e965-c113-49a7-9d0a-ab856a62f543']
  - [5, 'a07a2328-235e-4493-965d-ba20089addee']
...
unix/:/var/run/tarantool/notify_instance_008.control> box.info
---
- version: 1.7.6-12-g2db448b
  id: 3
  ro: false
  vclock: {1: 3054773, 4: 8938828, 3: 285902018}
  uptime: 2329
  lsn: 285902018
  vinyl: []
  cluster:
    uuid: 49f2dc58-e300-4bdf-bd9e-81404c7bd14d
  pid: 1569792
  status: running
  signature: 297895619
  replication:
    5:
      id: 5
      uuid: a07a2328-235e-4493-965d-ba20089addee
      lsn: 0
      downstream:
        vclock: {1: 3054773, 4: 8938827, 3: 285902018}
    3:
      id: 3
      uuid: 2fe3e965-c113-49a7-9d0a-ab856a62f543
      lsn: 285902018
  uuid: 2fe3e965-c113-49a7-9d0a-ab856a62f543
...
```

Server restart doesn't help. Snapshot doesn't help. (Please keep in mind when adding test coverage, please test that restart/snapshot doesn't make the problem worse).

What's worse, box.cfg.replication shows entries for pruned replicas forever. This is confusing, I am only interested in connected replicas or replicas from box.cfg.

This is not a bug apparently, it works as intended, so needs to be documented.
