### ISSUE TITLE
net.box: space index parts do not contain `is_nullable` and `collation` options

### ISSUE THREAD

**Issue by opomuc** [tarantool/tarantool#3256]
```
localhost:3303> b = require('net.box').new('localhost:3303')
localhost:3303> b.space['user']
---
- &0
  engine: memtx
  field_count: 0
  connection:
    peer_uuid: 13fdd588-66cc-4306-9f94-779a0447724d
    opts:
      user: tester
    host: localhost
    schema_version: 120
    protocol: Binary
    state: active
    peer_version_id: 67840
    port: '3303'
  temporary: false
  index:
    0: &1
      unique: false
      parts:
      - type: string
        fieldno: 1
      id: 0
      type: TREE
      name: primary
      space: *0
    1: &2
      unique: false
      parts:
      - type: unsigned
        fieldno: 6
      - type: unsigned
        fieldno: 8
      id: 1
      type: TREE
      name: i1
      space: *0
    primary: *1
    i1: *2
  enabled: true
  name: user
  _format: []
  id: 523
```
