### ISSUE TITLE
No object collation updates with alter operation

### ISSUE THREAD

**Issue by kshcherbatov** [tarantool/tarantool#3285]
Steps to reproduce:
```Lua
space = box.schema.create_space('test')
box.internal.collation.create('test', 'ICU', 'ru-RU')
i1 = space:create_index('i1', { type = 'tree', parts = {{1, 'str'}}, unique = true })
i1:alter({parts = {{1, 'str', collation='test'}}})
i1
```

Expected:
```
unique: true
parts:
    type: string
    is_nullable: false
    collation: test
    fieldno: 1
    id: 0
    space_id: 567
    name: sk
    type: TREE
```

Result:
```
unique: true
parts:
    type: string
    is_nullable: false
    fieldno: 1
    id: 0
    space_id: 567
    name: sk
    type: TREE
```
**i.e. no collation**
