### ISSUE TITLE
track in _cluster table hostname and time of last login

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#3363]
to be able to easier prune dead replicas, track in _cluster table hostname, vclock and time of last login.
Dead replicas will be more clearly visible 'cause it's a lot behind the master - in time, in vclock, and it's clearly visible which host it's come from , so we can prune all dead replicas from a given host.

**Comment by Mons** [comment]
If hostname means ip+port, then ok )

**Comment by IlyaMarkovMipt** [comment]
@kostja Tracking times and vclocks in space _cluster may cause conflicts during replication of this space. Moreover, updates on replica will cause not only applying the updates, but also updates in _cluster table. Why can't we store this information in box.info.replication?

As far as I understand, this issue relates to #3110 and current implementation of that ticket highly relies on box.info.replication.

**Comment by sergos** [comment]
The problem is box.info.replication contains the following after replica disconnection:
```
- 1:
    id: 1
    uuid: 26a2fafa-2d80-490b-b791-bbd6a035145e
    lsn: 9
    upstream:
      peer: replicator@localhost:3302
      lag: 0.00012969970703125
      status: disconnected
      idle: 4.3349569998682
      message: connect, called on fd 15, aka 127.0.0.1:62507
      system_message: Connection refused
    downstream:
      status: stopped
      message: unexpected EOF when reading from socket, called on fd 16, aka [::1]:3301,
        peer of [::1]:62482
      system_message: Broken pipe
```
and after restart of the instance
```
- 1:
    id: 1
    uuid: 26a2fafa-2d80-490b-b791-bbd6a035145e
    lsn: 9
```

A disconnect trigger can be introduced similar to https://www.tarantool.io/en/doc/2.3/book/box/triggers/ already available. By default we can store the last value in system space, while user will have options to keep log of some size to understand behavior of the cluster.
