### ISSUE TITLE
primary index alter don't work on already unique fields

### ISSUE THREAD

**Issue by donmikel** [tarantool/tarantool#3582]
We have space with primary index:
```
0: &0
      unique: true
      parts:
      - type: unsigned
        is_nullable: false
        fieldno: 1
      sequence_id: 1
      id: 0
      space_id: 512
      name: primary
      type: TREE
```
and secondary unique:
```
3: &2
      unique: true
      parts:
      - type: unsigned
        is_nullable: false
        fieldno: 2
      - type: unsigned
        is_nullable: false
        fieldno: 4
      id: 3
      space_id: 512
      name: wbuser_chrt
      type: TREE
```
then we trying to aleter primary index:
`box.space.poned_good.index.primary:alter({sequence = false, unique = true, parts = {2, 'unsigned', 4, 'unsigned'}})`

and we got:
`error: Duplicate key exists in unique index 'primary' in space 'poned_good'`

snap of instance to reproduce sended to @kyukhin via google drive
