### ISSUE TITLE
tarantoolctl fails to parse request without body

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#3675]
Affected releases: 1.10, 2.0

If `space.before_replace` returns the old tuple, the operation turns into a no-op. For the sake of replication we will still write it to WAL as `IPROTO_NOP`. Such a request doesn't have a body. An attempt to parse it with `tarantoolctl cat` leads to an error:
```
tarantoolctl:819: attempt to index field 'BODY' (a nil value)
```
Steps to reproduce:
1. Run the following script in a clean directory:
```box.cfg{}
s = box.schema.space.create('test')
s:create_index('pk')
s:replace{1, 1}
s:before_replace(function(old, new) return old end)
s:replace{1, 2}
os.exit(0)
```
2. Try to read the xlog file created by the script with `tarantoolctl cat`:
```
Processing file '00000000000000000000.xlog'
---
HEADER:
  lsn: 4
  replica_id: 1
  type: REPLACE
  timestamp: 1536597405.2526
BODY:
  space_id: 512
  tuple: [1, 1]
/home/vlad/bin/tarantoolctl:819: attempt to index field 'BODY' (a nil value)
```
