### ISSUE TITLE
space.before_replace trigger corrupts xlog

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#3678]
Affected releases: 1.10, 2.0

The issue was reproduced on Tarantool 1.10.1-367-g0a3186c4

Steps to reproduce:

Run the following script:
```
box.cfg{}
s = box.schema.space.create('test')
s:create_index('pk')
s:replace{1, 1}
f = function(old, new) return old end
box.begin()
s:before_replace(f)
s:replace{1, 2}
s:before_replace(nil, f)
s:replace{1, 3}
box.commit()
os.exit(0)
```
Then take a look at the generated xlog (you need to fix #3675 first):
```
Processing file '00000000000000000000.xlog'
---
HEADER:
  lsn: 4
  replica_id: 1
  type: REPLACE
  timestamp: 1536656270.5091
BODY:
  space_id: 512
  tuple: [1, 1]
---
HEADER:
  lsn: 5
  replica_id: 1
  type: NOP
  timestamp: 1536656270.5092
BODY:
  type: 3
  timestamp: 1536656270.5092
  lsn: 6
  replica_id: 1
---
HEADER:
  type: 0
...
```
It looks corrupted: a request body can't have lsn or replica_id. You can recover from it, but the space will contain `{1, 1}` instead of `{1, 3}`.
