### ISSUE TITLE
replication crash under high CPU and IO load

### ISSUE THREAD

**Issue by R-omk** [tarantool/tarantool#3718]
Replication  can  stopped 
with box.info.replication
`status: stopped`
and
```
message: Invalid MsgPack - packet body
message: Invalid MsgPack - packet header
message: Missing mandatory field 'tuple' in request
```

How to reproduce and more detail
https://gist.github.com/R-omk/163950ced360dd3321ef5acc9a0053ed#gistcomment-2723867

broken state example
```

unix/:/var/run/tarantool/tarantool.sock> box.info
---
- version: 1.9.2-0-g113ade24e
  id: 1
  ro: false
  vinyl: []
  vclock: {1: 1140433, 2: 682413, 3: 289836}
  uptime: 84
  lsn: 1140433
  memory: []
  cluster:
    uuid: 7b853d13-508b-4b8e-82e6-806f088ea6e9
  pid: 1
  status: running
  signature: 2112682
  replication:
    1:
      id: 1
      uuid: 037fec43-18a9-4e12-a684-a42b716fcd01
      lsn: 1140433
    2:
      id: 2
      uuid: 037fec43-18a9-4e12-a684-a42b716fcd02
      lsn: 682413
      upstream:
        peer: master@tarantool2:3301
        lag: 5.3919904485573e+67
        status: stopped
        idle: 23.581829273026
        message: Invalid MsgPack - packet body
      downstream:
        vclock: {1: 780469, 2: 962664, 3: 289836}
    3:
      id: 3
      uuid: 037fec43-18a9-4e12-a684-a42b716fcd03
      lsn: 289836
      upstream:
        peer: master@tarantool3:3301
        lag: 8.632523059845
        status: stopped
        idle: 47.460358217009
        message: Invalid MsgPack - packet header
      downstream:
        vclock: {1: 1075597, 2: 1134262, 3: 864677}
  uuid: 037fec43-18a9-4e12-a684-a42b716fcd01
```
