### ISSUE TITLE
tarantoolctl cat --to= can't find existing lsn in xlog (replication)

### ISSUE THREAD

**Issue by vasilky3** [tarantool/tarantool#3827]
https://github.com/tarantool/tarantool/blob/6ca97fd5ac0ef287c4ed543a3553c147ea6e4c39/extra/dist/tarantoolctl.in#L847
**Проблема:**
Tarantoolctl cat --from=10031 --to=10032 [file.xlog] не находит существующую в xlog запись 
```
HEADER:
  lsn: 10031
  replica_id: 1
  type: UPSERT
  timestamp: 1542302285.4273
```
Поскольку выходит по break найдя
```
HEADER:
  lsn: 3670386
  replica_id: 3
  type: UPSERT
  timestamp: 1542302268.3706
```
**Пример поведения:**
```
[vasilii@srv7-lesillon db]$ tarantoolctl cat 00000000000003709698.xlog | grep -B 2 -A 12 "lsn: 10031"
Processing file '00000000000003709698.xlog'
---
HEADER:
  lsn: 10031
  replica_id: 1
  type: UPSERT
  timestamp: 1542302285.4273
BODY:
  space_id: 512
  operations: [['=', 3, ''], ['=', 4,
      true], ['=', 5, true], ['=', 6, true], ['=', 7, 1803888733], ['=', 8, 1542302285426865475]]
  index_base: 1
  tuple: ['',
    '', '', true, true, true, 1803888733,
    1542302285426865475, false]
---
[vasilii@srv7-lesillon db]$ tarantoolctl cat --from=10031 --to=10032 00000000000003709698.xlog
Processing file '00000000000003709698.xlog'
[vasilii@srv7-lesillon db]$
```
