### ISSUE TITLE
sql: optimizer ignores index in LIKE statement

### ISSUE THREAD

**Issue by opomuc** [tarantool/tarantool#3889]
```
box.sql.execute("create table t2(id int primary key, a varchar(36), b int)")
---
...
for i=1,1000000 do
   box.space.T2:insert({i,uuid.str(),i+100})
end
---
...
test("select id,a from t2 where a like 'ab%'")
---
- 0.25214530003723
...
box.sql.execute("explain query plan select id,a from t2 where a like 'ab%'")
---
- - [0, 0, 0, 'SCAN TABLE T2']
...
box.sql.execute("create index i1 on t2(a)")
---
...
test("select id,a from t2 where a like 'ab%'")
---
- 0.26176150003448
...
box.sql.execute("explain query plan select id,a from t2 where a like 'ab%'")
---
- - [0, 0, 0, 'SCAN TABLE T2']
...
box.sql.execute("explain select id,a from t2 where a like 'ab%'")
---
- - [0, 'Init', 0, 11, 0, '', '00', null]
  - [1, 'IteratorOpen', 1, 0, 0, 'space<name=T2>', '00', null]
  - [2, 'Rewind', 1, 10, 1, '0', '00', null]
  - [3, 'Column', 1, 1, 3, '', '00', null]
  - [4, 'Function0', 1, 2, 1, 'like(2)', '02', null]
  - [5, 'IfNot', 1, 9, 1, '', '00', null]
  - [6, 'Column', 1, 0, 4, '', '00', null]
  - [7, 'Column', 1, 1, 5, '', '00', null]
  - [8, 'ResultRow', 4, 2, 0, '', '00', null]
  - [9, 'Next', 1, 3, 0, '', '01', null]
  - [10, 'Halt', 0, 0, 0, '', '00', null]
  - [11, 'String8', 0, 2, 0, 'ab%', '00', null]
  - [12, 'Goto', 0, 1, 0, '', '00', null]
...

```

**Comment by Korablev77** [comment]
It is fixed on master branch:
```
tarantool> box.execute("explain query plan select id,a from t2 where a like 'ab%'")
---
- metadata:
  - name: selectid
    type: INTEGER
  - name: order
    type: INTEGER
  - name: from
    type: INTEGER
  - name: detail
    type: TEXT
  rows:
  - [0, 0, 0, 'SEARCH TABLE T2 USING COVERING INDEX I1 (A>? AND A<?) (~16384 rows)']
...

```
LIKE operation is substituted with pair of inequalities: a >= 'ab' AND a < 'ac'. Note that such optimization currently available (i.e. involving index search) only for fields featuring default (that is none), binary or "unicode_ci" collations.
