### ISSUE TITLE
Downstream status doesn't show up in replication.info unless the channel is broken

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#3904]
**Tarantool version:**
1.10, 2.1
(in 1.9 there was no such thing as `downstream.status`)

**OS version:**
Any

**Bug description:**
When a relay is stopped, its `downstream.status` is set to `stopped`, but when it's active, its `downstream.status` is set to `nil`. This is confusing and inconsistent with `upstream.status` behavior, which is always valid.

**Steps to reproduce:**
Start master-master replication and check out `box.info.replication` on one of the participating instances:
```
---
- 1:
    id: 1
    uuid: 4f78e200-6bd7-4817-a15d-95d10410b286
    lsn: 1
  2:
    id: 2
    uuid: dac1b3e5-2776-40a6-9d8e-1f7cbfca89f9
    lsn: 0
    upstream:
      status: follow
      idle: 0.9805296909999
      peer:
      lag: 9.7990036010742e-05
    downstream:
      vclock: {1: 1}
...
```
Note, there's no `downstream.status`. Now stop the other instance and check `box.info.replication` again:
```
---
- 1:
    id: 1
    uuid: 4f78e200-6bd7-4817-a15d-95d10410b286
    lsn: 1
  2:
    id: 2
    uuid: dac1b3e5-2776-40a6-9d8e-1f7cbfca89f9
    lsn: 0
    upstream:
      peer:
      lag: 0.00014448165893555
      status: disconnected
      idle: 2.1303209229991
      message: connect, called on fd 13, aka [::1]:60796
    downstream:
      status: stopped
      message: unexpected EOF when reading from socket, called on fd 13, aka 127.0.0.1:57916,
        peer of 127.0.0.1:37928
...
```
Note, `downstream.status` equals `stopped`.

**Optional (but very desirable):**
`downstream.status` was introduced in commit 3db1dee962d4922605794087c6f93d2c4cc9a4b4. For some reason, the commit sets the status only if the channel is broken.
