### ISSUE TITLE
fiber.join() blocks in 'suspended' if fiber has cancelled 

### ISSUE THREAD

**Issue by arthur-barsegyan** [tarantool/tarantool#3948]
**Bug description:** This code leads to "func" fiber remains in a 'suspended' state even after the expected fiber (another_func) has ended.
 
```
local fiber = require('fiber')

local tasks = {}

function start(func, name)
    local worker = fiber.create(function()
        local ok, _ = pcall(func)
        fiber.testcancel()
    end)

    tasks[name] = worker
end

function sync_stop(name)
    tasks[name]:cancel()
    while tasks[name] and tasks[name]:status() ~= 'dead' do
        fiber.sleep(1)
    end
end

function another_func()
    fiber.yield()
end

function func()
    local fib = fiber.create(another_func)
    fib:set_joinable(true)
    fib:join()
end

start(func, "test_worker")
sync_stop("test_worker")
```

**Tarantool version:**  2.1.1-185-gf583b6c82
**OS version:** macOS 10.14.1

**fiber.info() print grep for 'suspended' fiber:**
```
102:
  csw: 3
  backtrace:
  - C: '#0  0x10e6f5acb in lbox_fiber_join+40'
  - L: join in =[C] at line -1
  - L: (unnamed) in @fiber_bug.lua at line 30
  - C: '#1  0x10e71f595 in lj_BC_FUNCC+68'
  - C: '#2  0x10e72f70f in lua_pcall+155'
  - C: '#3  0x10e6f9b79 in luaT_call+19'
  - C: '#4  0x10e6f6693 in lua_fiber_run_f+87'
  - C: '#5  0x10e64f416 in fiber_cxx_invoke(int (*)(__va_list_tag*), __va_list_tag*)+12'
  - C: '#6  0x10e7072f0 in fiber_loop+42'
  - C: '#7  0x10e826764 in coro_init+75'
  fid: 102
  memory:
    total: 57664
    used: 0
  name: lua 
```
