### ISSUE TITLE
Column names in values statements

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#3962]
I have Ubuntu 18.04. I have Tarantool 2.1, pulled from source today.

I execute this statement:
select "_auto_field_","_auto_field_1" from (values (5,6)) as x;
It works -- but why are the columns named "_auto_field_" etc.?

If I execute this statement:
select "5","6" from (select 5,6) as x;
It works -- so in that statement the names are based on the values.

In MariaDB (not MySQL) I can say
values (5,6);
and the names are based on the values.

In PostgreSQL the names would be column1, column 2, etc.
https://www.postgresql.org/docs/8.2/sql-values.html

In standard SQL  "The column names are implementation-dependent."
So we can do whatever we like, but this is a feature request to
ensure column names are consistent, unique, and printable.
Keep in mind that someday we might support
values (5,6) ,(7,8) order by column-name.

**Comment by romanhabibov** [comment]
Now, after
```
tarantool> SELECT 1+1, 1+1
---
- metadata:
  - name: 1+1
    type: integer
  - name: 1+1
    type: integer
  rows:
  - [2, 2]
...
```
column names are based on expressions and they aren't unique.

After
```
tarantool> SELECT * FROM (VALUES (1+1, 1+1))
---
- metadata:
  - name: _auto_field_
    type: integer
  - name: _auto_field_1
    type: integer
  rows:
  - [2, 2]
...
```
column names are formed with the template '_auto_field_N' and they are unique.

As I understood, we think it is OK.

**Comment by kyukhin** [comment]
> As I understood, we think it is OK.

Yes, we do. Please, proceed w/ a patch.

**Comment by romanhabibov** [comment]
There is just different naming, when you use/don't use VALUES:
```
tarantool> SELECT 10, 1+1
---
- metadata:
  - name: '10'
    type: integer
  - name: 1+1
    type: integer
  rows:
  - [10, 2]
...

tarantool> SELECT * FROM (VALUES (10,1+1))
---
- metadata:
  - name: _auto_field_
    type: integer
  - name: _auto_field_1
    type: integer
  rows:
  - [10, 2]
...
```

**Comment by Totktonada** [comment]
@pgulutzan Peter, are you see an area for improvement considering current way to expose result set column names? If so, how exactly you propose to modify current behaviour?

**Comment by pgulutzan** [comment]
@Toktonada, The decision is "won't fix", I accept that, this is only a comment.

Somebody has changed the way that VALUES works.
Today I do not see "_auto_field_" plus ordinal, I see "column" plus ordinal.
That is, for VALUES (1,'1',1+1) the column names are: column1 column2 column3.
I do not like this because ...
CREATE VIEW v1 AS VALUES (1,'1',1+1);
SELECT column1, column2, column3 FROM v1;
... fails. Instead, I have to say
SELECT "column1", "column2", "column3" FROM v1;
This would be easy to avoid: let the name be "COLUMN" plus ordinal,
not "column" plus ordinal.

Nobody has changed the way that SELECT works.
That is, for SELECT 1,'1',1+1 the column names are: 1, '1', 1+1.
I do not like this because:
(a) The metadata display says the names are '1' '''1''' 1+1.
But of course if I made a view I could not use those exact names ...
CREATE VIEW v2 AS SELECT 1,'1',1+1;
SELECT '1', '''1''', 1+1 FROM v2; -- seems to work but misleads
SELECT "1", "'1'", "1+1" FROM v2; -- correct but is odd
The correct SELECT is odd because the first column name is
within single quotes, the third column is not within single quotes.
But the main problem is: what I see in metadata is not what I am
supposed to use.
(b) The names are not valid for regular identifiers, so again I
must enclose in double quotes.
(c) The results from SELECT are not the same as the results from
VALUES. (I do not understand what point @romanhabibov is making,
we know that the names are not the same, that is part of the problem
description.)

Therefore I would have favoured: for both VALUES and SELECT: COLUMN1, COLUMN2, COLUMN3, 
Exception: if the SELECT list contains a Cyrillic character in any of the expressions: КОЛУМН1 КОЛУМН2 КОЛУМН3.

**Comment by Totktonada** [comment]
Thanks for the explanation!

> The decision is "won't fix", I accept that, this is only a comment.

There was no decision. The only person whose position assumes responsibility for decisions in tarantool core development is Kirill Yukhin. He shares certain level of responsibility for Tarantool/SQL with Nikita Pettik. That is all: everything else is a personal opinion.

Roman, please, express your opinions in a less ambiguous manner.

> Exception: if the SELECT list contains a Cyrillic character in any of the expressions: КОЛУМН1 КОЛУМН2 КОЛУМН3.

Is it sarcasm?

> Therefore I would have favoured: for both VALUES and SELECT: COLUMN1, COLUMN2, COLUMN3.

I agree: this way make usage of views like you shown above simpler and less ambiguous (and also allows to differentiate columns with the same original expression). On the first glance we pay nothing for that, except, maybe, simplicity of determination of original expression during interactive SQL usage.

We have `span` field now (see https://github.com/tarantool/doc/issues/1049), which is declared as 'an original expression forming result set column'. So it seems logical to left an expression in `span` field and assign 'consistent, unique and printable' values for `name` field.

Now those fields do not work in this way:

```
tarantool> box.space._session_settings:update({'sql_full_metadata'}, {{'=', 'value', true}})
---
- ['sql_full_metadata', true]
...
tarantool> box.execute('VALUES (1, 2, 3)')
---
- metadata:
  - type: integer
    span: column1  !! should be '1'
    name: column1  !! okay (except lowercase)
  - type: integer
    span: column2  !! should be '2'
    name: column2  !! okay (except lowercase)
  - type: integer
    span: column3  !! should be '3'
    name: column3  !! okay (except lowercase)
  rows:
  - [1, 2, 3]
...

tarantool> box.execute('SELECT 1, 2, 3') 
---
- metadata:
  - type: integer
    span: '1'      !! okay
    name: '1'      !! should be COLUMN1
  - type: integer
    span: '2'      !! okay
    name: '2'      !! should be COLUMN2
  - type: integer
    span: '3'      !! okay
    name: '3'      !! should be COLUMN3
  rows:
  - [1, 2, 3]
...
```

I would cast @Korablev77 and @Gerold103 to this discussion.

**Comment by pgulutzan** [comment]
Re "Is it sarcasm": You're correct if you mean the suggestion can't be serious, but I was trying to acknowledge that maybe users wouldn't like a Latin-alphabet name if all the other names which they added explicitly were Cyrillic. I should also have acknowledged that there are ways to try to be pretty, e.g.: start with _, change all non-alphanumeric characters to _, make all alphabetic characters upper case, truncate if too long, then add column number. However, I thought that's too much trouble.

**Comment by rybakit** [comment]
Regardless of what naming format is eventually chosen, please make sure that it is applied everywhere, which is not the case at the moment:

```lua
box.execute([[ SELECT ?, ?, ? ]], {1, 2, 3})
---
- metadata:
  - name: '?'
    type: integer
  - name: '?'
    type: integer
  - name: '?'
    type: integer
  rows:
  - [1, 2, 3]
```
vs
```
box.execute([[ SELECT * FROM (VALUES (?, ?, ?)) ]], {1, 2, 3})
---
- metadata:
  - name: _auto_field_
    type: boolean
  - name: _auto_field_1
    type: boolean
  - name: _auto_field_2
    type: boolean
  rows:
  - [1, 2, 3]
```
*(Also note the `boolean` type in the second example, is it a bug?)*

> column names are formed with the template '_auto_field_N' and they are unique.

@romanhabibov To be precise, the current template is `_auto_field_[N]`. So *N* is omitted when it is a first column, which I don't like personally and would prefer `_auto_field_0`, `_auto_field_1`, ... instead.

>  Today I do not see "auto_field" plus ordinal, I see "column" plus ordinal.

I tend to agree with this sentiment. From my userland experience, it is common to say that the tuple consists of fields, but the table row contains columns.
