### ISSUE TITLE
sql: wrong type of addition string with integer

### ISSUE THREAD

**Issue by Korablev77** [tarantool/tarantool#4103]
```
tarantool> SELECT '9223372036854' + 0
- metadata:
  - name: '''9223372036854'' + 0'
    type: number
  rows:
  - [9223372036854]
...

```
As one can see, resulting value of this operation is integer. Nevertheless, type is number, which in turn is wrong.
