### ISSUE TITLE
Improve box.stat.net

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#4150]
Currently, `box.stat.net()` output looks like this:

```
---
- SENT:
    total: 20924179852
    rps: 2053286
  CONNECTIONS:
    current: 8
  RECEIVED:
    total: 127867376466
    rps: 12504060
...
```

For one thing, it's impossible to figure out how many requests are currently in flight while it would be useful for understanding whether `box.cfg.net_msg_max` needs to be increased. So I suggest to add `REQUESTS.current` to the output. Besides it would be nice to see how many requests are being processed per second so it might also be worthwhile to add `REQUESTS.rps` and `REQUESTS.total`. And for the stats not to look kinda lopsided after this, let's also add `CONNECTIONS.rps` and `CONNECTIONS.total` which would account the number of connections opened per second and the total number of connections that have ever been opened.

Anything else? Something to indicate that `box.cfg.readahead` needs to be increased, may be?
