### ISSUE TITLE
sql: length takes not-string values

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#4159]
```Lua
box.execute('SELECT LENGTH(5)')
```
returns
```YAML
---
- metadata:
  - name: LENGTH(5)
    type: integer
  rows:
  - [1]
...
```

But should raise and error, according to the standard.
