### ISSUE TITLE
Don't show idle fibers in fiber.info

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#4235]
Output of `fiber.info` from an instance that has been running for a while:
```Yaml
    name: main
  3965366:
    csw: 3502
    backtrace:
    - C: '#0  0x40efdc in fiber_cxx_invoke(int (*)(__va_list_tag*), __va_list_tag*)+12'
    - C: '#1  0x4f7e90 in fiber_loop+48'
    - C: '#2  0x6323bf in coro_init+63'
    fid: 3965366
    memory:
      total: 545104
      used: 23926
    name: main
  3965361:
    csw: 24319
    backtrace:
    - C: '#0  0x40efdc in fiber_cxx_invoke(int (*)(__va_list_tag*), __va_list_tag*)+12'
    - C: '#1  0x4f7e90 in fiber_loop+48'
    - C: '#2  0x6323bf in coro_init+63'
    fid: 3965361
    memory:
      total: 536912
      used: 15917
    name: main
  3974361:
    csw: 53165
    backtrace:
    - C: '#0  0x40efdc in fiber_cxx_invoke(int (*)(__va_list_tag*), __va_list_tag*)+12'
    - C: '#1  0x4f7e90 in fiber_loop+48'
    - C: '#2  0x6323bf in coro_init+63'
    fid: 3974361
    memory:
      total: 520528
      used: 0
    name: main
  3965362:
    csw: 4138
    backtrace:
    - C: '#0  0x40efdc in fiber_cxx_invoke(int (*)(__va_list_tag*), __va_list_tag*)+12'
    - C: '#1  0x4f7e90 in fiber_loop+48'
    - C: '#2  0x6323bf in coro_init+63'
    fid: 3965362
    memory:
      total: 541008
      used: 20066
    name: main
  3965372:
    csw: 616
    backtrace:
    - C: '#0  0x40efdc in fiber_cxx_invoke(int (*)(__va_list_tag*), __va_list_tag*)+12'
    - C: '#1  0x4f7e90 in fiber_loop+48'
    - C: '#2  0x6323bf in coro_init+63'
    fid: 3965372
    memory:
      total: 536912
      used: 15936
```
We need to filter out idle fiber stacks, because they only clutter the output.
