### ISSUE TITLE
'parts' argument format check in create_index()

### ISSUE THREAD

**Issue by bhmj** [tarantool/tarantool#4416]
Tarantool version: 1.9.2
OS version: Debian 9 (stretch)

#### Bug description:

The function `box.schema.create_space` in it's second argument receives a field called `parts` which can be passed in two different formats: **{num, type, num, type, ...}** or **{{num, type, named params}, {num, type, named_params}, ...}**. It is possible to pass this field as **{num, type, named_params}** by mistake. The function receives this invalid argument and creates an index, silently ignoring **named_params** without any errors as shown below.

My suggestion is to detect this kind of error and return an error message.

#### Steps to reproduce:
```
sp = box.schema.create_space('some_space', {if_not_exists = true})
sp:create_index('ci', {parts = {2, 'string', collation='unicode_ci'}})
---
- unique: true
  parts:
  - type: string
    is_nullable: false
    fieldno: 2
  id: 1
  space_id: 530
  name: ci
  type: TREE
```
#### Result: 
Index created without collation even though it was specified (or so I thought).
#### Expected: 
index created with collation OR error message.
