### ISSUE TITLE
Small bugs with BOOLEAN in SQL

### ISSUE THREAD

**Issue by ImeevMA** [tarantool/tarantool#4462]
Tarantool version: 2.3.0-77-ga850acf

OS version: Ubuntu 16.04

Bug description: Small bugs with type BOOLEAN.

Steps to reproduce:

1) Result of implicit cast from BOOLEAN to TEXT is not equal to the explicit one:
```
tarantool> SELECT GROUP_CONCAT(true), GROUP_CONCAT(CAST(true AS TEXT));
---
- metadata:
  - name: GROUP_CONCAT(true)
    type: string
  - name: GROUP_CONCAT(CAST(true AS TEXT))
    type: string
  rows:
  - ['true', 'TRUE']
...
```

2) The IN operator throws a "Type Mismatch" error when the right value is the result of a sub-select:
```
tarantool> SELECT true IN (1,2,3);
---
- metadata:
  - name: true IN (1,2,3)
    type: boolean
  rows:
  - [false]
...

tarantool> SELECT true IN (VALUES(1), (2), ('3'));
---
- null
- 'Type mismatch: can not convert UNSIGNED to BOOLEAN'
...
```
3) Function LENGTH() returns NULL when argument is BOOLEAN:
```
tarantool> SELECT length(true), length(false);
---
- metadata:
  - name: length(true)
    type: integer
  - name: length(false)
    type: integer
  rows:
  - [null, null]
...
```
