### ISSUE TITLE
SQL arithmetic types are broken

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#4470]
```YAML
tarantool> box.execute("CREATE TABLE t(a INTEGER PRIMARY KEY, c1 STRING, c2 INTEGER)")
---
- row_count: 1
...

tarantool> box.execute("SELECT 1 + '1.1'")
---
- metadata:
  - name: 1 + '1.1'
    type: integer
  rows:
  - [2.1]
...

tarantool> box.execute("INSERT INTO t VALUES (1, '1.1', 1)")
---
- row_count: 1
...

tarantool> box.execute("SELECT c2 + c1 FROM t")
---
- metadata:
  - name: c2 + c1
    type: integer
  rows:
  - [2.1]
...
```

In both cases I have a float value in an 'integer' column. I provided two examples to show, that both runtime and compile time type calculations are broken.
Function `sql_type_result` currently does not take strings into account. I think, that if a user tried to do an arithmetic operation with a string, result should be NUMBER always.

**Comment by Gerold103** [comment]
One another problem:
```YAML
tarantool> box.execute("SELECT 1 + ?;", {1.1})
---
- metadata:
  - name: 1 + ?
    type: integer
  rows:
  - [2.1]
...
```

**Comment by Gerold103** [comment]
And one another:
```YAML
tarantool> box.execute("CREATE TABLE t3(a NUMBER primary key);")
---
- row_count: 1
...

tarantool> box.execute("SELECT sum(a), typeof(sum(a)) FROM t3;")
---
- metadata:
  - name: sum(a)
    type: number
  - name: typeof(sum(a))
    type: string
  rows:
  - [null, 'boolean']
...
```
As you can see, in the meta `sum` has correct type `number`, but `typeof()` return another one.
And even cooler example:
```YAML
tarantool> box.execute("CREATE TABLE t3(a INTEGER primary key);")
---
- row_count: 1
...

tarantool> box.execute("SELECT sum(a), typeof(sum(a)) FROM t3;")
---
- metadata:
  - name: sum(a)
    type: number
  - name: typeof(sum(a))
    type: string
  rows:
  - [null, 'boolean']
...
```
Column is of type INTEGER. `Sum` has type `number` in meta. And type `boolean` in runtime.

**Comment by Gerold103** [comment]
One another:
```YAML
tarantool> box.execute("SELECT MIN(1.1), typeof(MIN(1.1))")
---
- metadata:
  - name: MIN(1.1)
    type: scalar
  - name: typeof(MIN(1.1))
    type: string
  rows:
  - [1.1, 'number']
...

```
`MIN` returns `scalar` in meta, `number` in runtime.

**Comment by Gerold103** [comment]
`MIN` above is an aggregate function, but the same is broken for regular functions:
```YAML
tarantool> box.execute("SELECT ABS(1), typeof(ABS(1))")
---
- metadata:
  - name: ABS(1)
    type: number
  - name: typeof(ABS(1))
    type: string
  rows:
  - [1, 'integer']
...

```

**Comment by Gerold103** [comment]
One another example:
```YAML
tarantool> box.execute("CREATE TABLE t(a INTEGER primary key);")
---
- row_count: 1
...

tarantool> box.execute("INSERT INTO t VALUES(1)")
---
- row_count: 1
...

tarantool> box.execute("SELECT ABS(a), typeof(ABS(a)) FROM t")
---
- metadata:
  - name: ABS(a)
    type: number
  - name: typeof(ABS(a))
    type: string
  rows:
  - [1, 'integer']
...
```
Here ABS should preserve column type. But runtime `typeof` returns `integer`.
