### ISSUE TITLE
SQL comparison miracle

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#4471]
```YAML
tarantool> box.execute("SELECT '2' >= 100")
---
- metadata:
  - name: '''2'' >= 100'
    type: any
  rows:
  - [false]
...

tarantool> box.execute("SELECT 100 < '2'")
---
- metadata:
  - name: 100 < '2'
    type: boolean
  rows:
  - [false]
...
```
From these examples we can assume that 100 or '2' are NaN. If not joking, in both cases it should be either an error, or a conversion to numbers, or a conversion to strings.
