### ISSUE TITLE
SQL ROUND issue with INT

### ISSUE THREAD

**Issue by zilveer** [tarantool/tarantool#4494]
Tarantool version:
Tarantool 2.2.1-6-g109a304d6

OS version:
Debian 9

Bug description:
The syntax `ROUND` behaves strange, it seems to return INT values when using ROUND on INT values:

Steps to reproduce:
```
> SELECT round(999999999999955/3333, 4);
---
- metadata:
  - name: round(999999999999955/3333, 4)
    type: integer
  rows:
  - [300030003000]
```

But in fact the correct calculation is `300030003000,2865`

Why does Tarantool return Integer when in fact it should be a decimal number returned ?

So it seems that INT variables always stays in INT, so what is the solution here with SQL?
Thanks for any solution,
regards Zilveer

**Comment by Korablev77** [comment]
It is due to the fact that result of integer division is integer. You can verify it using simple SELECT:
```
tarantool> SELECT 999999999999955/3333
- metadata:
  - name: 999999999999955/3333
    type: integer
  rows:
  - [300030003000]
...
```
To force floating point representation you can add `.0`: `SELECT 999999999999955.0/3333`).
