### ISSUE TITLE
CAST to INTEGER large floating-point numbers result in an error

### ISSUE THREAD

**Issue by ImeevMA** [tarantool/tarantool#4526]
Tarantool version:
2.3.0-122-gd7a8942

OS version:
Ubuntu 16.04

Bug description:
CAST to INTEGER floating point numbers greater than 9223372036854775296 lead to an error.

Steps to reproduce:
```
box.execute('SELECT CAST(9223372036854775296.01 AS INTEGER)')
```
Result:
```
tarantool> box.execute('SELECT CAST(9223372036854775296.01 AS INTEGER)')
---
- null
- 'Type mismatch: can not convert 9.22337203685478e+18 to integer'
...
```

At the same time, such queries work fine:
```
tarantool> box.execute('SELECT CAST(9223372036854775297 AS INTEGER) + 123')
---
- metadata:
  - name: CAST(9223372036854775297 AS INTEGER) + 123
    type: integer
  rows:
  - [9223372036854775420]
```
