### ISSUE TITLE
 box.info:memory() displays whole content of box.info

### ISSUE THREAD

**Issue by Korablev77** [tarantool/tarantool#4688]
`box.info:memory()` displays whole content of `box.info`, meanwhile `box.info:vinyl()` and `box.info:gc()` do the same as `box.info.vinyl()` and `box.info.gc()` correspondingly:

```
tarantool> box.info.gc()
---
- signature: 0
  checkpoint_is_in_progress: false
  checkpoints:
  - references: []
    vclock: {}
    signature: 0
  - references: []
    vclock: {1: 5}
    signature: 5
  vclock: {}
  consumers: []
...

tarantool> box.info:gc()
---
- signature: 0
  checkpoint_is_in_progress: false
  checkpoints:
  - references: []
    vclock: {}
    signature: 0
  - references: []
    vclock: {1: 5}
    signature: 5
  vclock: {}
  consumers: []
...
```
```
tarantool> box.info:memory()
---
- vinyl: []
  status: running
  version: 2.3.0-270-g49fa68a79
  id: 1
  ro: false
  memory: []
  vclock: {1: 19}
  package: Tarantool
  lsn: 19
  cluster:
    uuid: a7459003-b3d5-4036-b6aa-db160a1d93e9
  pid: 75779
  uptime: 388
  gc: []
  uuid: ad03ce81-ae8d-422c-b670-334c45f6bf9e
  replication:
    1:
      id: 1
      uuid: ad03ce81-ae8d-422c-b670-334c45f6bf9e
      lsn: 19
  signature: 19
...
```
It is worth mentioning that our docs don't say that it is correct way to appeal to statistics (https://www.tarantool.io/en/doc/1.10/book/box/box_info/). On the other hand, it would be nice to see unified way of accessing statistics at least to avoid any confusions.
