### ISSUE TITLE
sql: INSTEAD OF DELETE trigger works not for each row of VIEW

### ISSUE THREAD

**Issue by ImeevMA** [tarantool/tarantool#4740]
Tarantool version: 2.4.0-16-gcdf502c
Bug description: The INSTEAD OF DELETE trigger works not for every row of VIEW if the VIEW has non-unique rows.
Steps to reproduce:
```
box.cfg{}
box.execute('CREATE TABLE t (i INT PRIMARY KEY AUTOINCREMENT, a INT);')
box.execute('CREATE TABLE t1 (i INT PRIMARY KEY AUTOINCREMENT, a INT);')
box.execute('CREATE VIEW v AS SELECT a FROM t;')
box.execute('CREATE TRIGGER bd INSTEAD OF DELETE ON v FOR EACH ROW BEGIN INSERT INTO t1 VALUES (NULL, 1); END;')
box.execute('INSERT INTO t VALUES (NULL, 1);')
box.execute('INSERT INTO t VALUES (NULL, 1);')
box.execute('INSERT INTO t VALUES (NULL, 1);')
box.execute('INSERT INTO t VALUES (NULL, 1);')
box.execute('DELETE FROM v;')
box.execute('SELECT * FROM t1;')
```

Result:
```
tarantool> box.execute('SELECT * FROM t1;')
---
- metadata:
  - name: I
    type: integer
  - name: A
    type: integer
  rows:
  - [1, 1]
...
```
Should be this:
```
tarantool> box.execute('SELECT * FROM t1;')
---
- metadata:
  - name: I
    type: integer
  - name: A
    type: integer
  rows:
  - [1, 1]
  - [2, 1]
  - [3, 1]
  - [4, 1]
...
```
