### ISSUE TITLE
Invalid WAL-log

### ISSUE THREAD

**Issue by dsamirov** [tarantool/tarantool#4792]
Tarantool version:  1.10.5-19-gb58a53b

OS version: CentOS Linux release 7.7.1908 (Core)

Bug description:

I have stored procedure in C. This procedure inserts many tuples in one transaction. Go-client generates tuples with increment primary key (the third field) and sends them to stored procedure. Tarantool works fine, but WAL-logs are invalid.

With 100 inserts per second I see this WAL. Tuple with PK=525 replaces PK=523,524, and 523,524 are missing:

```
---
HEADER:
  lsn: 549
  replica_id: 1
  type: INSERT
  timestamp: 1582786380.909
BODY:
  space_id: 512
  tuple: ['MB0100696611', 1, 522, 522, 'A', 1582786380907859242, 0]
---
HEADER:
  lsn: 550
  replica_id: 1
  type: INSERT
  timestamp: 1582786380.9403
BODY:
  space_id: 512
  tuple: ['MB0100696223', 1, 525, 525, 'A', 1582786380937878830, 0]
---
HEADER:
  lsn: 551
  replica_id: 1
  type: INSERT
  timestamp: 1582786380.9403
BODY:
  space_id: 512
  tuple: ['MB0100696223', 1, 525, 525, 'A', 1582786380937878830, 0]
---
HEADER:
  lsn: 552
  replica_id: 1
  type: INSERT
  timestamp: 1582786380.9403
BODY:
  space_id: 512
  tuple: ['MB0100696223', 1, 525, 525, 'A', 1582786380937878830, 0]
---
HEADER:
  lsn: 553
  replica_id: 1
  type: INSERT
  timestamp: 1582786380.949
BODY:
  space_id: 512
  tuple: ['MB0100697000', 1, 526, 526, 'A', 1582786380947870930, 0]
---
```

With 50000 inserts per second I got this WAL. PK=450,451,452,453,454,455 replaces PK=413,414,415,416,417,418.

`tarantoolctl cat *.xlog | grep tuple`:

```
  tuple: ['MB0100696619', 1, 410, 410, 'A', 1582789167521166657, 0]
  tuple: ['MB0100696162', 1, 411, 411, 'A', 1582789167521167824, 0]
  tuple: ['MB0100696637', 1, 412, 412, 'A', 1582789167521168699, 0]
  tuple: ['MB0100696735', 1, 450, 450, 'A', 1582789167521219817, 0]
  tuple: ['MB0100696435', 1, 451, 451, 'A', 1582789167521220904, 0]
  tuple: ['MB0100696503', 1, 452, 452, 'A', 1582789167521221965, 0]
  tuple: ['MB0100696949', 1, 453, 453, 'A', 1582789167521222973, 0]
  tuple: ['MB0100696483', 1, 454, 454, 'A', 1582789167521224219, 0]
  tuple: ['MB0100696784', 1, 455, 455, 'A', 1582789167521225323, 0]
  tuple: ['MB0100696968', 1, 419, 419, 'A', 1582789167521176038, 0]
  tuple: ['MB0100696627', 1, 420, 420, 'A', 1582789167521177054, 0]
  tuple: ['MB0100696589', 1, 421, 421, 'A', 1582789167521178797, 0]
```

PK=416 exists:

```
tarantool> box.space.A:select(416)
---
- - ['MB0100697031', 1, 416, 416, 'A', 1582789167521172754, 0]
...
```
