### ISSUE TITLE
List anonymous replicas in box.info.replication

### ISSUE THREAD

**Issue by sergepetrenko** [tarantool/tarantool#4900]
Currently it's hard to know which exactly and how many anonymous replicas are following a master. It's also hard to define whether the connection is healthy, and how much have the replicas fallen behind.
On master's side, `box.info.replication` will give the following output, listing only the master itself:
```
---
- 1:
    id: 1
    uuid: 1ca2c226-9f29-4546-bcac-0c612121134f
    lsn: 1
...
```
The anonymous replica output will be more informative:
```
---
- 1:
    id: 1
    uuid: 1ca2c226-9f29-4546-bcac-0c612121134f
    lsn: 1
    upstream:
      status: follow
      idle: 0.83193300000858
      peer: 
      lag: 0.00018906593322754
...
```
Add similar info to master's `box.info.replication` output for anonymous replicas.
