### ISSUE TITLE
popen: protect popen.opts.<...> constants from mistyping

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#4923]
Tarantool version: 2.5.0-2-g098324556.

The popen module exposes the list of constants that it accepts and returns:

```yml
tarantool> popen = require('popen')
tarantool> popen
---
- new: 'function: 0x40ee1a90'
  shell: 'function: 0x40ee1ab8'
  state:
    ALIVE: alive
    EXITED: exited
    SIGNALED: signaled
  signal:
    SIGTERM: 15
    SIGKILL: 9
    <...>
  stream:
    CLOSED: closed
    OPEN: open
  opts:
    PIPE: pipe
    DEVNULL: devnull
    INHERIT: inherit
    CLOSE: close
```

Mistyping like `popen.new(<...>, {stdin = popen.opts.DEVNUL})` will pass `{stdin = nil}` table and the default behaviour (inheriting) will be silently chosen.

We can set a metatable on `popen.opts` or even on all those tables including the module table itself. This metatable will define `__index` metamethod that will give an error on attempt to access a non-existing field.

I prefer to use constants from `popen.opts.<...>` as option values, because it visually distinguish a value that is a kind of enum value from an arbitrary string payload. Mistyping of, say, `'devnull'` will give an error at `popen.new()` and it would be good to receive an error for mistyping of a `popen.opts` constant.
