### ISSUE TITLE
popen: improve child process failure diagnostics

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#4925]
Tarantool version: 2.5.0-2-g098324556.

If a child process fails in `execve()`, the error will not be reported as result of the `popen_new()` call, however it is possible to do, because `vfork()` does not copy a memory pages and blocks a parent process until successful `execve()` or `_exit()`. We can store a failure fact (and also an error) in a stack variable and read it from the parent.

We should verify whether the statements above are valid for Mac OS and FreeBSD:

- Verify vfork() does not copy memory on MacOS / FreeBSD (just in case).
- Verify that vfork() unblocks a parent process only after `execve()` / `_exit()`, not sooner, on MacOS / FreeBSD.

Current behaviour (tarantool console):

```yml
tarantool> popen = require('popen')
tarantool> popen.new({'nonexistent'})
---
- command: nonexistent
  status:
    state: alive
  opts:
    stdout: inherit
    stdin: inherit
    group_signal: false
    keep_child: false
    close_fds: true
    restore_signals: true
    shell: false
    setsid: false
    stderr: inherit
  pid: 10622
...
```
