### ISSUE TITLE
SQL order by repeating column bug

### ISSUE THREAD

**Issue by msiomkin** [tarantool/tarantool#5065]
Tarantool version: Tarantool Enterprise 2.2.2-29-g5c8a435

OS version: Centos 8

Bug description: order by repeating column with limit doesn't work.

Steps to reproduce:

I have the following space:

```
tarantool> box.space.process:format()
---
- [{'name': 'bucket_id', 'type': 'unsigned'}, {'name': 'modelUid', 'type': 'string'},
  {'name': 'id', 'type': 'string'}, {'type': 'string', 'name': 'chainHash', 'is_nullable': true},
  {'type': 'unsigned', 'name': 'eventCount', 'is_nullable': true}, {'type': 'unsigned',
    'name': 'durationFact', 'is_nullable': true}, {'type': 'unsigned', 'name': 'durationSch',
    'is_nullable': true}]
...
```
This query works fine:
```sql
select "id", "modelUid" from "process" order by "id", "modelUid", "id"
```
```
---
- metadata:
  - name: '"id"'
    type: string
  - name: '"modelUid"'
    type: string
  rows:
  - ['1', '85777b8f-35ac-40be-a733-647005ee4cfa']
  - ['10', '85777b8f-35ac-40be-a733-647005ee4cfa']
  - ['11', '85777b8f-35ac-40be-a733-647005ee4cfa']
  - ['12', '85777b8f-35ac-40be-a733-647005ee4cfa']
  - ['13', '85777b8f-35ac-40be-a733-647005ee4cfa']
  - ['14', '85777b8f-35ac-40be-a733-647005ee4cfa']
  - ['15', '85777b8f-35ac-40be-a733-647005ee4cfa']
  - ['16', '85777b8f-35ac-40be-a733-647005ee4cfa']
  - ['17', '85777b8f-35ac-40be-a733-647005ee4cfa']
  - ['18', '85777b8f-35ac-40be-a733-647005ee4cfa']
  - ['19', '85777b8f-35ac-40be-a733-647005ee4cfa']
  - ['2', '85777b8f-35ac-40be-a733-647005ee4cfa']
  - ['20', '85777b8f-35ac-40be-a733-647005ee4cfa']
  - ['3', '85777b8f-35ac-40be-a733-647005ee4cfa']
  - ['4', '85777b8f-35ac-40be-a733-647005ee4cfa']
  - ['5', '85777b8f-35ac-40be-a733-647005ee4cfa']
  - ['6', '85777b8f-35ac-40be-a733-647005ee4cfa']
  - ['7', '85777b8f-35ac-40be-a733-647005ee4cfa']
  - ['8', '85777b8f-35ac-40be-a733-647005ee4cfa']
  - ['9', '85777b8f-35ac-40be-a733-647005ee4cfa']
...
```
This query also works fine:
```sql
select "id", "modelUid" from "process" order by "id", "modelUid" limit 1
```
```
---
- metadata:
  - name: '"id"'
    type: string
  - name: '"modelUid"'
    type: string
  rows:
  - ['1', '85777b8f-35ac-40be-a733-647005ee4cfa']
...
```
Now let's combine:
```sql
select "id", "modelUid" from "process" order by "id", "modelUid", "id" limit 1
```
```
---
- null
- Tuple field count 4 does not match space field count 3
...
```
