### ISSUE TITLE
CONFIRM and ROLLBACK WAL records do not have a named type when printed by tarantoolctl cat utility

### ISSUE THREAD

**Issue by WeCodingNow** [tarantool/tarantool#5199]
Tarantool version: Tarantool 2.5.1-16-gdf35699

OS version: CentOS 7

Bug description:
CONFIRM and ROLLBACK wal records do not have a named type when printed by tarantoolctl cat utility

```
---
HEADER:
  lsn: 14
  replica_id: 1
  type: REPLACE
  timestamp: 1595502062.8321
BODY:
  space_id: 513
  tuple: [1, 1]
---
HEADER:
  lsn: 15
  replica_id: 1
  type: 40             <--- should be CONFIRM
  timestamp: 1595502062.8332
BODY:
- null
- 1
- 14
---
HEADER:
  lsn: 16
  replica_id: 1
  type: REPLACE
  timestamp: 1595502105.7026
BODY:
  space_id: 513
  tuple: [1, 2]
---
HEADER:
  lsn: 17
  replica_id: 1
  type: 40         <--- should be CONFIRM
  timestamp: 1595502105.7038
BODY:
- null
- 1
- 16
---
HEADER:
  lsn: 18
  replica_id: 1
  type: REPLACE
  timestamp: 1595502803.7428
BODY:
  space_id: 513
  tuple: [1, 3]
---
HEADER:
  lsn: 19
  replica_id: 1
  type: 41            <--- should be ROLLBACK
  timestamp: 1595502808.744
BODY:
- null
- 1
- 18
...
```

Steps to reproduce:
launch tarantool master instance with this init file:
```lua
box.cfg{
    listen = 3300,
    replication_synchro_quorum = 2,
    read_only =  false ,
}

box.once("schema", function()
   box.schema.user.create('replicator', {password = 'password'})
   box.schema.user.grant('replicator', 'replication')

   box.schema.space.create('sync', {is_sync=true})
   box.space.sync:create_index('primary')
end)

require('console').start()
```

launch tarantool replica instance with this init file:
```lua
box.cfg{
    listen = 3301,
    replication = 'replicator:password@localhost:3300',
    
    read_only =  true ,
}

require('console').start()
```

in tarantool master instance console do:
```
box.space.sync:put{1, 1}
```

this should produce a REPLACE record in WAL log followed by a CONFIRM record

then kill tarantool replica instance and in tarantool master instance console do:
```
box.space.sync:put{1, 2}
```

this should produce a REPLACE record in WAL log followed by a ROLLBACK record

and, finally:
```
tarantoolctl cat 00000000000000000000.xlog
```

observe
