### ISSUE TITLE
Non-informative error message for index creation

### ISSUE THREAD

**Issue by olegrok** [tarantool/tarantool#5218]
Tarantool version: 2.3

```
s = box.schema.space.create('test')
s:format({{field='name', type = 'map'}})
tarantool> s:create_index('pk', {parts = {{field = 'name', path = 'test'}}})
---
- error: 'Can''t create or modify index ''pk'' in space ''test'': field type ''map''
    is not supported'
...
```

After type specification works fine:
```
tarantool> s:create_index('pk', {parts = {{field = 'name', path = 'test', type='string'}}})
---
- unique: true
  parts:
  - type: string
    is_nullable: false
    path: test
    fieldno: 1
  id: 0
  space_id: 512
  type: TREE
  name: pk
...
```

I expect something like `Type for index "name.test" missed` but not `field type 'map'
    is not supported`
