### ISSUE TITLE
Raft: handle split-brain

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#5295]
If a user specified too low election quorum, a split-brain can happen. And it can be detected from the code. Need to decide what to do when it is detected. Perhaps it is worth making the node read-only and freeze the Raft state machine until a user bumps term manually via `box.raft.new_term()`.

**Comment by sergos** [comment]
I believe we have to prevent such situation in box.cfg(). Also, there should be the same check-ups for adding/removing of a replica to/fro the replica set.

**Comment by Mons** [comment]
The quorum could be set manually. In this case, this may happen.

I think, if such a case is detected, maybe we should turn every node into read_only until the new election term?

**Comment by Gerold103** [comment]
Here is a test which makes the data inconsistent, but does not have any rollbacks. It uses the nopify filter to loose the data.
```Lua
--
-- Instance 1
--

-- Step 1
box.cfg({
    listen = 3313,
    replication = {3313, 3314},
    replication_timeout = 0.1,
    replication_connect_quorum = 0,
})
box.once("bootstrap", function()
    box.schema.user.grant('guest', 'super')
end)

-- Step 3
box.cfg{
    replication_synchro_quorum = 2,
    replication_synchro_timeout = 1000,
}
s = box.schema.create_space('test', {is_sync = true})
_ = s:create_index('pk')
box.ctl.promote()
_ = s:replace{1}

-- Step 5
box.cfg{replication_synchro_quorum = 1}
s:replace{2}
os.exit(0)

-- Step 7
box.cfg({
    listen = 3313,
    replication = {3313, 3314},
    replication_timeout = 0.1,
    replication_connect_quorum = 0,
})
require('fiber').sleep(1)

-- Step 9
box.space.test:select{}
box.info.replication




--
-- Instance 2
--

-- Step 2
box.cfg({
    listen = 3314,
    replication = {3313, 3314},
    replication_timeout = 0.1,
    replication_connect_quorum = 0,
})
box.once("bootstrap", function()
    box.schema.user.grant('guest', 'super')
end)

-- Step 4
os.exit(0)

-- Step 6
box.cfg({
    listen = 3314,
    replication = {3313, 3314},
    replication_timeout = 0.1,
    replication_connect_quorum = 0,
    replication_synchro_quorum = 1,
    replication_synchro_timeout = 0.01,
})
box.ctl.promote()
s = box.space.test
_ = s:replace{3}
box.cfg{election_mode = 'voter'}

-- Step 8
s:select{}
box.info.replication
```

Instance 1 will print in the end:
```
tarantool> box.space.test:select{}
---
- - [1]
  - [2]
  - [3]
...

tarantool> box.info.replication
---
- 1:
    id: 1
    uuid: 04d2d8f5-24cf-41c7-9ed1-1fe91999163c
    lsn: 11
  2:
    id: 2
    uuid: 5ff98048-f184-4728-9693-6a1b840f9e69
    lsn: 3
    upstream:
      status: follow
      idle: 0.087465999997221
      peer: 
      lag: 0.00019311904907227
    downstream:
      status: follow
      idle: 0.08765699993819
      vclock: {2: 3, 1: 11}
      lag: 69.573049783707
...
```

Instance 2 will print in the end:
```
tarantool> s:select{}
---
- - [1]
  - [3]
...

tarantool> box.info.replication
---
- 1:
    id: 1
    uuid: 04d2d8f5-24cf-41c7-9ed1-1fe91999163c
    lsn: 11
    upstream:
      status: follow
      idle: 0.0077349999919534
      peer: 
      lag: 0.0001981258392334
    downstream:
      status: follow
      idle: 0.0079290000721812
      vclock: {2: 3, 1: 11}
      lag: 8.5273628234863
  2:
    id: 2
    uuid: 5ff98048-f184-4728-9693-6a1b840f9e69
    lsn: 3
...
```
The selects return different data even though both instances are in full sync according to the vclocks, and have 'follow' in their replication statuses.

The 'voter' switch at the step 6 is used to workaround #6133. If #6133 is fixed, this bug remains and becomes ever easier to reproduce - 'voter' switch on the step 6 won't affect the result, the data will be different anyway.

I am not too sure about a correct behaviour. But it seems when 'instance1' was started back, it should have been rejected by 'instance2', because tries to insert new data into an old term.

The test works fine if #6133 is not fixed and the step 6 does not switch to 'voter' - then the replication breaks before the data becomes broken.
