### ISSUE TITLE
sql: in some cases INTEGER converted to DOUBLE in field of type NUMBER

### ISSUE THREAD

**Issue by ImeevMA** [tarantool/tarantool#5335]
Tarantool version: 2.6.0

OS version: Ubuntu 20.04

Bug description: in some cases value of type INTEGER converted to value of type DOUBLE in field of type NUMBER.

Steps to reproduce:
1. First reproducer:
```
box.execute("CREATE TABLE t (i NUMBER PRIMARY KEY, n NUMBER);")
box.execute("CREATE TRIGGER t AFTER INSERT ON t FOR EACH ROW BEGIN UPDATE t SET n = new.n; END;")
box.execute("INSERT INTO t VALUES (1, 1);")
box.execute("SELECT i / 2, n / 2 FROM t;")
```

Result:
```
tarantool> box.execute("SELECT i / 2, n / 2 FROM t;")
---
- metadata:
  - name: COLUMN_1
    type: number
  - name: COLUMN_2
    type: number
  rows:
  - [0, 0.5]
...
```

2. Second reproducer:
```
box.execute("CREATE TABLE t (i NUMBER PRIMARY KEY, n NUMBER);")
box.execute("INSERT INTO t VALUES (1,1);")
box.execute("SELECT i / 2, n / 2 FROM t;")
box.execute("SELECT i / 2, n / 2 FROM t GROUP BY n;")
```
Result:
```
tarantool> box.execute("SELECT i / 2, n / 2 FROM t;")
---
- metadata:
  - name: COLUMN_1
    type: number
  - name: COLUMN_2
    type: number
  rows:
  - [0, 0]
...

tarantool> box.execute("SELECT i / 2, n / 2 FROM t GROUP BY n;")
---
- metadata:
  - name: COLUMN_1
    type: number
  - name: COLUMN_2
    type: number
  rows:
  - [0.5, 0.5]
...
```
