### ISSUE TITLE
Bug: field 'path' from index.parts definition is not transmitted via net.box connection

### ISSUE THREAD

**Issue by R-omk** [tarantool/tarantool#5451]
Tarantool version: 2.5.2-0-g05730d326

Steps to reproduce:

```lua

s = box.schema.space.create('json_documents')
s:create_index('primarykey')
i = s:create_index('multikey', {parts = {{field = 2, type = 'str', path = 'data[*].name'} , {field = 2, type = 'unsigned', path = 'data[*].age'} }})
conn = require('net.box').connect('localhost:3301')
```

```
tarantool> i
---
- unique: true
  parts:
  - type: string
    is_nullable: false
    path: data[*].name
    fieldno: 2
  - type: unsigned
    is_nullable: false
    path: data[*].age
    fieldno: 2
  id: 1
  space_id: 512
  type: TREE
  name: multikey
...


```

```
tarantool> conn.space['json_documents'].index['multikey']
---
- &0
  unique: true
  parts:
  - type: string
    is_nullable: false
    fieldno: 2
  - type: unsigned
    is_nullable: false
    fieldno: 2
  id: 1
  type: TREE
  name: multikey
```

As a result, an incorrect index leads to a crash https://github.com/tarantool/tarantool/issues/5450
