### ISSUE TITLE
Enabled leader election breaks replication

### ISSUE THREAD

**Issue by ochaton** [tarantool/tarantool#5488]
Tarantool version: 2.6.1-11-g37077a48e

OS version: MacOS Catalina

Bug description:
```
2020-11-02 17:22:58.535 [30269] main/115/applier/127.0.0.1:3301 txn_limbo.c:590 E> ER_SYNC_MASTER_MISMATCH: CONFIRM message arrived for an unknown master id 1, expected 3
```

```yaml
# node 3:
  replication:
    1:
      id: 1
      uuid: 7549ac9a-863d-41b2-af3c-9b096c9df0f9
      lsn: 13171
      upstream:
        status: sync
        idle: 0.0002250000834465
        peer: 127.0.0.1:3302
        lag: 1204.2683098316
      downstream:
        status: follow
        idle: 0.92278800008353
        vclock: {1: 38358, 2: 329856, 3: 24224}
    2:
      id: 2
      uuid: d8d8303b-21d7-4632-8797-1374f1bd4f87
      lsn: 113852
      upstream:
        peer: 127.0.0.1:3301
        lag: 2358.7561879158
        status: stopped
        idle: 216.55341800011
        message: CONFIRM message arrived for an unknown master id 1, expected 3
      downstream:
        status: follow
        idle: 0.54951500007883
        vclock: {1: 38358, 2: 329856, 3: 24224}
    3:
      id: 3
      uuid: de5bccfc-8264-4bb1-b918-daebdc92b9b0
      lsn: 24231
  election:
    state: follower
    vote: 3
    leader: 2
    term: 5143
```

Steps to reproduce:
Do not have stable steps to reproduce
[election.tar.gz](https://github.com/tarantool/tarantool/files/5475659/election.tar.gz)

It seems that there is only one way to rebootstrap outdated replica

Optional (but very desirable):
* coredump
* backtrace
* netstat
