### ISSUE TITLE
vinyl: EQ select via secondary index returns no data

### ISSUE THREAD

**Issue by Korablev77** [tarantool/tarantool#5591]
Tarantool version: 1.10

It may turn out that select of particular key via secondary index returns no rows meanwhile index in fact contains tuple with that key. It happens due to broken .index file which in turn comprises malformed bloom filter; the rest of .index file's content seems to be OK (i.e. it is the same as after deleting it and re-creating from scratch during force-recovery). Index itself:
```
- unique: true
  parts:
  - type: string
    is_nullable: true
    fieldno: 2
  id: 1
  options:
    page_size: 8192
    run_count_per_level: 2
    run_size_ratio: 3.5
    bloom_fpr: 0.05
    range_size: 1073741824
```
.index metadata:
```
 {'HEADER': {'type': 'RUNINFO'}, 'BODY': {'min_lsn': 52, 'bloom_filter': [[118186,
  'max_key': ['bff95b49-1341-4b44-aa2d-39e244804d33', 70401914], 'page_count': 361922,
  'stmt_stat': {9: 0, 2: 50695476, 5: 0, 3: 0}, 'max_lsn': 19315721391, 'min_key': [
  '7ffb08f4-c569-409d-89ae-3f9c1ed06a7d', 35536629]}}
```
Proper value for bloom filter is `714240`, so if we delete corresponding .index file manually and restart instance with force recovery, new .index file will contain correct bloom value and select will return data as it should.
There are several keys that are rejected by bloom filter like `"ba88332a-ea7f-4fa0-b4af-f25daca2dc00" `or "`8f486efd-9262-4c7b-8e40-9a367ce390a5"`.

Unfortunately, there's no reproducer for this issue. To resolve this issue I guess one should come up with the way how to get wrong value for bloom filter. For instance, generate error injections during dump/compaction processes.
