### ISSUE TITLE
SQL execution error: Space '0' does not exist

### ISSUE THREAD

**Issue by msiomkin** [tarantool/tarantool#5592]
Sometimes (quite often) executing of some SQL queries results in the following error:

```
Space '0' does not exist
```

`box.error.last().trace`:
```json
{"file":"/tarantool/src/box/schema.h","line":84}
```

An example of a query:
```sql
select (
    select "processAttr"."valueStr"
    from "processAttr"
    where "processAttr"."processUid" = "process"."uid"
      and "processAttr"."name" = 'rf_name') as "#1",
    min("process"."uid") as "#2"
  from "process" as "process"
  where "process"."modelUid" = '5c81f5f7-0d21-4cc7-9559-0011dfcf80e2'
  group by "#1"
  order by "#1", "#2"
limit 50;
```

Space formats:
```lua
process = {
    format = {
        { name = "bucket_id", type = "unsigned" },
        { name = "uid", type = "string" },
        { name = "modelUid", type = "string" },
        { name = "extId", type = "string" },
        { name = "chainHash", type = "string", is_nullable = true },
        { name = "eventCount", type = "unsigned", is_nullable = true },
        { name = "durationFact", type = "integer", is_nullable = true },
        { name = "durationSch", type = "integer", is_nullable = true }
    },
    index = {
        {
            name = "uid",
            unique = true,
            parts = { "uid" }
        },
        {
            name = "modelUid_extId",
            unique = true,
            parts = { "modelUid", "extId" }
        },
        {
            name = "bucket_id",
            unique = false,
            parts = { "bucket_id" }
        },
        {
            name = "modelUid_chainHash",
            unique = false,
            parts = { "modelUid", "chainHash" }
        },
        {
            name = "eventCount",
            unique = false,
            parts = { "eventCount" }
        },
        {
            name = "durationFact",
            unique = false,
            parts = { "durationFact" }
        },
        {
            name = "durationSch",
            unique = false,
            parts = { "durationSch" }
        }
    }
},

processAttr = {
    format = {
        { name = "bucket_id", type = "unsigned" },
        { name = "processUid", type = "string" },
        { name = "name", type = "string" },
        { name = "valueNum", type = "number", is_nullable = true },
        { name = "valueStr", type = "string", is_nullable = true }
    },
    index = {
        {
            name = "processUid_name",
            unique = true,
            parts = { "processUid", "name" }
        },
        {
            name = "bucket_id",
            unique = false,
            parts = { "bucket_id" }
        },
        {
            name = "name_valueNum",
            unique = false,
            parts = { "name", "valueNum" }
        },
        {
            name = "name_valueStr",
            unique = false,
            parts = { "name", "valueStr" }
        }
    }
},

event = {
    format = {
        { name = "bucket_id", type = "unsigned" },
        { name = "uid", type = "string" },
        { name = "processUid", type = "string" },
        { name = "extId", type = "string" },
        { name = "modelUid", type = "string" },
        { name = "name", type = "string" },
        { name = "started", type = "unsigned" },
        { name = "ended", type = "unsigned" },
        { name = "intervalFact", type = "integer" },
        { name = "intervalSch", type = "integer" },
        { name = "durationFact", type = "integer" },
        { name = "durationSch", type = "integer" },
        { name = "sorting", type = "integer" }
    },
    index = {
        {
            name = "uid",
            unique = true,
            parts = { "uid" }
        },
        {
            name = "processUid_extId",
            unique = true,
            parts = { "processUid", "extId" }
        },
        {
            name = "bucket_id",
            unique = false,
            parts = { "bucket_id" }
        },
        {
            name = "modelUid",
            unique = false,
            parts = { "modelUid" }
        },
        {
            name = "processUid_started_sorting",
            unique = false,
            parts = { "processUid", "started", "sorting" }
        }
    }
},

eventAttr = {
    format = {
        { name = "bucket_id", type = "unsigned" },
        { name = "eventUid", type = "string" },
        { name = "name", type = "string" },
        { name = "valueNum", type = "number", is_nullable = true },
        { name = "valueStr", type = "string", is_nullable = true }
    },
    index = {
        {
            name = "eventUid_name",
            unique = true,
            parts = { "eventUid", "name" }
        },
        {
            name = "bucket_id",
            unique = false,
            parts = { "bucket_id" }
        },
        {
            name = "name_valueNum",
            unique = false,
            parts = { "name", "valueNum" }
        },
        {
            name = "name_valueStr",
            unique = false,
            parts = { "name", "valueStr" }
        }
    }
},

chain = {
    format = {
        { name = "modelUid", type = "string" },
        { name = "chainHash", type = "string" },
        { name = "chainCount", type = "unsigned", is_nullable = true },
        { name = "percent", type = "number", is_nullable = true },
        { name = "durationFactAvg", type = "integer", is_nullable = true },
        { name = "durationSchAvg", type = "integer", is_nullable = true },
        { name = "eventCount", type = "unsigned" }
    },
    index = {
        {
            name = "modelUid_chainHash",
            unique = true,
            parts = { "modelUid", "chainHash" }
        },
        {
            name = "modelUid_percent",
            unique = false,
            parts = { "modelUid", "percent" }
        }
    }
},

model = {
    format = {
        { name = "bucket_id", type = "unsigned" },
        { name = "uid", type = "string" },
        { name = "name", type = "string", is_nullable = true },
        { name = "chainCount", type = "unsigned", is_nullable = true },
        { name = "processCount", type = "unsigned", is_nullable = true },
        { name = "eventCount", type = "unsigned", is_nullable = true },
        { name = "processAttrTypes", type = "array", is_nullable = true },
        { name = "eventAttrTypes", type = "array", is_nullable = true }
    },
    index = {
        {
            name = "uid",
            unique = true,
            parts = { "uid" }
        },
        {
            name = "bucket_id",
            unique = false,
            parts = { "bucket_id" }
        }
    }
}
```

Another example:
```sql
select
  "c"."chainHash" as "#1",
  "c"."chainCount" as "#2",
  "c"."percent" as "#3",
  "c"."durationFactAvg" as "#4",
  "c"."durationSchAvg" as "#5",
  "c"."eventCount" as "#6",
  (
    select group_concat("name")
    from (
      select distinct
        "e"."name"
      from "event" as "e"
      where "e"."processUid" = "p"."uid"
      order by "e"."name")
    ) as "#7",
    min("c"."modelUid") as "#8",
    min("c"."chainHash") as "#9",
    min("p"."uid") as "#10"
from "chain" as "c"
    inner join "process" as "p" on "p"."chainHash" = "c"."chainHash"
where "c"."modelUid" = ?
    and "c"."percent" <= ?
    and "p"."uid" = (
      select "p2"."uid"
      from "process" as "p2"
      where "p2"."modelUid" = "c"."modelUid"
        and "p2"."chainHash" = "c"."chainHash"
      limit 1)
group by "#1", "#2", "#3", "#4", "#5", "#6", "#7"
order by "#3" desc, "#1" desc, "#8" desc, "#9" desc, "#10" desc
limit 1000;
```

Execution plan:
```
---
- metadata:
  - name: selectid
    type: integer
  - name: order
    type: integer
  - name: from
    type: integer
  - name: detail
    type: text
  rows:
  - [0, 0, 0, 'SEARCH TABLE chain AS c USING COVERING INDEX modelUid_percent (modelUid=?
      AND percent<?) (~2 rows)']
  - [0, 1, 1, 'SEARCH TABLE process AS p USING PRIMARY KEY (uid=?) (~1 row)']
  - [0, 0, 0, 'EXECUTE CORRELATED SCALAR SUBQUERY 1']
  - [1, 0, 0, 'SEARCH TABLE process AS p2 USING COVERING INDEX modelUid_chainHash
      (modelUid=? AND chainHash=?) (~8 rows)']
  - [0, 0, 0, 'USE TEMP B-TREE FOR GROUP BY']
  - [0, 0, 0, 'EXECUTE CORRELATED SCALAR SUBQUERY 2']
  - [3, 0, 0, 'SEARCH TABLE event AS e USING COVERING INDEX processUid_extId (processUid=?)
      (~10 rows)']
  - [3, 0, 0, 'USE TEMP B-TREE FOR DISTINCT']
  - [2, 0, 0, 'SCAN SUBQUERY 3 (~1 row)']
  - [0, 0, 0, 'EXECUTE CORRELATED SCALAR SUBQUERY 4']
  - [5, 0, 0, 'SEARCH TABLE event AS e USING COVERING INDEX processUid_extId (processUid=?)
      (~10 rows)']
  - [5, 0, 0, 'USE TEMP B-TREE FOR DISTINCT']
  - [4, 0, 0, 'SCAN SUBQUERY 5 (~1 row)']
  - [0, 0, 0, 'USE TEMP B-TREE FOR ORDER BY']
...
```

Low level explanation:
```
---
- metadata:
  - name: addr
    type: integer
  - name: opcode
    type: text
  - name: p1
    type: integer
  - name: p2
    type: integer
  - name: p3
    type: integer
  - name: p4
    type: text
  - name: p5
    type: text
  - name: comment
    type: text
  rows:
  - [0, 'Init', 0, 1, 0, '', '00', null]
  - [1, 'OpenTEphemeral', 1, 11, 0, 'k(5,-B,-B,-B,-B,-B)', '00', null]
  - [2, 'IteratorOpen', 5, 0, 1, '', '00', null]
  - [3, 'Integer', 1000, 2, 0, '', '00', null]
  - [4, 'MustBeInt', 2, 7, 0, '', '00', null]
  - [5, 'Integer', 0, 3, 0, '', '00', null]
  - [6, 'Ge', 3, 9, 2, '', '00', null]
  - [7, 'SetDiag', 159, 0, 0, 'Failed to execute SQL statement: Only positive integers
      are allowed in the LIMIT clause', '00', null]
  - [8, 'Halt', -1, 0, 0, '', '00', null]
  - [9, 'Eq', 3, 268, 2, '', '00', null]
  - [10, 'SorterOpen', 6, 9, 0, 'k(7,B,B,B,B,B,B,B)', '00', null]
  - [11, 'Integer', 0, 16, 0, '', '00', null]
  - [12, 'Integer', 0, 15, 0, '', '00', null]
  - [13, 'Null', 0, 19, 25, '', '00', null]
  - [14, 'Gosub', 18, 253, 0, '', '00', null]
  - [15, 'IteratorOpen', 7, 1, 0, 'space<name=chain>', '00', null]
  - [16, 'IteratorOpen', 8, 0, 0, 'space<name=process>', '02', null]
  - [17, 'Variable', 1, 33, 0, '', '00', null]
  - [18, 'IsNull', 33, 131, 0, '', '00', null]
  - [19, 'Null', 0, 34, 0, '', '00', null]
  - [20, 'ApplyType', 33, 1, 0, "\x02", '00', null]
  - [21, 'SeekGT', 7, 131, 33, '2', '00', null]
  - [22, 'Variable', 2, 34, 0, '', '00', null]
  - [23, 'IsNull', 34, 131, 0, '', '00', null]
  - [24, 'ApplyType', 34, 1, 0, "\x03", '00', null]
  - [25, 'IdxGT', 7, 131, 33, '2', '00', null]
  - [26, 'Null', 0, 36, 36, '', '00', null]
  - [27, 'Integer', 1, 37, 0, '', '00', null]
  - [28, 'MustBeInt', 37, 31, 0, '', '00', null]
  - [29, 'Integer', 0, 3, 0, '', '00', null]
  - [30, 'Ge', 3, 33, 37, '', '00', null]
  - [31, 'SetDiag', 159, 0, 0, 'Failed to execute SQL statement: Only positive integers
      are allowed in the LIMIT clause', '00', null]
  - [32, 'Halt', -1, 0, 0, '', '00', null]
  - [33, 'Eq', 3, 47, 37, '', '00', null]
  - [34, 'Integer', 1, 3, 0, '', '00', null]
  - [35, 'Eq', 37, 38, 3, '', '00', null]
  - [36, 'SetDiag', 159, 0, 0, 'Failed to execute SQL statement: Expression subquery
      could be limited only with 1', '00', null]
  - [37, 'Halt', -1, 0, 0, '', '00', null]
  - [38, 'IteratorOpen', 9, 3, 0, 'space<name=process>', '02', null]
  - [39, 'Column', 7, 0, 38, '', '00', null]
  - [40, 'Column', 7, 1, 39, '', '00', null]
  - [41, 'ApplyType', 38, 2, 0, "\x02", '00', null]
  - [42, 'SeekGE', 9, 47, 38, '2', '00', null]
  - [43, 'IdxGT', 9, 47, 38, '2', '00', null]
  - [44, 'Column', 9, 1, 36, '', '00', null]
  - [45, 'DecrJumpZero', 37, 47, 0, '', '00', null]
  - [46, 'Next', 9, 43, 1, '', '00', null]
  - [47, 'IsNull', 36, 130, 0, '', '00', null]
  - [48, 'ApplyType', 36, 1, 0, "\x02", '00', null]
  - [49, 'SeekGE', 8, 130, 36, '1', '00', null]
  - [50, 'IdxGT', 8, 130, 36, '1', '00', null]
  - [51, 'Column', 8, 4, 35, '', '00', null]
  - [52, 'Column', 7, 1, 3, '', '00', null]
  - [53, 'Ne', 3, 129, 35, '({type = binary})', '18', null]
  - [54, 'Column', 7, 1, 40, '', '00', null]
  - [55, 'Column', 7, 2, 41, '', '00', null]
  - [56, 'Column', 7, 3, 42, '', '00', null]
  - [57, 'Column', 7, 4, 43, '', '00', null]
  - [58, 'Column', 7, 5, 44, '', '00', null]
  - [59, 'Column', 7, 6, 45, '', '00', null]
  - [60, 'Null', 0, 49, 49, '', '00', null]
  - [61, 'InitCoroutine', 50, 103, 62, '', '00', null]
  - [62, 'Noop', 10, 3, 0, '', '00', null]
  - [63, 'Noop', 10, 0, 51, '', '00', null]
  - [64, 'SorterOpen', 11, 1, 0, 'k(1,B)', '00', null]
  - [65, 'Integer', 0, 54, 0, '', '00', null]
  - [66, 'Integer', 0, 53, 0, '', '00', null]
  - [67, 'Null', 0, 57, 57, '', '00', null]
  - [68, 'Gosub', 56, 100, 0, '', '00', null]
  - [69, 'IteratorOpen', 12, 1, 0, 'space<name=event>', '02', null]
  - [70, 'Column', 8, 1, 59, '', '00', null]
  - [71, 'ApplyType', 59, 1, 0, "\x02", '00', null]
  - [72, 'SeekGE', 12, 78, 59, '1', '00', null]
  - [73, 'IdxGT', 12, 78, 59, '1', '00', null]
  - [74, 'Column', 12, 5, 3, '', '00', null]
  - [75, 'MakeRecord', 3, 1, 35, '', '00', null]
  - [76, 'SorterInsert', 11, 35, 0, '', '00', null]
  - [77, 'Next', 12, 73, 0, '', '00', null]
  - [78, 'OpenPseudo', 13, 3, 1, '', '00', null]
  - [79, 'SorterSort', 11, 102, 0, '', '00', null]
  - [80, 'SorterData', 11, 3, 13, '', '00', null]
  - [81, 'Column', 13, 0, 58, '', '00', null]
  - [82, 'Compare', 57, 58, 1, 'k(1,B)', '00', null]
  - [83, 'Jump', 84, 88, 84, '', '00', null]
  - [84, 'Move', 58, 57, 1, '', '00', null]
  - [85, 'Gosub', 55, 95, 0, '', '00', null]
  - [86, 'IfPos', 54, 102, 0, '', '00', null]
  - [87, 'Gosub', 56, 100, 0, '', '00', null]
  - [88, 'Column', 13, 0, 52, '', '00', null]
  - [89, 'Integer', 1, 53, 0, '', '00', null]
  - [90, 'SorterNext', 11, 80, 0, '', '00', null]
  - [91, 'Gosub', 55, 95, 0, '', '00', null]
  - [92, 'Goto', 0, 102, 0, '', '00', null]
  - [93, 'Integer', 1, 54, 0, '', '00', null]
  - [94, 'Return', 55, 0, 0, '', '00', null]
  - [95, 'IfPos', 53, 97, 0, '', '00', null]
  - [96, 'Return', 55, 0, 0, '', '00', null]
  - [97, 'Copy', 52, 60, 0, '', '00', null]
  - [98, 'Yield', 50, 0, 0, '', '00', null]
  - [99, 'Return', 55, 0, 0, '', '00', null]
  - [100, 'Null', 0, 52, 52, '', '00', null]
  - [101, 'Return', 56, 0, 0, '', '00', null]
  - [102, 'EndCoroutine', 50, 0, 0, '', '00', null]
  - [103, 'Integer', 1, 61, 0, '', '00', null]
  - [104, 'MustBeInt', 61, 107, 0, '', '00', null]
  - [105, 'Integer', 0, 62, 0, '', '00', null]
  - [106, 'Ge', 62, 109, 61, '', '00', null]
  - [107, 'SetDiag', 159, 0, 0, 'Failed to execute SQL statement: Only positive integers
      are allowed in the LIMIT clause', '00', null]
  - [108, 'Halt', -1, 0, 0, '', '00', null]
  - [109, 'Eq', 62, 124, 61, '', '00', null]
  - [110, 'Integer', 2, 61, 0, '', '00', null]
  - [111, 'Null', 0, 63, 64, '', '00', null]
  - [112, 'InitCoroutine', 50, 0, 62, '', '00', null]
  - [113, 'Yield', 50, 117, 0, '', '00', null]
  - [114, 'Copy', 60, 62, 0, '', '00', null]
  - [115, 'AggStep0', 0, 62, 63, 'GROUP_CONCAT(-1)', '01', null]
  - [116, 'Goto', 0, 113, 0, '', '00', null]
  - [117, 'AggFinal', 63, 1, 0, 'GROUP_CONCAT(-1)', '00', null]
  - [118, 'Copy', 63, 49, 0, '', '00', null]
  - [119, 'DecrJumpZero', 61, 120, 0, '', '00', null]
  - [120, 'Integer', 0, 62, 0, '', '00', null]
  - [121, 'Ne', 62, 124, 61, '', '00', null]
  - [122, 'SetDiag', 159, 0, 0, 'Failed to execute SQL statement: Expression subquery
      returned more than 1 row', '00', null]
  - [123, 'Halt', -1, 0, 0, '', '00', null]
  - [124, 'SCopy', 49, 46, 0, '', '00', null]
  - [125, 'Column', 8, 1, 47, '', '00', null]
  - [126, 'Column', 7, 0, 48, '', '00', null]
  - [127, 'MakeRecord', 40, 9, 62, '', '00', null]
  - [128, 'SorterInsert', 6, 62, 0, '', '00', null]
  - [129, 'Next', 8, 50, 1, '', '00', null]
  - [130, 'Next', 7, 25, 0, '', '00', null]
  - [131, 'OpenPseudo', 14, 62, 9, '', '00', null]
  - [132, 'SorterSort', 6, 255, 0, '', '00', null]
  - [133, 'SorterData', 6, 62, 14, '', '00', null]
  - [134, 'Column', 14, 0, 26, '', '00', null]
  - [135, 'Column', 14, 1, 27, '', '00', null]
  - [136, 'Column', 14, 2, 28, '', '00', null]
  - [137, 'Column', 14, 3, 29, '', '00', null]
  - [138, 'Column', 14, 4, 30, '', '00', null]
  - [139, 'Column', 14, 5, 31, '', '00', null]
  - [140, 'Column', 14, 6, 32, '', '00', null]
  - [141, 'Compare', 19, 26, 7, 'k(7,B,B,B,B,B,B,B)', '00', null]
  - [142, 'Jump', 143, 147, 143, '', '00', null]
  - [143, 'Move', 26, 19, 7, '', '00', null]
  - [144, 'Gosub', 17, 171, 0, '', '00', null]
  - [145, 'IfPos', 16, 255, 0, '', '00', null]
  - [146, 'Gosub', 18, 253, 0, '', '00', null]
  - [147, 'Column', 14, 8, 65, '', '00', null]
  - [148, 'CollSeq', 66, 0, 0, '(binary)', '00', null]
  - [149, 'AggStep0', 0, 65, 11, 'MIN(1)', '01', null]
  - [150, 'Column', 14, 0, 65, '', '00', null]
  - [151, 'CollSeq', 66, 0, 0, '(binary)', '00', null]
  - [152, 'AggStep0', 0, 65, 12, 'MIN(1)', '01', null]
  - [153, 'Column', 14, 7, 65, '', '00', null]
  - [154, 'CollSeq', 66, 0, 0, '(binary)', '00', null]
  - [155, 'AggStep0', 0, 65, 13, 'MIN(1)', '01', null]
  - [156, 'If', 66, 165, 0, '', '00', null]
  - [157, 'Column', 14, 0, 4, '', '00', null]
  - [158, 'Column', 14, 1, 5, '', '00', null]
  - [159, 'Column', 14, 2, 6, '', '00', null]
  - [160, 'Column', 14, 3, 7, '', '00', null]
  - [161, 'Realify', 7, 0, 0, '', '00', null]
  - [162, 'Column', 14, 4, 8, '', '00', null]
  - [163, 'Column', 14, 5, 9, '', '00', null]
  - [164, 'Column', 14, 7, 10, '', '00', null]
  - [165, 'Integer', 1, 15, 0, '', '00', null]
  - [166, 'SorterNext', 6, 133, 0, '', '00', null]
  - [167, 'Gosub', 17, 171, 0, '', '00', null]
  - [168, 'Goto', 0, 255, 0, '', '00', null]
  - [169, 'Integer', 1, 16, 0, '', '00', null]
  - [170, 'Return', 17, 0, 0, '', '00', null]
  - [171, 'IfPos', 15, 173, 0, '', '00', null]
  - [172, 'Return', 17, 0, 0, '', '00', null]
  - [173, 'AggFinal', 11, 1, 0, 'MIN(1)', '00', null]
  - [174, 'AggFinal', 12, 1, 0, 'MIN(1)', '00', null]
  - [175, 'AggFinal', 13, 1, 0, 'MIN(1)', '00', null]
  - [176, 'Copy', 5, 73, 0, '', '00', null]
  - [177, 'Copy', 7, 74, 2, '', '00', null]
  - [178, 'Null', 0, 83, 83, '', '00', null]
  - [179, 'InitCoroutine', 84, 221, 180, '', '00', null]
  - [180, 'Noop', 15, 3, 0, '', '00', null]
  - [181, 'Noop', 15, 0, 85, '', '00', null]
  - [182, 'SorterOpen', 16, 1, 0, 'k(1,B)', '00', null]
  - [183, 'Integer', 0, 88, 0, '', '00', null]
  - [184, 'Integer', 0, 87, 0, '', '00', null]
  - [185, 'Null', 0, 91, 91, '', '00', null]
  - [186, 'Gosub', 90, 218, 0, '', '00', null]
  - [187, 'IteratorOpen', 17, 1, 0, 'space<name=event>', '02', null]
  - [188, 'IsNull', 10, 196, 0, '', '00', null]
  - [189, 'ApplyType', 10, 1, 0, "\x02", '00', null]
  - [190, 'SeekGE', 17, 196, 10, '1', '00', null]
  - [191, 'IdxGT', 17, 196, 10, '1', '00', null]
  - [192, 'Column', 17, 5, 93, '', '00', null]
  - [193, 'MakeRecord', 93, 1, 65, '', '00', null]
  - [194, 'SorterInsert', 16, 65, 0, '', '00', null]
  - [195, 'Next', 17, 191, 0, '', '00', null]
  - [196, 'OpenPseudo', 18, 93, 1, '', '00', null]
  - [197, 'SorterSort', 16, 220, 0, '', '00', null]
  - [198, 'SorterData', 16, 93, 18, '', '00', null]
  - [199, 'Column', 18, 0, 92, '', '00', null]
  - [200, 'Compare', 91, 92, 1, 'k(1,B)', '00', null]
  - [201, 'Jump', 202, 206, 202, '', '00', null]
  - [202, 'Move', 92, 91, 1, '', '00', null]
  - [203, 'Gosub', 89, 213, 0, '', '00', null]
  - [204, 'IfPos', 88, 220, 0, '', '00', null]
  - [205, 'Gosub', 90, 218, 0, '', '00', null]
  - [206, 'Column', 18, 0, 86, '', '00', null]
  - [207, 'Integer', 1, 87, 0, '', '00', null]
  - [208, 'SorterNext', 16, 198, 0, '', '00', null]
  - [209, 'Gosub', 89, 213, 0, '', '00', null]
  - [210, 'Goto', 0, 220, 0, '', '00', null]
  - [211, 'Integer', 1, 88, 0, '', '00', null]
  - [212, 'Return', 89, 0, 0, '', '00', null]
  - [213, 'IfPos', 87, 215, 0, '', '00', null]
  - [214, 'Return', 89, 0, 0, '', '00', null]
  - [215, 'Copy', 86, 94, 0, '', '00', null]
  - [216, 'Yield', 84, 0, 0, '', '00', null]
  - [217, 'Return', 89, 0, 0, '', '00', null]
  - [218, 'Null', 0, 86, 86, '', '00', null]
  - [219, 'Return', 90, 0, 0, '', '00', null]
  - [220, 'EndCoroutine', 84, 0, 0, '', '00', null]
  - [221, 'Integer', 1, 95, 0, '', '00', null]
  - [222, 'MustBeInt', 95, 225, 0, '', '00', null]
  - [223, 'Integer', 0, 96, 0, '', '00', null]
  - [224, 'Ge', 96, 227, 95, '', '00', null]
  - [225, 'SetDiag', 159, 0, 0, 'Failed to execute SQL statement: Only positive integers
      are allowed in the LIMIT clause', '00', null]
  - [226, 'Halt', -1, 0, 0, '', '00', null]
  - [227, 'Eq', 96, 242, 95, '', '00', null]
  - [228, 'Integer', 2, 95, 0, '', '00', null]
  - [229, 'Null', 0, 97, 98, '', '00', null]
  - [230, 'InitCoroutine', 84, 0, 180, '', '00', null]
  - [231, 'Yield', 84, 235, 0, '', '00', null]
  - [232, 'Copy', 94, 96, 0, '', '00', null]
  - [233, 'AggStep0', 0, 96, 97, 'GROUP_CONCAT(-1)', '01', null]
  - [234, 'Goto', 0, 231, 0, '', '00', null]
  - [235, 'AggFinal', 97, 1, 0, 'GROUP_CONCAT(-1)', '00', null]
  - [236, 'Copy', 97, 83, 0, '', '00', null]
  - [237, 'DecrJumpZero', 95, 238, 0, '', '00', null]
  - [238, 'Integer', 0, 96, 0, '', '00', null]
  - [239, 'Ne', 96, 242, 95, '', '00', null]
  - [240, 'SetDiag', 159, 0, 0, 'Failed to execute SQL statement: Expression subquery
      returned more than 1 row', '00', null]
  - [241, 'Halt', -1, 0, 0, '', '00', null]
  - [242, 'Copy', 83, 77, 0, '', '00', null]
  - [243, 'Copy', 6, 67, 0, '', '00', null]
  - [244, 'Copy', 4, 68, 0, '', '00', null]
  - [245, 'Copy', 11, 69, 2, '', '00', null]
  - [246, 'Sequence', 5, 72, 0, '', '00', null]
  - [247, 'MakeRecord', 67, 11, 99, '', '00', null]
  - [248, 'IdxInsert', 99, 1, 0, '', '00', null]
  - [249, 'IfNotZero', 2, 252, 0, '', '00', null]
  - [250, 'Rewind', 5, 251, 0, '', '00', null]
  - [251, 'Delete', 5, 0, 0, '', '00', null]
  - [252, 'Return', 17, 0, 0, '', '00', null]
  - [253, 'Null', 0, 4, 14, '', '00', null]
  - [254, 'Return', 18, 0, 0, '', '00', null]
  - [255, 'Last', 5, 268, 0, '', '00', null]
  - [256, 'Column', 5, 1, 73, '', '00', null]
  - [257, 'Column', 5, 6, 74, '', '00', null]
  - [258, 'Column', 5, 0, 75, '', '00', null]
  - [259, 'Column', 5, 7, 76, '', '00', null]
  - [260, 'Column', 5, 8, 77, '', '00', null]
  - [261, 'Column', 5, 9, 78, '', '00', null]
  - [262, 'Column', 5, 10, 79, '', '00', null]
  - [263, 'Column', 5, 2, 80, '', '00', null]
  - [264, 'Column', 5, 3, 81, '', '00', null]
  - [265, 'Column', 5, 4, 82, '', '00', null]
  - [266, 'ResultRow', 73, 10, 0, '', '00', null]
  - [267, 'Prev', 5, 256, 0, '', '00', null]
  - [268, 'Halt', 0, 0, 0, '', '00', null]
...
```

One more example (**VERY SIMPLE**):
```sql
select "event"."name" as "#1", count(*) as "#2", min("event"."uid") as "#3"
from "event" as "event"
where "event"."modelUid" = '5c81f5f7-0d21-4cc7-9559-0011dfcf80e2' group by "#1";
```

Execution plan:
```
---
- metadata:
  - name: selectid
    type: integer
  - name: order
    type: integer
  - name: from
    type: integer
  - name: detail
    type: text
  rows:
  - [0, 0, 0, 'SEARCH TABLE event AS event USING COVERING INDEX modelUid (modelUid=?)
      (~10 rows)']
  - [0, 0, 0, 'USE TEMP B-TREE FOR GROUP BY']
...
```

Low level explanation:
```
---
- metadata:
  - name: addr
    type: integer
  - name: opcode
    type: text
  - name: p1
    type: integer
  - name: p2
    type: integer
  - name: p3
    type: integer
  - name: p4
    type: text
  - name: p5
    type: text
  - name: comment
    type: text
  rows:
  - [0, 'Init', 0, 1, 0, '', '00', null]
  - [1, 'SorterOpen', 1, 2, 0, 'k(1,B)', '00', null]
  - [2, 'Integer', 0, 6, 0, '', '00', null]
  - [3, 'Integer', 0, 5, 0, '', '00', null]
  - [4, 'Null', 0, 9, 9, '', '00', null]
  - [5, 'Gosub', 8, 45, 0, '', '00', null]
  - [6, 'IteratorOpen', 2, 3, 0, 'space<name=event>', '02', null]
  - [7, 'String8', 0, 11, 0, '5c81f5f7-0d21-4cc7-9559-0011dfcf80e2', '00', null]
  - [8, 'ApplyType', 11, 1, 0, "\x02", '00', null]
  - [9, 'SeekGE', 2, 16, 11, '1', '00', null]
  - [10, 'IdxGT', 2, 16, 11, '1', '00', null]
  - [11, 'Column', 2, 5, 12, '', '00', null]
  - [12, 'Column', 2, 1, 13, '', '00', null]
  - [13, 'MakeRecord', 12, 2, 14, '', '00', null]
  - [14, 'SorterInsert', 1, 14, 0, '', '00', null]
  - [15, 'Next', 2, 10, 1, '', '00', null]
  - [16, 'OpenPseudo', 3, 14, 2, '', '00', null]
  - [17, 'SorterSort', 1, 47, 0, '', '00', null]
  - [18, 'SorterData', 1, 14, 3, '', '00', null]
  - [19, 'Column', 3, 0, 10, '', '00', null]
  - [20, 'Compare', 9, 10, 1, 'k(1,B)', '00', null]
  - [21, 'Jump', 22, 26, 22, '', '00', null]
  - [22, 'Move', 10, 9, 1, '', '00', null]
  - [23, 'Gosub', 7, 38, 0, '', '00', null]
  - [24, 'IfPos', 6, 47, 0, '', '00', null]
  - [25, 'Gosub', 8, 45, 0, '', '00', null]
  - [26, 'AggStep0', 0, 0, 2, 'COUNT(-1)', '00', null]
  - [27, 'Column', 3, 1, 15, '', '00', null]
  - [28, 'CollSeq', 16, 0, 0, '(binary)', '00', null]
  - [29, 'AggStep0', 0, 15, 3, 'MIN(1)', '01', null]
  - [30, 'If', 16, 32, 0, '', '00', null]
  - [31, 'Column', 3, 0, 1, '', '00', null]
  - [32, 'Integer', 1, 5, 0, '', '00', null]
  - [33, 'SorterNext', 1, 18, 0, '', '00', null]
  - [34, 'Gosub', 7, 38, 0, '', '00', null]
  - [35, 'Goto', 0, 47, 0, '', '00', null]
  - [36, 'Integer', 1, 6, 0, '', '00', null]
  - [37, 'Return', 7, 0, 0, '', '00', null]
  - [38, 'IfPos', 5, 40, 0, '', '00', null]
  - [39, 'Return', 7, 0, 0, '', '00', null]
  - [40, 'AggFinal', 2, 0, 0, 'COUNT(-1)', '00', null]
  - [41, 'AggFinal', 3, 1, 0, 'MIN(1)', '00', null]
  - [42, 'Copy', 1, 17, 2, '', '00', null]
  - [43, 'ResultRow', 17, 3, 0, '', '00', null]
  - [44, 'Return', 7, 0, 0, '', '00', null]
  - [45, 'Null', 0, 1, 4, '', '00', null]
  - [46, 'Return', 8, 0, 0, '', '00', null]
  - [47, 'Halt', 0, 0, 0, '', '00', null]
...
```

Tarantool version:
[centos@pm-rt-1 ~]$ tarantool --version
Tarantool Enterprise 2.4.2-12-g11f587c
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=ON
Compiler: /usr/bin/cc /usr/bin/c++
C_FLAGS: -static-libstdc++ -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type
CXX_FLAGS: -static-libstdc++ -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type

OS version: centos 8
