### ISSUE TITLE
 Low SQL queries performance

### ISSUE THREAD

**Issue by msiomkin** [tarantool/tarantool#5593]
The following query takes ~2.5 seconds to execute on a relatively small dataset:

```sql
select
    (select "eventAttr"."valueStr"
     from "eventAttr"
     where "eventAttr"."eventUid" = "event"."uid"
        and "eventAttr"."name" = 'supp_level') as "#1",
    sum(cast(cast("event"."durationFact" as double) / 60 as double) / 60) as "#2",
    count(cast(cast("event"."durationFact" as double) / 60 as double) / 60) as "#3",
    min("event"."uid") as "#4",
    min("process"."uid") as "#5"
from "event" as "event"
    inner join "process" on "event"."processUid" = "process"."uid"
where
    exists(
        select 1 from "eventAttr"
        where "eventAttr"."eventUid" = "event"."uid"
            and "eventAttr"."name" = 'supp_level'
            and "eventAttr"."valueStr" <> '' limit 1)
    and exists(
        select 1
        from "processAttr"
        where "processAttr"."processUid" = "process"."uid"
            and "processAttr"."name" = 'intr_type'
            and "processAttr"."valueStr" = 'Телефон' limit 1)
    and "event"."modelUid" = '5c81f5f7-0d21-4cc7-9559-0011dfcf80e2'
    group by "#1";
```

Space formats:
```Lua
process = {
    format = {
        { name = "bucket_id", type = "unsigned" },
        { name = "uid", type = "string" },
        { name = "modelUid", type = "string" },
        { name = "extId", type = "string" },
        { name = "chainHash", type = "string", is_nullable = true },
        { name = "eventCount", type = "unsigned", is_nullable = true },
        { name = "durationFact", type = "integer", is_nullable = true },
        { name = "durationSch", type = "integer", is_nullable = true }
    },
    index = {
        {
            name = "uid",
            unique = true,
            parts = { "uid" }
        },
        {
            name = "modelUid_extId",
            unique = true,
            parts = { "modelUid", "extId" }
        },
        {
            name = "bucket_id",
            unique = false,
            parts = { "bucket_id" }
        },
        {
            name = "modelUid_chainHash",
            unique = false,
            parts = { "modelUid", "chainHash" }
        },
        {
            name = "eventCount",
            unique = false,
            parts = { "eventCount" }
        },
        {
            name = "durationFact",
            unique = false,
            parts = { "durationFact" }
        },
        {
            name = "durationSch",
            unique = false,
            parts = { "durationSch" }
        }
    }
},

processAttr = {
    format = {
        { name = "bucket_id", type = "unsigned" },
        { name = "processUid", type = "string" },
        { name = "name", type = "string" },
        { name = "valueNum", type = "number", is_nullable = true },
        { name = "valueStr", type = "string", is_nullable = true }
    },
    index = {
        {
            name = "processUid_name",
            unique = true,
            parts = { "processUid", "name" }
        },
        {
            name = "bucket_id",
            unique = false,
            parts = { "bucket_id" }
        },
        {
            name = "name_valueNum",
            unique = false,
            parts = { "name", "valueNum" }
        },
        {
            name = "name_valueStr",
            unique = false,
            parts = { "name", "valueStr" }
        }
    }
},

event = {
    format = {
        { name = "bucket_id", type = "unsigned" },
        { name = "uid", type = "string" },
        { name = "processUid", type = "string" },
        { name = "extId", type = "string" },
        { name = "modelUid", type = "string" },
        { name = "name", type = "string" },
        { name = "started", type = "unsigned" },
        { name = "ended", type = "unsigned" },
        { name = "intervalFact", type = "integer" },
        { name = "intervalSch", type = "integer" },
        { name = "durationFact", type = "integer" },
        { name = "durationSch", type = "integer" },
        { name = "sorting", type = "integer" }
    },
    index = {
        {
            name = "uid",
            unique = true,
            parts = { "uid" }
        },
        {
            name = "processUid_extId",
            unique = true,
            parts = { "processUid", "extId" }
        },
        {
            name = "bucket_id",
            unique = false,
            parts = { "bucket_id" }
        },
        {
            name = "modelUid",
            unique = false,
            parts = { "modelUid" }
        },
        {
            name = "processUid_started_sorting",
            unique = false,
            parts = { "processUid", "started", "sorting" }
        }
    }
},

eventAttr = {
    format = {
        { name = "bucket_id", type = "unsigned" },
        { name = "eventUid", type = "string" },
        { name = "name", type = "string" },
        { name = "valueNum", type = "number", is_nullable = true },
        { name = "valueStr", type = "string", is_nullable = true }
    },
    index = {
        {
            name = "eventUid_name",
            unique = true,
            parts = { "eventUid", "name" }
        },
        {
            name = "bucket_id",
            unique = false,
            parts = { "bucket_id" }
        },
        {
            name = "name_valueNum",
            unique = false,
            parts = { "name", "valueNum" }
        },
        {
            name = "name_valueStr",
            unique = false,
            parts = { "name", "valueStr" }
        }
    }
}
```

The amount of data:
```Lua
unix/:/var/run/tarantool/pems.storage-10.control> box.space.process:count()
---
- 33727
...

unix/:/var/run/tarantool/pems.storage-10.control> box.space.event:count()
---
- 274718
...

unix/:/var/run/tarantool/pems.storage-10.control> box.space.processAttr:count()
---
- 291700
...

unix/:/var/run/tarantool/pems.storage-10.control> box.space.eventAttr:count()
---
- 936728
...
```

Execution plan:
```
---
- metadata:
  - name: selectid
    type: integer
  - name: order
    type: integer
  - name: from
    type: integer
  - name: detail
    type: text
  rows:
  - [0, 0, 0, 'SEARCH TABLE event AS event USING COVERING INDEX modelUid (modelUid=?)
      (~9 rows)']
  - [0, 0, 0, 'EXECUTE CORRELATED SCALAR SUBQUERY 1']
  - [1, 0, 0, 'SEARCH TABLE eventAttr USING PRIMARY KEY (eventUid=? AND name=?) (~1
      row)']
  - [0, 1, 1, 'SEARCH TABLE process USING PRIMARY KEY (uid=?) (~1 row)']
  - [0, 0, 0, 'EXECUTE CORRELATED SCALAR SUBQUERY 2']
  - [2, 0, 0, 'SEARCH TABLE processAttr USING PRIMARY KEY (processUid=? AND name=?)
      (~1 row)']
  - [0, 0, 0, 'USE TEMP B-TREE FOR GROUP BY']
  - [0, 0, 0, 'EXECUTE CORRELATED SCALAR SUBQUERY 3']
  - [3, 0, 0, 'SEARCH TABLE eventAttr USING PRIMARY KEY (eventUid=? AND name=?) (~1
      row)']
  - [0, 0, 0, 'EXECUTE CORRELATED SCALAR SUBQUERY 4']
  - [4, 0, 0, 'SEARCH TABLE eventAttr USING PRIMARY KEY (eventUid=? AND name=?) (~1
      row)']
...
```

The plan is perfect! The performance is terrible...

Tarantool version:
[centos@pm-rt-1 ~]$ tarantool --version
Tarantool Enterprise 2.4.2-12-g11f587c
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=ON
Compiler: /usr/bin/cc /usr/bin/c++
C_FLAGS: -static-libstdc++ -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type
CXX_FLAGS: -static-libstdc++ -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type

OS version: centos 8
