### ISSUE TITLE
strange slow processing of sql query

### ISSUE THREAD

**Issue by ArtDu** [tarantool/tarantool#5698]
Tarantool version: Tarantool Enterprise 2.6.1-0-gcfe0d1a55-r356
OS version: CentOS 7
Bug description: strange slow processing of sql query
Engine: Vinyl
Steps to reproduce:

This query is fast(a few milliseconds):
`SELECT * FROM "test_datamart__gibddpp2__vehicleregdata_history" WHERE "sys_from" <= 98 AND "sys_to" >= 98`
But this is too slow(1.5min), was expected more efficiency of speed response:
`SELECT * FROM "test_datamart__gibddpp2__vehicleregdata_history" WHERE "sys_from" >= 98 AND "sys_to" <= 98`

Number of fields: 209
Main fields by which the indices are built:
```
- name: "id"
        type: "integer"
        is_nullable: false
- name: "vehiclevin"
        type: "string"
        is_nullable: true
- name: "vehiclevin2"
        type: "string"
        is_nullable: true
- name: "sys_from"
        type: "number"
        is_nullable: false
- name: "sys_to"
        type: "number"
        is_nullable: true
```
Indexes:
```
indexes:
      - unique: true
        parts:
          - path: "id"
            type: "integer"
            is_nullable: false
          - path: "sys_from"
            type: "number"
            is_nullable: false
        type: "TREE"
        name: "id"
      - unique: false
        parts:
          - path: "bucket_id"
            type: "unsigned"
            is_nullable: false
        type: "TREE"
        name: "bucket_id"
      - unique: false
        parts:
          - path: "vehiclevin"
            type: "string"
            is_nullable: true
        type: "TREE"
        name: "vehiclevin"
      - unique: false
        parts:
          - path: "vehiclevin2"
            type: "string"
            is_nullable: true
        type: "TREE"
        name: "vehiclevin2"
      - unique: false
        parts:
          - path: "sys_to"
            type: "number"
            is_nullable: true
        type: "TREE"
        name: "sys_to"
      - unique: false
        parts:
          - path: "sys_from"
            type: "number"
            is_nullable: false
        type: "TREE"
        name: "sys_from"
```

Columns data, which used in query:
```
localhost:3304> box.space.test_datamart__gibddpp2__vehicleregdata_history:count()
---
- 402980
...
localhost:3304> SELECT DISTINCT "sys_from", COUNT("sys_from") FROM "test_datamart__gibddpp2__vehicleregdata_history"
---
- metadata:
  - name: sys_from
    type: number
  - name: COLUMN_1
    type: integer
  rows:
  - [15, 402980]
...

localhost:3304> SELECT DISTINCT "sys_to", COUNT("sys_to") FROM "test_datamart__gibddpp2__vehicleregdata_history"
---
- metadata:
  - name: sys_to
    type: number
  - name: COLUMN_1
    type: integer
  rows:
  - [15, 402980]
...

```
