### ISSUE TITLE
Vinyl primary index lookup on high load hangs the server

### ISSUE THREAD

**Issue by pnvasanth** [tarantool/tarantool#5700]
Tarantool version: 2.4.2-1-g3f00d29

OS version: alpine:3.9 (Docker image)

Bug description: 
We have a replica set with 3 servers one master and two replicas. Routing all the read requests only to read replicas with `vshard` options `prefer_replica = true` and `balance = true`.  We are having huge data in the space 
Ex: `(index:len() => 79,927,725)` 
Once we start reading from Vinyl primary index its going dramatically down and its lead to hang the server with lot of warnings like below.  (nearly 3k requests per second)

```
too long WAL write: 1 rows at LSN 473075130: 0.821 sec
too long WAL write: 1 rows at LSN 473075131: 0.821 sec
513/0: get([1586753, 11556036933]) => [25850, ....] took too long: 0.821 sec
too long WAL write: 1 rows at LSN 473075138: 0.915 sec
too long WAL write: 1 rows at LSN 473075137: 0.915 sec
513/0: select([218626212], EQ) => [25739, .....] took too long: 1.033 sec
513/0: select([247387146], EQ) => [20515, .....] took too long: 1.040 sec
513/0: select([112149492], EQ) => <NULL> took too long: 0.942 sec
52 messages suppressed
too long WAL write: 1 rows at LSN 473252762: 1.205 sec
too long WAL write: 1 rows at LSN 473252759: 1.205 sec
143 messages suppressed
too long WAL write: 1 rows at LSN 473271131: 1.972 sec
stopping input on connection fd 694, aka 10.0.137.111:3301, peer of 10.0.149.99:59416, net_msg_max limit is reached
stopping input on connection fd 695, aka 10.0.137.111:3301, peer of 10.0.138.155:36786, net_msg_max limit is reached
233 messages suppressed
513/0: select([163443110], EQ) => [29477,...] took too long: 44.692 sec
513/0: select([1694560], EQ) => [23824,...] took too long: 343.706 sec
240 messages suppressed
stopping input on connection fd 688, aka 10.0.137.111:3301, peer of 10.0.139.84:33576, net_msg_max limit is reached
513/0: select([179554275], EQ) => [26975,...] took too long: 3.702 sec
```

*Space Details:*
```
local format = {
        { 'bucket_id',		'unsigned' },
        { 'message_id',		'unsigned' }, 
        { 'user_id',		'unsigned' },
        { 'data',		'string', is_nullable = true},
        { 'params_data',	'string', is_nullable = true},
        { 'created_at',		'number' }, 
        { 'updated_at',		'number' }
    }
space = box.schema.space.create(message, {if_not_exists = true, engine = 'vinyl', temporary = false})
space:format(format)
space:create_index('idx_user_message', {
        parts = { 'user_id', 'message_id' },
        if_not_exists = true,
        unique = true,
    })

```
*box.cfg*
```
---
- vinyl_run_count_per_level: 3
  feedback_host: https://feedback.tarantool.io
  custom_proc_title: xxx@xxxxx-1-2
  wal_dir: /data
  checkpoint_interval: 1800
  replication_anon: false
  replication_connect_timeout: 30
  coredump: false
  vinyl_run_size_ratio: 2
  replication_timeout: 1
  memtx_memory: 134217728
  replication:
  - 0xxxxxxxx:3301
  - 1xxxxxxxx:3301
  - 2xxxxxxxx:3301
  readahead: 81600
  wal_dir_rescan_delay: 2
  vinyl_memory: 3865190400
  too_long_threshold: 0.5
  force_recovery: false
  strip_core: true
  feedback_enabled: true
  wal_max_size: 268435456
  hot_standby: false
  slab_alloc_factor: 1.05
  replication_skip_conflict: true
  background: false
  vinyl_dir: /data
  vinyl_cache: 3865190400
  vinyl_read_threads: 4
  replication_sync_lag: 10
  vinyl_timeout: 60
  net_msg_max: 3840
  listen: '3301'
  vinyl_write_threads: 4
  vinyl_bloom_fpr: 0.2
  checkpoint_count: 2
  memtx_min_tuple_size: 16
  log_format: json
  memtx_max_tuple_size: 1048576
  vinyl_max_tuple_size: 1048576
  feedback_interval: 3600
  sql_cache_size: 5242880
  wal_mode: write
  worker_pool_threads: 4
  replication_connect_quorum: 0
  read_only: true
  work_dir: /opt/tarantool
  memtx_dir: /data
  log_level: 5
  checkpoint_wal_threshold: 1000000000000000000
  vinyl_page_size: 2621440
  replication_sync_timeout: 300
...
```
We are having the issue only we start reading the data, writes are going fine.
Please let me know your thoughts and is there any config changes will help?  
Thank you.
