### ISSUE TITLE
multikey indexes don't respect "exclude_null" option

### ISSUE THREAD

**Issue by olegrok** [tarantool/tarantool#5861]
```yaml
tarantool> box.space.test:select()
---
- - [1, ['a', 'b']]
  - [2, ['c', null]]
  - [3, null]
...
tarantool> box.space.test.index.mk
---
- unique: true
  parts:
  - path: '[*]'
    type: string
    exclude_null: true
    fieldno: 2
    is_nullable: true
  hint: true
  id: 1
  type: TREE
  space_id: 512
  name: mk
...
tarantool> box.space.test.index.mk:select()
---
- - [2, ['c', null]]
  - [1, ['a', 'b']]
  - [1, ['a', 'b']]
  - [2, ['c', null]]
...
tarantool> box.space.test.index.mk2
---
- unique: true
  parts:
  - type: string
    is_nullable: true
    path: '[*]'
    fieldno: 2
  hint: true
  id: 2
  type: TREE
  space_id: 512
  name: mk2
...
tarantool> box.space.test.index.mk2:select()
---
- - [2, ['c', null]]
  - [1, ['a', 'b']]
  - [1, ['a', 'b']]
  - [2, ['c', null]]
...
```

Here I just report such behaviour, personally I don't suffer from such option. But here some thoughts.
If "exclude_null" option gives me guarantee that nulls won't be indexed - I expect following output:
```yaml
tarantool> box.space.test.index.mk:select()
---
- - [1, ['a', 'b']]
  - [1, ['a', 'b']]
  - [2, ['c', null]]
...
```
The second array element in `[2, ['c', null]]` shouldn't be indexed.
