### ISSUE TITLE
http client: hang at response without CRLF before empty body

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#5937]
Affected versions: all currently exist (verified on 2.8.0-80-g4842c090f).
Reported by: Vladimir Malyutin (@first-leon).

The HTTP standard [requires](https://tools.ietf.org/html/rfc2616#section-6) CRLF before a body, even if it is empty, aside of CRLF after the last header. However we should not hang when meet this situation.

## How to reproduce

I'll use our http server to send an incorrect response.

1. Clone and checkout v1:

```sh
$ git clone https://github.com:tarantool/http.git
$ cd http
$ git chechout 1.1.0
```

2. Broke it:

```diff
diff --git a/http/server.lua b/http/server.lua
index e7dac9a..4199c8c 100644
--- a/http/server.lua
+++ b/http/server.lua
@@ -844,7 +844,7 @@ local function process_client(self, s, peer)
                 table.insert(response, sprintf("%s: %s\r\n", ucfirst(k), v))
             end
         end
-        table.insert(response, "\r\n")
+        --table.insert(response, "\r\n")
 
         if type(body) == 'string' then
             table.insert(response, body)
```

3. Run the broken HTTP server:

```sh
$ tarantool
tarantool> httpd = require('http.server').new('127.0.0.1', 8080) httpd:route({path='/', method='GET'}, function() return {status = 200, headers = {}, body = ''} end) httpd:start()
```

4. Attempt to receive a response from this server:

```sh
$ tarantool
tarantool> require('http.client').get('http://127.0.0.1:8080')
<..here it hangs..>
```

## Details

In order to investigate whether my guess about the reason of the hang that Vladimir sporadically sees on his workload, I created a dirty patch (upward 2.6.2), which allows to spot the problem with a log message and the extra field in the http client response:

```diff
diff --git a/src/lua/httpc.c b/src/lua/httpc.c
index c3dd611fa..249db0388 100644
--- a/src/lua/httpc.c
+++ b/src/lua/httpc.c
@@ -76,6 +76,15 @@ parse_headers(lua_State *L, char *buffer, size_t len,
        lua_pushstring(L, "headers");
        lua_newtable(L);
        while (true) {
+               if (buffer >= end_buf) {
+                       const char *msg = "It seems, HTTP response does not "
+                                         "end with CRLF CRLF";
+                       lua_pushstring(L, msg);
+                       lua_setfield(L, -4, "no_crlf_error");
+                       say_error(msg);
+                       diag_set(IllegalParams, msg);
+                       break;
+               }
                int rc = http_parse_header_line(&parser, &buffer, end_buf,
                                                max_header_name_len);
                if (rc == HTTP_PARSE_INVALID || rc == HTTP_PARSE_CONTINUE) {
```

The result looks so:

```yaml
tarantool> require('http.client').get('http://127.0.0.1:8080')
2021-03-23 22:36:51.098 [13992] main/103/interactive httpc.c:82 E> It seems, HTTP response does not end with CRLF CRLF
---
- no_crlf_error: It seems, HTTP response does not end with CRLF CRLF
  reason: Ok
  status: 200
  proto:
  - 1
  - 1
  headers:
    content-length: '0'
    server: Tarantool http (tarantool v2.8.0-80-g4842c090f)
    connection: close
...
```

It is definitely not a proper fix, just workaround to look around the problem.
