### ISSUE TITLE
MVCC: memory monitoring

### ISSUE THREAD

**Issue by unera** [tarantool/tarantool#6150]
1. Tarantool is a high RPS application. So, typical tarantool application will have too many RPS. 
2. MVCC: A transaction uses additional memory since the first conflict and until it is closed.

So if You reflect on the pt 1 and 2, You'll find that there can be a situation:

- someone's opened a transaction and hasn't closed it for a long time
- high RPS level brings tarantool to OOM killer

So it would be nice to monitor how much memory MVCC uses.

Min/Max/AVG per txn/total

**Comment by unera** [comment]
1. All these counters are in <code>box.stat.**memtx.mvcc**</code>, so don't use `memtx`, `mvcc` as keyname parts.
2. Don't use phrases with spaces as key names (`tuple stories` -> `tuples`, etc)

**Comment by drewdzzz** [comment]
```
txn:
    statements:
      max: 0
      avg: 0
      total: 0
    user:
      max: 0
      avg: 0
      total: 0
    system:
      max: 0
      avg: 0
      total: 0
  mvcc:
    trackers:
      max: 0
      avg: 0
      total: 0
    conflicts:
      max: 0
      avg: 0
      total: 0
    tuples:
      tracking:
        stories:
          count: 0
          total: 0
        retained:
          count: 0
          total: 0
      used:
        stories:
          count: 0
          total: 0
        retained:
          count: 0
          total: 0
      read_view:
        stories:
          count: 0
          total: 0
        retained:
          count: 0
          total: 0
```
New format of statistics, @unera, what do you think?
