### ISSUE TITLE
Provide tarantool local start

### ISSUE THREAD

**Issue by unera** [tarantool/tarantool#6211]
We want to have a possibility to use a locally installed tarantool under any other installed tarantool version.
So system tarantool will be a launcher for local tarantools.

To realize the mechanizm we need to change tarantool startup scenario in a following way:

Tarantool is local if any condition is true (in the priority):

- environment variable `TT_HOME` is set (it points to a local directory)
- `.tt.conf` is found (by its search rules, see below)

If a local start is detected, then the following algorithm is performed:

1. Read `.tt.conf` (if exists) - this is a `YAML` config file
2. Search executable binary tarantool in the local directory using prefix from the config (from tarantool.bin section).
3. If executable binary is found, then:
  - Check, if it has already started. If `true`, continue usual start
  - Otherwise do exec to the found binary, using the same command arguments.

So, we can start local tarantool by
- Set `TT_HOME` to local installation
- Place `.tt.conf` to local directory and start tarantool inside the directory

#### Search rules for `.tt.conf`
- Search in current dir
- Up to one level up, until `/`
- If there was no one `.tt.conf` found, use `/etc/tarantool/tt.conf`.

Structure of `.tt.conf` or `/etc/tarantool/tt.conf`:

```yaml
tarantool:
  bin: path/to/bindir       # default is /usr/bin - system, ./bin - local
  pid: path/to/piddir       # default is /var/run/tarantool - system, ./var - local
  instances: path/to/idir   # default is /etc/tarantool/instnces.enabled - system, etc
  work: path/to/workdir     # default is /var/lib/tarantool/ - system...
  luadir: path/to/luadir
  logdir: path/to/logdir
  # the other global options, like 'do or don't send crash reports to tarantool team'
```

**Comment by unera** [comment]
It would be nice to add the patch for 1.10+

**Comment by unera** [comment]
`/etc/tarantool/tt.conf` have to contain all items from `/etc/default/tarantool`:

```lua
--
-- System-wide settings for tarantoolctl and init scripts
--
-- This file was configured by the package maintainers and you probably
-- don't want to change it. Please complain about your custom configuration
-- directly to upstream's bug tracker rather than to your distro.
--
-- Settings below should be kept in sync with:
--
--   * logrotate configuration
--   * tarantool.service unit
--   * systemd-tmpfiles configuration                                                                                                                                               
--   * directory structure and permissions
--

default_cfg = {
    pid_file   = "/var/run/tarantool", -- /var/run/tarantool/${INSTANCE}.pid
    wal_dir    = "/var/lib/tarantool", -- /var/lib/tarantool/${INSTANCE}/
    memtx_dir  = "/var/lib/tarantool", -- /var/lib/tarantool/${INSTANCE}
    vinyl_dir  = "/var/lib/tarantool", -- /var/lib/tarantool/${INSTANCE}
    log        = "/var/log/tarantool", -- /var/log/tarantool/${INSTANCE}.log
    username   = "tarantool",
    language   = "lua",
}

-- instances.available - all available instances
-- instances.enabled - instances to autostart by sysvinit
instance_dir = "/etc/tarantool/instances.enabled"
-- vim: set ft=lua :
```

Example (and defaults) for system:

```yaml
tarantool:
     pid_dir: /var/run/tarantool
     wal_dir: /var/lib/tarantool
     memtx_dir: /var/lib/tarantool
     vinyl_dir: /var/lib/tarantool
     log_dir: /var/log/tarantool
     username: tarantool
     language: lua
     instance_dir: /etc/tarantool/instances.enabled
```

Example (and defaults) for local:

```yaml
tarantool:
     pid_dir: ./pid
     wal_dir: ./db
     memtx_dir: ./db
     vinyl_dir: ./db
     instance_dir: ./instances.enabled
     log_dir: ./log
```
