### ISSUE TITLE
Implement statistic for iproto streams and remove in from `errinj`

### ISSUE THREAD

**Issue by EvgenyMekhanik** [tarantool/tarantool#6293]
1. At this moment, statistics on the number of streams and messages in streams are collected only for test purposes and stored in `errinj` to check that there is no memory leak in streams. Discuss what statistics are needed for streams, add it and remove statistics for streams from errinj.
2. Also at this moment we use errinj to collect iproto statistic per thread for test purpose. We store in errinj thread
number, which determine for what thread we want to get statistic. May be in this issue discuss and resolve it in other way.

**Comment by unera** [comment]
Let's add the key `STREAMS` into `box.stat.net`:

```yaml
STREAMS:
   threads:
   - active: 12  # count of active streams
     requests:
        total: 123
        rps: 2    # last 5 second
   - active: 0
     requests:
         total: 0
         rps: 0
```
