### ISSUE TITLE
Possible memory leak when vinyl and expirationd

### ISSUE THREAD

**Issue by filonenko-mikhail** [tarantool/tarantool#6476]
**Bug description**

There is case, when using vinyl with expiration logic.

* OS: Centos8

```
Tarantool 2.8.2-0-gfc96d10f5
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_BACKTRACE=OFF
Compiler: /usr/bin/cc /usr/bin/c++
C_FLAGS:-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fexceptions -funwind-tables -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type -Werror
CXX_FLAGS:-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fexceptions -funwind-tables -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror
```

**Steps to reproduce**

```lua
#!/usr/bin/env tarantool

local uuid = require('uuid')
local expirationd = require('expirationd')

box.cfg{}

box.schema.space.create('temp', {engine='vinyl', if_not_exists=true})

box.space.temp:format({
    { name = 'id',   type = 'string',    is_nullable = false },
    { name = 'endpoint',  type = 'unsigned',  is_nullable = false },
    { name = 'ts',   type = 'unsigned',  is_nullable = false },
    { name = 'data', type = '*',         is_nullable = false }
})


box.space.temp:create_index('primary', { unique = true, type = 'TREE', parts = { 'endpoint', 'id' }, if_not_exists=true })
box.space.temp:create_index('ts', { unique = false, type = 'TREE', parts = { 'ts' }, if_not_exists=true })


local function upsert()
    box.space.temp:upsert({
        uuid.str(),
        tonumber64(math.random(100000)),
        os.time(),
        {asdf=('x'):rep(10*1024)},
    }, {})
end

box.begin()
for i=1,1e6 do

    upsert()

    if i % 1000 == 0 then
        box.commit()
        box.begin()
    end
end
box.commit()

function isTupleExpired(_, tuple)
    local tsNextTry = tuple['ts']
    return tsNextTry <= os.time()
end

function processExpiredTuple(_, _, tuple)
    local pk
    pk = { tuple['endpoint'], tuple['id'] }

    box.space.temp:delete(pk)
end

function processWhile(task)
    return true
end


expirationd.start('move', box.space.temp.id, isTupleExpired, {
    index = 'ts',
    iterator_type = box.index.LE,
    start_key = function() return os.time() end,
    process_expired_tuple = processExpiredTuple,
    process_while = processWhile,
    tuples_per_iteration = 2048, -- x2 from default
    full_scan_time = 3600, -- default
    force = false,
    args = {}
})

require('console').start() os.exit(0)
```

**Actual behavior**

PMAP total

```
Every 2.0s: pmap -x 58573 | tail                                                                                                                                       vgrubov.novalocal: Mon Sep 27 21:09:40 2021

00007fb609d9f000      28      28       0 r--s- gconv-modules.cache
00007fb609da6000       4       4       4 r---- ld-2.28.so
00007fb609da7000       4       4       4 rw--- ld-2.28.so
00007fb609da8000       4       4       4 rw---   [ anon ]
00007fffb409d000     132      20      20 rw---   [ stack ]
00007fffb4127000      12       0       0 r----   [ anon ]
00007fffb412a000       8       4       0 r-x--   [ anon ]
ffffffffff600000       4       0       0 r-x--   [ anon ]
---------------- ------- ------- -------
total kB         4990188 4019420 4002088
```

Tarantool counters

```
tarantool> box.slab.info()
---
- items_size: 554560
  items_used_ratio: 6.90%
  quota_size: 268435456
  quota_used_ratio: 12.50%
  arena_used_ratio: 3.7%
  items_used: 38288
  quota_used: 33554432
  arena_size: 33554432
  arena_used: 1234320
...
```

```
tarantool> box.info.memory()
---
- cache: 0
  data: 6309327
  index: 287415523
  lua: 1801426
  net: 589824
  tx: 223
...

```

```
tarantool> box.info.vinyl()
---
- tx:
    conflict: 0
    commit: 3003000
    rollback: 0
    statements: 0
    transactions: 0
    gap_locks: 1
    read_views: 0
  regulator:
    dump_bandwidth: 73400320
    rate_limit: 40094196
    dump_watermark: 133636094
    write_rate: 0
  memory:
    tuple_cache: 0
    tx: 221
    level0: 7680063
    page_index: 277054529
    bloom_filter: 7755938
  disk:
    data_compacted: 26418250563
    data: 31285391700
    index: 479002603
  scheduler:
    dump_time: 107.22874427284
    tasks_inprogress: 0
    dump_output: 10624646301
    compaction_queue: 0
    compaction_output: 57076349278
    compaction_time: 559.21584853181
    dump_count: 158
    tasks_failed: 0
    tasks_completed: 6929
    dump_input: 10612451368
    compaction_input: 58083326197
...
```

```
tarantool> box.info.memory()
---
- cache: 0
  data: 4806361
  index: 96368498
  lua: 1919080
  net: 589824
  tx: 223
...
```

Game is over with message

```
tuple_extract_key.cc:181 !> SystemError Failed to allocate 42 bytes in region for tuple_extract_key: Cannot allocate memory
```

**Expected behavior**

Tarantool counter which can describe pmap situation.
