### ISSUE TITLE
Remove zombie fibers from fiber.info()

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#650]
``` 
require('fiber').info()
---
- 0:
    backtrace:
    - '#0  0x491f7f in ?'
    - '#1  0x4c63b7 in ?'
    - '#2  0x41a6a0 in ?'
    fid: 0
    name: zombie
    csw: 19975
```

fiber.info() must not show our internal cache of fibers.
