### ISSUE TITLE
Enrich box.info.gc() verbosity

### ISSUE THREAD

**Issue by sergepetrenko** [tarantool/tarantool#6514]
box.info.gc() output looks as follows:
```yaml
---
- signature: 6
  checkpoint_is_in_progress: false
  consumers:
  - signature: 7
    name: replica 8da17dc5-ab34-46f5-bfc6-302f1a9e8c36
    vclock: {1: 7}
  is_paused: false
  vclock: {1: 6}
  checkpoints:
  - references: []
    vclock: {1: 6}
    signature: 6
  - references: []
    vclock: {1: 7}
    signature: 7
...
```

When a consumer is some replica, like in the example above, it's hard to distinguish replicas by uuid solely.
Let's add a `peer` field to replica consumers.

Also it would be useful to see which file exactly is needed by the consumer: for example, '000.......0007.xlog'.
Even though there's a `signature` field for that, seeing the particular filename would be easier.

Let's also show a full sorted list of files held by this instance in `box.info.gc().files`
