### ISSUE TITLE
symbol resolve broken in packages for ubuntu 14

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#653]
libiberty is part of an own package on ubuntu 14 (libiberty-dev), and no longer a part of binutils-dev as was the case with earlier Debian/Ubuntu distributions.

We need to patch our deb spec to have a dependency on this library on Ubuntu 14, otherwise symbol resolution in backtrace is broken.

**Comment by kostja** [comment]
This is still broken:
```
tarantool> fiber.create(function() while true do fiber.sleep(0) end end)
tarantool> fiber.info()
---
- 102:
    backtrace:
    - '#0  0x482564 in ?'
    - '#1  0x482589 in ?'
    - '#2  0x47872b in ?'
    - '#3  0x4c41d6 in ?'
    fid: 102
    name: lua
    csw: 4980
  101:
    backtrace:
    - '#0  (nil) in ?'
    fid: 101
    name: interactive
    csw: 11
```
