### ISSUE TITLE
Wrong metadata for named bound variable

### ISSUE THREAD

**Issue by ImeevMA** [tarantool/tarantool#6551]
In case a named bound variable is called more than once, the metadata returned for it is incorrect.

Reproducer:
```
parameters = {}
parameters[1] = {}
parameters[1][':a'] = 1
box.execute([[select :a, :a, :a;]], parameters)
```
Result:
```
tarantool> box.execute([[select :a, :a, :a;]], parameters)
---
- metadata:
  - name: COLUMN_1
    type: integer
  - name: COLUMN_2
    type: boolean
  - name: COLUMN_3
    type: boolean
  rows:
  - [1, 1, 1]
...
```

**Comment by ImeevMA** [comment]
Another example of the bug:
```yaml
tarantool> box.execute([[SELECT :a, :a, :a, :b]], {{[':a'] = 123}, {[':b'] = 'asd'}})
---
- metadata:
  - name: COLUMN_1
    type: integer
  - name: COLUMN_2
    type: text
  - name: COLUMN_3
    type: boolean
  - name: COLUMN_4
    type: boolean
  rows:
  - [123, 123, 123, 'asd']
...
```

**Comment by ImeevMA** [comment]
Some more examples of strange behavior:
```yaml
tarantool> box.execute([[select :a, $1;]], {{[':a'] = 123}})
---
- metadata:
  - name: COLUMN_1
    type: integer
  - name: COLUMN_2
    type: boolean
  rows:
  - [123, 123]
...

tarantool> box.execute([[select $1, :a;]], {{[':a'] = 123}})
---
- metadata:
  - name: COLUMN_1
    type: boolean
  - name: COLUMN_2
    type: integer
  rows:
  - [null, 123]
...

tarantool> box.execute([[select $2, :a;]], {321, {[':a'] = 123}})
---
- metadata:
  - name: COLUMN_1
    type: integer
  - name: COLUMN_2
    type: boolean
  rows:
  - [null, 123]
...

tarantool> box.execute([[select :a, $2;]], {321, {[':a'] = 123}})
---
- metadata:
  - name: COLUMN_1
    type: integer
  - name: COLUMN_2
    type: boolean
  rows:
  - [123, null]
...

tarantool> box.execute([[select :a, $1;]], {321, {[':a'] = 123}})
---
- metadata:
  - name: COLUMN_1
    type: integer
  - name: COLUMN_2
    type: boolean
  rows:
  - [123, 123]
...
```
