### ISSUE TITLE
vinyl: replica's initial join consumes much more disk space

### ISSUE THREAD

**Issue by alyapunov** [tarantool/tarantool#6568]
There's a tarantool server in production with a large vinyl space (300GB) in it. The problem happens when we try to join a replica to the cluster. It consumes all available disk space (1TB) and fails to start because of disk error. I saw a lot of message in log about started and successfully finished compaction.

There's also was a lot of rumors that vinyl replica join is very slow (in particular it progressively slows down during join process). It seems for me that it can be connected with the subject.

I don't much about that installation, but I know whom to ask, if something would be important. On that instance `vinyl_memory` was set to 4 gigabytes.
<details>
<summary>Here's the space definition</summary>

```
---
- engine: vinyl
  before_replace: 'function: 0x40615e98'
  field_count: 0
  is_sync: false
  ck_constraint: []
  on_replace: 'function: 0x40615d78'
  temporary: false
  index:
    0: &0
      parts:
      - type: integer
        is_nullable: false
        fieldno: 1
      sequence_id: 1
      options:
        page_size: 8192
        run_count_per_level: 2
        run_size_ratio: 3.5
        bloom_fpr: 0.05
        range_size: 1073741824
      space_id: 515
      unique: true
      type: TREE
      sequence_fieldno: 1
      name: PK
      id: 0
    1: &1
      unique: true
      parts:
      - type: string
        is_nullable: true
        fieldno: 2
      options:
        page_size: 8192
        run_count_per_level: 2
        run_size_ratio: 3.5
        bloom_fpr: 0.05
        range_size: 1073741824
      id: 1
      space_id: 515
      type: TREE
      name: IX_guid
    2: &2
      unique: true
      parts:
      - type: string
        is_nullable: false
        fieldno: 3
      - type: string
        is_nullable: true
        fieldno: 4
      id: 2
      options:
        page_size: 8192
        run_count_per_level: 2
        run_size_ratio: 3.5
        bloom_fpr: 0.05
        range_size: 1073741824
      space_id: 515
      type: TREE
      name: IX_ch_uid
    3: &3
      unique: false
      parts:
      - type: string
        is_nullable: false
        fieldno: 3
      - type: integer
        is_nullable: false
        fieldno: 8
      options:
        page_size: 8192
        run_count_per_level: 2
        run_size_ratio: 3.5
        bloom_fpr: 0.05
        range_size: 1073741824
      id: 3
      space_id: 515
      type: TREE
      name: IX_ch_status
    4: &4
      unique: false
      parts:
      - type: string
        is_nullable: false
        fieldno: 3
      - type: string
        is_nullable: false
        fieldno: 5
      - type: integer
        is_nullable: false
        fieldno: 8
      id: 4
      options:
        page_size: 8192
        run_count_per_level: 2
        run_size_ratio: 3.5
        bloom_fpr: 0.05
        range_size: 1073741824
      space_id: 515
      type: TREE
      name: IX_chp_status
    5: &5
      unique: false
      parts:
      - type: string
        is_nullable: false
        fieldno: 3
      - type: string
        is_nullable: false
        fieldno: 5
      - type: number
        is_nullable: false
        fieldno: 6
      options:
        page_size: 8192
        run_count_per_level: 2
        run_size_ratio: 3.5
        bloom_fpr: 0.05
        range_size: 1073741824
      id: 5
      space_id: 515
      type: TREE
      name: IX_chp_counter
    6: &6
      unique: false
      parts:
      - type: string
        is_nullable: false
        fieldno: 3
      - type: string
        is_nullable: false
        fieldno: 5
      id: 6
      options:
        page_size: 8192
        run_count_per_level: 2
        run_size_ratio: 3.5
        bloom_fpr: 0.05
        range_size: 1073741824
      space_id: 515
      type: TREE
      name: IX_chp
    IX_channelId_uid: *2
    PK: *0
    IX_channelId_phone_status: *4
    IX_channelId_phone: *6
    IX_channelId_status: *3
    IX_guid: *1
    IX_channelId_phone_counter: *5
  is_local: false
  enabled: true
  name: table_name
  id: 515
```
</details>

We should try to reproduce and investigate the problem.
