### ISSUE TITLE
Some nan inconsistencies

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#6572]
I have Ubuntu 20.04. I have Tarantool 2.10, pulled from source today.

The SQL user guide says
https://www.tarantool.io/en/doc/latest/reference/reference_sql/sql_user_guide/
"To represent “nan” (not a number), write an expression that does not result in a real number,
for example 0/0, using Tarantool/NoSQL.  This will appear as NULL in Tarantool/SQL."
Not always.

```
tarantool> box.execute([[SELECT LUA('return 0/0'), TYPEOF(LUA('return 0/0'));]])
---
- metadata:
  - name: COLUMN_1
    type: any
  - name: COLUMN_2
    type: string
  rows:
  - [-nan, 'double']

tarantool> box.execute([[SELECT -LUA('return 0/0'), cast(LUA('return 0/0') AS STRING);]])
---
- metadata:
  - name: COLUMN_1
    type: any
  - name: COLUMN_2
    type: string
  rows:
  - [null, 'NaN']

tarantool> box.execute([[SELECT LUA('return 0/0') IS NULL;]])
---
- metadata:
  - name: COLUMN_1
    type: boolean
  rows:
  - [false]
```

And this fails:
CREATE TABLE k (s1 DOUBLE PRIMARY KEY, s2 DOUBLE);
INSERT INTO k VALUES (lua('return 0/0'), 0);
UPDATE k SET s2 = NULL;
Result:
2021-10-29 11:34:14.234 [39659] main/103/interactive key_def.h:849 E> ER_KEY_PART_TYPE: Supplied key type of part 0 does not match index part type: expected double
(This is interesting because it shows Tarantool is checking the value
of s1 even though we're only trying to change s2. I think that's a
good thing but might irritate a user who has any constraint that
is true during INSERT but false during UPDATE of another column.)

I can change the manual to say "sometimes appears as NULL",
and somebody can ensure that CAST returns 'nan' not 'NaN',
but the important matter is that bad data shouldn't interfere with good,
