### ISSUE TITLE
map is not treated as varbinary

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#6573]
I have Ubuntu 20.04. I have Tarantool 2.10, pulled from source today.

The "flags" field in _vspace is a map, and in version 2.8 we say it is a map.
Starting in version 2.10, we say it is varbinary instead.

```
tarantool> box.execute([[SELECT TYPEOF("flags") FROM "_vspace" LIMIT 1;]])
---
- metadata:
  - name: COLUMN_1
    type: string
  rows:
  - ['varbinary']
```
  
However, Tarantool does not always treat it as varbinary:

SELECT x'00' || "flags" FROM "_space";
Result:
Inconsistent types: expected string or varbinary got map({"group_id": 1})

SELECT SUBSTR("flags",1) FROM "_vspace" limit 1;
Result:
Failed to execute SQL statement: wrong arguments for function SUBSTR()
