### ISSUE TITLE
fiber.info(): nulls in output

### ISSUE THREAD

**Issue by anei** [tarantool/tarantool#666]
fiber.info works very slow and output looks like this:

```
unix/:/var/run/tarantool/node001.control> fiber.info()

---
- - null
  - null
  - null
  - null
[more nulls here]
  - backtrace:
    - '#0  0x42f7da in iproto_queue_handler(__va_list_tag*)+298'
    - '#1  0x494909 in fiber_loop(void*)+41'
    - '#2  0x4c9427 in coro_init+55'
    - '#3  0x41d590 in ?'
    fid: 103
    name: iproto
    csw: 792340
[etc.]
```

See full output here: https://gist.github.com/Anei/548f1550f224bfeb2950

GET!
