### ISSUE TITLE
Duplicate lsns in WAL after restart.

### ISSUE THREAD

**Issue by sergepetrenko** [tarantool/tarantool#6709]
It's possible that a node is killed and started up again before its last transactions are synced to WAL.
If this is the case, the node first reads its vclock from the latest WAL file (by scanning it), and then attemts to recover from the data.

By the time the node finishes recovery the last transactions may already appear in the WAL file, so they are recovered as well. But the node's vclock is never updated after recovery, so it still points to some previous moment in time.

This leads to replication errors once such node subscribes to a remote master (duplicate key found) and to duplicate lsns appearing in WAL.

Example: replica is restarted and it's last WAL looks like
`00000000000437871094.xlog` dump
```
XLOG
0.12
Server: <UUID>
VClock: {1: 16795231, 2: 29577963, 3: 391497900, 4: 0, 5: 0, 6: 0, 7: 0}

...
HEADER:
  lsn: 391498594
  replica_id: 3
  type: DELETE
  timestamp: 1633597422.384
BODY:
  space_id: 515
  key: ['somekey']
...
```
So it should recover with vclock equal to `{1: ..., 2: ..., 3: 391498594, 4: ... }`
Instead it recovers with vclock: `instance vclock {1: 16795231, 2: 29577963, 3: 391498406, 4: 0, 5: 0, 6: 0, 7: 0}`

This vclock is somewhere in the middle of the last WAL (00000000000437871094.xlog).

Replica subscribes to the remote peer with a wrong vclock:

```
2021-10-07 12:07:06.327 [2861] main/107/applier/<ipaddr> I> subscribed
2021-10-07 12:07:06.327 [2861] main/107/applier/<ipaddr> I> remote vclock {1: 16795231, 2: 29577963, 3: 391498594} local vclock {1: 16795231, 2: 29577963, 3: 391498406, 4: 0, 5: 0, 6: 0, 7: 0}
```
This leads to replication breaking with 'duplicate key' error on the first insert:
```
2021-10-07 12:07:06.363 [2861] main/107/applier/<ipaddr> box.cc:325 E> error applying row: {type: 'INSERT', replica_id: 3, lsn: 391498407, space_id: 515, index_id: 0, tuple: [sometuple]}
2021-10-07 12:07:06.364 [2861] main/107/applier/<ipaddr> I> can't read row
2021-10-07 12:07:06.364 [2861] main/107/applier/<ipaddr> memtx_tree.c:478 E> ER_TUPLE_FOUND: Duplicate key exists in unique index 'primary' in space 'spacename'
```

When the replica becomes writeable and starts writing new data, it creates a new WAL with duplicate lsns:

```
XLOG
0.13
Version: 1.10.11-2-ge30b441
Instance: <UUID>
VClock: {1: 16795231, 2: 29577963, 3: 391498406, 4: 0, 5: 0, 6: 0, 7: 0}
PrevVClock: {1: 16795231, 2: 29577963, 3: 391497900, 4: 0, 5: 0, 6: 0, 7: 0}

---
HEADER:
  lsn: 391498407
  replica_id: 3
  type: INSERT
  timestamp: 1633597972.2738
BODY:
  space_id: 515
  tuple: ...

...
```

Judging by the symptoms, replica recovers the data correctly (since it receives a duplicate key error), but fails to update vclock after recovery.
