### ISSUE TITLE
fiber_obj:info() ignores backtrace options

### ISSUE THREAD

**Issue by olegrok** [tarantool/tarantool#7210]
fiber_obj:info() ignores options

https://github.com/tarantool/tarantool/commit/b18dd47f50e817be5ef91013c5514fd6226d836d

```
tarantool> require('fiber').info({backtrace = nil}) -- with backtrace (default)
---
- 101:
    csw: 1
    backtrace:
    - C: '#1  0x561fcc1cf2c4 in lbox_fiber_stall+21'
    - L: '#2  stall in =[C]:-1'
    - L: '#3  (unnamed) in @builtin/fiber.lua:59'
    - C: '#4  0x561fcc25ab92 in lua_pcall+849'
    - C: '#5  0x561fcc1d48f2 in luaT_call+45'
    - C: '#6  0x561fcc1ce4d0 in lua_fiber_run_f+120'
    - C: '#7  0x561fcbf96c57 in fiber_cxx_invoke(int (*)(__va_list_tag*), __va_list_tag*)+34'
    - C: '#8  0x561fcc1ff6a7 in fiber_loop+136'
    - C: '#9  0x561fcca50740 in coro_init+88'
    memory:
      total: 516488
      used: 0
    time: 0
    name: lua
    fid: 101
  103:
    csw: 157
    backtrace:
    - C: '#1  0x561fcc1cdc7d in lbox_fiber_statof_map+836'
    - C: '#2  0x561fcc1cdd8a in lbox_fiber_statof+137'
    - C: '#3  0x561fcc1cddce in lbox_fiber_statof_bt+44'
    - C: '#4  0x561fcc202608 in fiber_stat+89'
    - C: '#5  0x561fcc1ce3cf in lbox_fiber_info+78'
    - L: '#6  pcall in =[C]:-1'
    - L: '#7  eval in @builtin/box/console.lua:404'
    - L: '#8  repl in @builtin/box/console.lua:710'
    - L: '#9  (unnamed) in @builtin/box/console.lua:759'
    - C: '#10 0x561fcc25ab92 in lua_pcall+849'
    - C: '#11 0x561fcc1d48f2 in luaT_call+45'
    - C: '#12 0x561fcc1cc61e in lua_main+189'
    - C: '#13 0x561fcc1cccc1 in run_script_f+1674'
    - C: '#14 0x561fcbf96c57 in fiber_cxx_invoke(int (*)(__va_list_tag*), __va_list_tag*)+34'
    - C: '#15 0x561fcc1ff6a7 in fiber_loop+136'
    - C: '#16 0x561fcca50740 in coro_init+88'
    memory:
      total: 516488
      used: 0
    time: 0
    name: interactive
    fid: 103
  102:
    csw: 0
    backtrace: []
    memory:
      total: 516488
      used: 0
    time: 0
    name: on_shutdown
    fid: 102
...

tarantool> require('fiber').info({backtrace = false}) -- without backtrace
---
- 101:
    csw: 1
    memory:
      total: 516488
      used: 0
    time: 0
    name: lua
    fid: 101
  103:
    csw: 164
    memory:
      total: 516488
      used: 0
    time: 0
    name: interactive
    fid: 103
  102:
    csw: 0
    memory:
      total: 516488
      used: 0
    time: 0
    name: on_shutdown
    fid: 102
...
```

However,
```
tarantool> require('fiber').self().info() -- with backtrace (default)
---
- csw: 243
  backtrace:
  - C: '#1  0x561fcc1cdc7d in lbox_fiber_statof_map+836'
  - C: '#2  0x561fcc1ce8e0 in lbox_fiber_object_info+130'
  - L: '#3  pcall in =[C]:-1'
  - L: '#4  eval in @builtin/box/console.lua:404'
  - L: '#5  repl in @builtin/box/console.lua:710'
  - L: '#6  (unnamed) in @builtin/box/console.lua:759'
  - C: '#7  0x561fcc25ab92 in lua_pcall+849'
  - C: '#8  0x561fcc1d48f2 in luaT_call+45'
  - C: '#9  0x561fcc1cc61e in lua_main+189'
  - C: '#10 0x561fcc1cccc1 in run_script_f+1674'
  - C: '#11 0x561fcbf96c57 in fiber_cxx_invoke(int (*)(__va_list_tag*), __va_list_tag*)+34'
  - C: '#12 0x561fcc1ff6a7 in fiber_loop+136'
  - C: '#13 0x561fcca50740 in coro_init+88'
  memory:
    total: 516488
    used: 0
  time: 0
  name: interactive
  fid: 103
...

tarantool> require('fiber').self().info({backtrace = false}) -- why?
---
- error: 'bad argument #1 to ''?'' (fiber expected, got table)'
...

tarantool> require('fiber').self():info({backtrace = false}) -- expected info without backtrace
---
- csw: 313
  backtrace:
  - C: '#1  0x561fcc1cdc7d in lbox_fiber_statof_map+836'
  - C: '#2  0x561fcc1ce8e0 in lbox_fiber_object_info+130'
  - L: '#3  pcall in =[C]:-1'
  - L: '#4  eval in @builtin/box/console.lua:404'
  - L: '#5  repl in @builtin/box/console.lua:710'
  - L: '#6  (unnamed) in @builtin/box/console.lua:759'
  - C: '#7  0x561fcc25ab92 in lua_pcall+849'
  - C: '#8  0x561fcc1d48f2 in luaT_call+45'
  - C: '#9  0x561fcc1cc61e in lua_main+189'
  - C: '#10 0x561fcc1cccc1 in run_script_f+1674'
  - C: '#11 0x561fcbf96c57 in fiber_cxx_invoke(int (*)(__va_list_tag*), __va_list_tag*)+34'
  - C: '#12 0x561fcc1ff6a7 in fiber_loop+136'
  - C: '#13 0x561fcca50740 in coro_init+88'
  memory:
    total: 516488
    used: 0
  time: 0
  name: interactive
  fid: 103
...
```
