### ISSUE TITLE
Old leader might confirm data not present on new leader

### ISSUE THREAD

**Issue by sergepetrenko** [tarantool/tarantool#7253]
<details><summary>10 step reproducer:</summary>

Run 3 tarantools in 3 consoles and execute the following commands in respective consoles:
```lua
--
-- Instance 1
--

-- Step 1
box.cfg{listen = 3301, replication = {3301,3302,3303}, election_mode = 'candidate', election_fencing_enabled = false, replication_timeout = 10}

-- Step 4
box.schema.user.grant('guest', 'replication')
box.schema.space.create('sync', {is_sync = true})
box.space.sync:create_index('pk')

-- Step 5
box.cfg{replication = ""}

-- Step 9
box.space.sync:insert{1}

--
-- Instance 2
--

-- Step 2
box.cfg{listen=3302, replication={3301,3302,3303}, election_mode='voter', replication_timeout = 10}

--
-- Instance 3
--

-- Step 3
box.cfg{listen=3303, replication={3301,3302,3303}, election_mode='voter', replication_timeout = 10}

-- Step 6
box.cfg{replication = {3302, 3303}}

-- Step 7
box.cfg{election_mode = 'candidate'}

-- Step 8
box.ctl.promote() box.error.injection.set("ERRINJ_WAL_DELAY", true) -- important to do this in one line, whitout yields.

-- Step 10
box.error.injection.set("ERRINJ_WAL_DELAY", false)
```

</details>

After you've performed these 10 steps:
 * Instance 3 is leader
 * Instance 1 and instance 2 output:
```lua
tarantool> box.space.sync:get{1}
---
- [1]
...
```
 * Instance 3 output:
```lua
tarantool> box.space.sync:get{1}
---
...
```

I guess it's already obvious what happened, but still some excerpts from the node WALs for convenience.
<details><summary>Instance 1 xlog</summary>

```
---
HEADER:
  lsn: 9
  replica_id: 1
  type: INSERT
  timestamp: 1654768508.6078
BODY:
  space_id: 512
  tuple: [1]
---
HEADER:
  lsn: 10
  replica_id: 1
  type: CONFIRM
  timestamp: 1654768508.608
BODY:
- null
- 1
- 9
...
```

</details>
<details><summary>Instance 2 xlog</summary>

```
---
HEADER:
  lsn: 9
  replica_id: 1
  type: INSERT
  timestamp: 1654768508.6079
BODY:
  space_id: 512
  tuple: [1]
---
HEADER:
  lsn: 10
  replica_id: 1
  type: CONFIRM
  timestamp: 1654768508.6081
BODY:
- null
- 1
- 9
---
HEADER:
  lsn: 1
  replica_id: 2
  type: PROMOTE
  timestamp: 1654768510.2046
BODY:
  2: 1
  3: 0
  83: 4
...
```

</details>
<details><summary>Instance 3 xlog</summary>

```
---
HEADER:
  lsn: 1
  replica_id: 2
  type: PROMOTE
  timestamp: 1654768508.0623
BODY:
  2: 1
  3: 0
  83: 4
---
HEADER:
  lsn: 9
  replica_id: 1
  type: NOP  <-- this was INSERT
  timestamp: 1654768510.2045
---
HEADER:
  lsn: 10
  replica_id: 1
  type: NOP  <-- this was CONFIRM
  timestamp: 1654768510.2045
...
```

</details>

**Note:** it's not necessary to turn the fencing off on the old leader or disconnect it from everyone to reproduce the issue. It's just easier to reproduce with fencing = off. The same might happen with soft fencing, and even with strict fencing, when manual elections are in play.
**Note:** the issue may be reproduced without the manual elections. When fencing is not strict.

**Issue №1:** new leader doesn't ask the quorum of their actual vclock before writing PROMOTE.
**Issue №2:** even if new leader did so, old leader might always insert and confirm something new while new leader is stuck writing PROMOTE.
**Issue №3:** even if we disallow replication from everyone but the leader (like it's done in canonical Raft), it's still possible that old leader's data enters WAL write on a voter BEFORE vote request from the new leader arrives, but  WAL write confirmation arrives AFTER the voter votes for the new leader. This means that a voter votes for a leader which doesn't have the same data, as voter does.
**Issue №4:** when #5295 is fixed, it will detect this situation, and will force the cluster partition. Moreover, the new leader will be left in a smaller portion of the cluster. Essentially not able to commit anything.

**Proposed steps to fix:**
1. **On all nodes:** do not accept replication from ANY node, whose term is smaller, than ours. This is a compromise between what we had initially (applying replication only from the leader) and what we have now (applying replication from everyone, but nopifying it, when it comes from an old journal term).
2. **On old leader:** freeze the limbo not only during fencing, but always when stepping off. Due to new term, for example. So that the old leader doesn't confirm / rollback some transactions which should be overtaken by the new leader. This will minimise chances of a split-brain.
3. **On followers:** when voting for a candidate, take into account not only `replicaset.vclock`, but `replicaset.applier.vclock`, because the latter might reflect changes that came from an old leader and are now undergoing a WAL write.
