### ISSUE TITLE
SQL result header and column type mismatch

### ISSUE THREAD

**Issue by msiomkin** [tarantool/tarantool#7295]
**Bug description**

The column data type in the result header doesn't match the actual data type

* OS: Linux
* OS Version: Centos 8
* Architecture: amd64

```
Tarantool 2.11.0-entrypoint-109-ga6818accc
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=ON
Compiler: /usr/lib64/ccache/cc /usr/lib64/ccache/c++
C_FLAGS: -fexceptions -funwind-tables -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type
CXX_FLAGS: -fexceptions -funwind-tables -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type
```

**Steps to reproduce**

**Scenario 1**

Run tarantool. Run the following script:

```Lua
box.cfg{}

test1 = box.schema.create_space("test1")

test1:format({
      { name = "id", type = "unsigned" },
      { name = "a", type = "unsigned" },
      { name = "b", type = "unsigned" }
})

test1:create_index("primary")

test1:insert({1, 1, 2})

box.execute([[
    select "a" - "b"
    from "test1"
]])
```

**Actual behavior**

```
---
- metadata:
  - name: COLUMN_1
    type: unsigned
  rows:
  - [-1]
...
```

**Expected behavior**

```
---
- metadata:
  - name: COLUMN_1
    type: integer
  rows:
  - [-1]
...
```

**Scenario 2**

Run tarantool. Run the following script:

```Lua
box.cfg{}

test1 = box.schema.create_space("test1")

test1:format({
      { name = "id", type = "unsigned" },
      { name = "a", type = "unsigned" },
      { name = "b", type = "unsigned" }
})

test1:create_index("primary")

test1:insert({1, 1, 2})

box.execute([[
    select "a" - "b"
    from "test1"
    order by 1
    limit 1
]])
```

**Actual behavior**

```
---
- null
- 'Tuple field 1 (_COLUMN_0) type does not match one required by operation: expected
  unsigned, got integer'
...
```

**Expected behavior**

```
---
- metadata:
  - name: COLUMN_1
    type: integer
  rows:
  - [-1]
...
```
