### ISSUE TITLE
`box.info.replication[i].downstream.lag` is growing indefinitely on an old master

### ISSUE THREAD

**Issue by sergepetrenko** [tarantool/tarantool#7581]
Tarantool version - current master (2.11.0-entrypoint-376-g8f4538cb5)

Steps to reproduce:
1. Start two instances in a replicaset
2. Perform some requests on one of the instances
3. Perform requests on another instance
4. Check `box.info.replication` on the first instance. The `downstream.lag` field will show something similar to time since last request on the first instance instead of the actual lag:
```
    downstream:
      status: follow
      idle: 0.90947299999971
      vclock: {2: 1, 1: 3}
      lag: 15.019683122635
```
