### ISSUE TITLE
Make Flight Recorder use embedded metrics

### ISSUE THREAD

**Issue by DifferentialOrange** [tarantool/tarantool#7728]
The series of tickets about tarantool/metrics embedding is just a beginning of the discussion started with possible Product Team plans related to Flight Recorder development. Expected features may be reevaluated, estimation is preliminary.

Now Flight Recorded uses its own parsing mechanism that needs to be mapped on the metrics module values to display them on default Grafana dashboard. It would be much convenient if they used the same set of metrics so we can reuse things like Grafana dashboard (and not confuse users).

But this is where it all became a little bit tricky. Flight Recorder decided to store derivatives, metrics expose totals.

Exposing precomputed derivatives in case of `metrics` pull drivers -- Prometheus and JSON (used in Telegraf + InfluxDB stands) -- is a bad pattern since it is a guaranteed data loss. I'm not sure it is also possible to use derivatives for push-based drivers without data loss since all push intervals must be the same as derivative computing interval. If it is not expected for Flight Recorder data to be observed explicitly and we will expect that one will always inspect artifacts with Grafana dashboards -- there is no reason to actually store derivatives.

So, the main point of issue will be to answer the question "what format of metrics would satisfy both `metrics` export and Flight Recorder data?". After that, we should provide a smooth (in case of anything would change in public and widely-used `metrics`) migration to new common format.

**Definition of Done**

Flight Recorder calls some export function from embedded `metrics` module and no longer need to provide any additional parsing or extract something from core handles manually. Grafana dashboard could be reused for Flight Recorder data with minimal efforts on rework.

**Comment by DifferentialOrange** [comment]
Current task estimation is based on the following solution:
- provide a common standard for metrics (naming, values) which could be used both in Prometheus exporters and Flight Recorder data,
- implement it together with required smooth migrations.

**Comment by DifferentialOrange** [comment]
> ... (see [RFC](https://www.notion.so/tarantool/FlightRec-RFC-346d61e6c4fd44439f965fcb1f868807)).
> ...
> Names in Flight Recorder are also different now.

Dots in metric names are forbidden by Prometheus data model:
> The metric name specifies the general feature of a system that is measured (e.g. `http_requests_total` - the total number of HTTP requests received). It may contain ASCII letters and digits, as well as underscores and colons. It must match the regex `[a-zA-Z_:][a-zA-Z0-9_:]*`.

See [documentation](https://prometheus.io/docs/concepts/data_model/) and [GitHub issue](https://github.com/prometheus/jmx_exporter/issues/256).

**Comment by DifferentialOrange** [comment]
## Metrics improvements for Flight recorder

See https://github.com/tarantool/metrics/pull/436 and https://github.com/tarantool/metrics/pull/437 for implementation draft.

New export plugin is introduced for flight recorder. To get
- relevant metrics information
- which can be easily exported to Prometheus/json/graphite with existing handles
- with aggregate metrics computed for each kind of metric, like
  - per second rate of change for all monotonic counters,
  - min and max value for all non-monotonic gauges,
  - average values for histograms and summaries
- with all potentially useful information

call `require('metrics.plugins.flight_recorder').export()` to get a Lua table (can be encoded with msgpack)

```
 tnt_stats_op_totalcounter:
    timestamp: 1676627560174944
    name_prefix: tnt_stats_op
    kind: counter
    help: Total amount of operations
    metainfo:
      default: true
    name: tnt_stats_op_total
    observations:
      '':
        "operation\tdelete":
          label_pairs:
            alias: instance-1
            operation: delete
          value: 121672
        "operation\tupsert":
          label_pairs:
            alias: instance-1
            operation: upsert
          value: 236123
  tnt_stats_op_per_secondgauge:
    timestamp: 1676627560174944
    name_prefix: tnt_stats_op
    kind: gauge
    help: Average per second rate of change of tnt_stats_op_total
    metainfo:
      default: true
    name: tnt_stats_op_per_second
    observations:
      '':
        "operation\tdelete":
          label_pairs:
            alias: instance-1
            operation: delete
          value: 3012.251
        "operation\tupsert":
          label_pairs:
            alias: instance-1
            operation: upsert
          value: 5216.734
  http_latencysummary:
    timestamp: 1676627560174944
    name_prefix: http_latency
    kind: summary
    help: Latency of HTTP requests
    metainfo: []
    name: http_latency
    observations:
      sum:
        "code\t200":
          label_pairs:
            alias: instance-1
            code: 200
          value: 2457.567
        "code\t400":
          label_pairs:
            alias: instance-1
            code: 400
          value: 937.76
      count:
        "code\t200":
          label_pairs:
            alias: instance-1
            code: 200
          value: 406182
        "code\t400":
          label_pairs:
            alias: instance-1
            code: 400
          value: 93894
  http_latency_averagegauge:
    timestamp: 1676627560174944
    name_prefix: http_latency
    kind: summary
    help: Average value (over all time) of http_latency
    metainfo: []
    name: http_latency_average
    observations:
      '':
        "code\t200":
          label_pairs:
            alias: instance-1
            code: 200
          value: 0.006
        "code\t400":
          label_pairs:
            alias: instance-1
            code: 400
          value: 0.01
```

Plugin stores a table with previous aggregates. Each `export()` call invokes callbacks, collects metrics, computes aggregates, updates previous aggregates table and returns the output similar to the above one.

Since this format is more suited for code processing (and was built with that in mind), plugin also provides a helper to extract basic info in human-readable format -- `print(require('metrics.plugins.flight_recorder').plain_format(output))`:

```
tnt_stats_op_total{alias=instance-1,operation=delete} 121672
tnt_stats_op_total{alias=instance-1,operation=upsert} 236123
tnt_stats_op_per_second{alias=instance-1,operation=delete} 3012.251
tnt_stats_op_per_second{alias=instance-1,operation=upsert} 5216.734
http_latency_sum{alias=instance-1,code=200} 2457.567
http_latency_sum{alias=instance-1,code=400} 937.76
http_latency_count{alias=instance-1,code=200} 406182
http_latency_count{alias=instance-1,code=400} 93894
http_latency_average{alias=instance-1,code=200} 0.006
http_latency_average{alias=instance-1,code=400} 0.01
```
