### ISSUE TITLE
Replication bug after multiple restart

### ISSUE THREAD

**Issue by Sulverus** [tarantool/tarantool#788]
Reproduction:
Implemented in gh-784 branch
https://github.com/tarantool/tarantool/blob/gh-784/test/recovery/all.test.py

Description:
1.  write something in space
2.  join replica
3.  wait lsn
4.  restart master, restart replica
5.  repeat x2+

Trace:
```
103:
    backtrace:
    - '#0  0x4904aa in fiber_yield()+189'
    - '#1  0x4905b0 in fiber_yield_timeout(double)+146'
    - '#2  0x46e0fe in coio_fiber_yield_timeout(ev_io*, double)+57'
    - '#3  0x46ef24 in coio_read_ahead_timeout(ev_io*, void*, unsigned long, unsigned
      long, double)+345'
    - '#4  0x46e069 in coio_read_ahead(ev_io*, void*, unsigned long, unsigned long)+61'
    - '#5  0x46efd5 in coio_readn_ahead(ev_io*, void*, unsigned long, unsigned long)+53'
    - '#6  0x4300d2 in coio_breadn(ev_io*, ibuf*, unsigned long)+78'
    - '#7  0x4301ac in remote_read_row(ev_io*, iobuf*, xrow_header*)+83'
    - '#8  0x430bb0 in pull_from_remote(__va_list_tag*)+472'
    - '#9  0x490998 in fiber_loop(void*)+115'
    - '#10 0x606538 in coro_init+76'
    - '#11 0x41f440 in ?'
    fid: 103
    name: replica/localhost:4257
    csw: 6
```
