### ISSUE TITLE
mvcc shouldn't work on a replication stream

### ISSUE THREAD

**Issue by sergepetrenko** [tarantool/tarantool#8121]
Reproduced on latest master (2.11.0-entrypoint-850-g182034dc9)

**Bug description**
Run 2 Tarantool instances in console:
```lua
-- Instance 1.
-- Step 1.
box.cfg{
    listen = 3301,
    memtx_use_mvcc_engine = true,
    txn_isolation = 'read-confirmed',
}

box.once('bootstrap', function()
    box.schema.user.grant('guest', 'replication')
    box.schema.space.create('test')
    box.space.test:create_index('pk')
    box.space.test:insert{1}
end)

-- Step 3.
box.space.test:delete{1}
box.space.test:delete{1}

-- Instance 2.
-- Step 2.
box.cfg{replication = 3301, memtx_use_mvcc_engine = true, txn_isolation = 'read-confirmed'}
box.cfg{replication = ""}

-- Step 4.
box.cfg{replication = 3301}
```

After these steps the replica will disconnect from master with an `ER_TRANSACTION_CONFLICT` error.
It's box.info.replication will read:
```
tarantool> box.info.replication
---
- 1:
    id: 1
    uuid: 95005d25-21b3-42cb-8eb8-9aed62f35771
    lsn: 8
    upstream:
      peer: '3301'
      lag: 0.00046181678771973
      status: stopped
      idle: 4.4793854899999
      message: Transaction has been aborted by conflict
  2:
    id: 2
    uuid: e00fad89-c417-4d39-af1c-e6b7197ea38b
    lsn: 0
...

```

The reason for this is that from master's point of view the deletes were run sequentially, but for replica they were concurrent: that's because replica applies transactions in parallel: commits them asynchronously not waiting for a wal write to complete.

It seems mvcc shouldn't work on a replication stream. At least when this stream comes from a single master. Because having transactions in master's WAL means there were no conflicts when master committed them.
