### ISSUE TITLE
YAML serializer doesn't detect aliases in table returned by `__serialize` meta method

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#8240]
Reproduced with Tarantool 2.11.0-entrypoint-959-gfb8d98614652. Tarantool 2.10 is affected as well.

YAML serializer (used by default in Tarantool console) supports aliasing to produce more compact output:

```
tarantool> x = {}
---
...

tarantool> {a = x, b = x}
---
- a: &0 []
  b: *0
...
```

This is useful when dumping space indexes to the console:

```
tarantool> box.space._schema.index
---
- 0: &0
    unique: true
    parts:
    - type: string
      is_nullable: false
      fieldno: 1
    hint: true
    id: 0
    type: TREE
    space_id: 272
    name: primary
  primary: *0
...
```

However, this feature doesn't seem to work for a table returned by the `__serialize` meta method:

```
tarantool> setmetatable({}, {__serialize = function() return {a = x, b = x} end})
---
- a: []
  b: []
...
```

Funny fact: aliasing is detected if the aliased table is referenced in the original table:

```
tarantool> setmetatable({c = x}, {__serialize = function() return {a = x, b = x} end})
---
- a: []
  b: []
...

tarantool> setmetatable({c = x, d = x}, {__serialize = function() return {a = x, b = x} end})
---
- a: &0 []
  b: *0
...
```
