### ISSUE TITLE
Inconsistency between Lua and C configuration in case of integer parameters

### ISSUE THREAD

**Issue by nshy** [tarantool/tarantool#8255]
Some configuration parameters are integers. In `box.cfg()` we can only check that their type is `number` and then typically use `cfg_geti` to get value in C code. As result fractional part is truncated which can lead to unexpected results as in https://github.com/tarantool/tarantool-ee/issues/359

Let's consider `cfg_geti` to fail if value has fractional part (it is a breaking change generally speaking).

**Comment by Totktonada** [comment]
There is a proposal (AFAIR, it is originated from @Mons) to leave `box.cfg()` behavior unchanged, but reflect the integer/number difference in an upcoming declarative configuration processing (#8724).

There are several integer options, for example the following ones.

https://github.com/tarantool/tarantool/blob/852664b4ddb021384d087b6ec57c5c3dbd49276c/src/box/lua/config/instance_config.lua#L602-L617

https://github.com/tarantool/tarantool/blob/852664b4ddb021384d087b6ec57c5c3dbd49276c/src/box/lua/config/instance_config.lua#L681-L686

And they're validated to don't have a fractional part:

https://github.com/tarantool/tarantool/blob/852664b4ddb021384d087b6ec57c5c3dbd49276c/test/config-luatest/schema_test.lua#L525-L539

You can verify it using the following steps.

1. Pick up our simplest example:

   https://github.com/tarantool/tarantool/blob/852664b4ddb021384d087b6ec57c5c3dbd49276c/doc/examples/config/single.yaml#L1-L14

2. Add an invalid option:

   ```yaml
   credentials:
     users:
       guest:
         roles: [super]

   iproto:
     listen: 'unix/:./{{ instance_name }}.iproto'

   groups:
     group-001:
       replicasets:
         replicaset-001:
           instances:
             instance-001:
               memtx:
                 memory: 1000000000.5 # !!
   ```

3. Try to start the given instance.

   > $ tarantool --name instance-001 --config doc/examples/config/single.yaml
   > LuajitError: [cluster_config] groups.group-001.replicasets.replicaset-001.instances.instance-001.memtx.memory: Unexpected data for scalar "integer": Expected number without a fractional part, got 1000000000.5
   > fatal error, exiting the event loop

Alternatively you can leave the example unchanged and pass the same option from an environment variable:

> $ TT_MEMTX_MEMORY=1000000000.5 tarantool --name instance-001 --config doc/examples/config/single.yaml
> LuajitError: Unable to decode an integer value from environment variable "TT_MEMTX_MEMORY", got "1000000000.5"
> fatal error, exiting the event loop
