### ISSUE TITLE
yaml: unnecessary anchors

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#8350]
Tarantool version: 2.11.0-entrypoint-1037-gbf8b76a4d.

```yaml
Tarantool 2.11.0-entrypoint-1037-gbf8b76a4d
type 'help' for interactive help
tarantool> require('tarantool')
---
- build: &0
    target: Linux-x86_64-Debug
    options: cmake . -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_BACKTRACE=TRUE
    linking: dynamic
    mod_format: so
    flags: -march=native -O2 -ggdb -fexceptions -funwind-tables -fasynchronous-unwind-tables
      -fno-common -fopenmp -msse2 -mavx -Wformat -Wformat-security -Werror=format-security
      -fstack-protector-strong -fPIC -fmacro-prefix-map=/var/tmp/portage/dev-db/tarantool-9999/work/tarantool-9999=.
      -std=c11 -Wall -Wextra -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type
      -Werror
    compiler: GNU-12.2.1
  package: Tarantool
  debug: &1
    getsources: 'function: 0x40fcd508'
  uptime: 'function: 0x408364d8'
  version: 2.11.0-entrypoint-1037-gbf8b76a4d
  pid: 'function: 0x408364f8'
...
```

`build` and `debug` are anchored, but not present second time in the output.
