### ISSUE TITLE
Support obtaining column name or column ID through the bound variable in ORDER BY and GROUP BY.

### ISSUE THREAD

**Issue by ImeevMA** [tarantool/tarantool#8413]
Let's say that we already have executed these queries:
```
box.execute([[create table t(i int primary key, a int);]])
box.execute([[insert into t values(1,5), (2,4), (3,3);]])
```

Then the following queries work as intended:
```
tarantool> box.execute([[select -i as i1, a from t order by i1;]])
---
- metadata:
  - name: I1
    type: integer
  - name: A
    type: integer
  rows:
  - [-3, 3]
  - [-2, 4]
  - [-1, 5]
...

tarantool> box.execute([[select -i, a from t order by a desc;]])
---
- metadata:
  - name: COLUMN_1
    type: integer
  - name: A
    type: integer
  rows:
  - [-1, 5]
  - [-2, 4]
  - [-3, 3]
...
```

Queries with bound variables do not work as expected:
```
tarantool> box.execute([[select -i, a from t order by ?;]], {'i1'})
---
- metadata:
  - name: COLUMN_1
    type: integer
  - name: A
    type: integer
  rows:
  - [-1, 5]
  - [-2, 4]
  - [-3, 3]
...

tarantool> box.execute([[select -i, a from t order by ?;]], {2})
---
- metadata:
  - name: COLUMN_1
    type: integer
  - name: A
    type: integer
  rows:
  - [-1, 5]
  - [-2, 4]
  - [-3, 3]
...
```

And in some cases, it can even return an unexpected result:
```
tarantool> box.execute([[select i, a from t order by :a;]], {{[':a'] = {1}}})
---
- metadata:
  - name: I
    type: integer
  - name: A
    type: integer
  rows:
  - [3, 3]
  - [2, 4]
  - [1, 5]
...
```

We should most likely only allow string and integer values for bound variables used as ORDER BY and GROUP BY arguments, and make them work the way literal integers and strings currently work.
