### ISSUE TITLE
`box.stat.memtx` is inconsistent with other statistics

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#8448]
Reproduced with Tarantool 3.0.0-entrypoint-69-ge13b0d4ae1e0.
Tarantool 2.10 and 2.11 are affected as well.

`box.stat()`, `box.stat.net()`, `box.stat.vinyl()`, `box.stat.sql()` are functions but `box.stat.memtx` isn't. This is confusing.

<details>

```
tarantool> _ = box.stat()
---
...

tarantool> _ = box.stat.net()
---
...

tarantool> _ = box.stat.sql()
---
...

tarantool> _ = box.stat.vinyl()
---
...

tarantool> _ = box.stat.memtx()
---
- error: '[string "_ = box.stat.memtx()"]:1: attempt to call field ''memtx'' (a table
    value)'
...
```

</details>

Overall, `box.stat.memtx` object behavior looks weird.

<details>

```
tarantool> box.stat.memtx
---
- tx: []
...

tarantool> box.stat.memtx.tx
---
- []
...

tarantool> box.stat.memtx.tx()
---
- txn:
    statements:
      max: 0
      avg: 0
      total: 0
    user:
      max: 0
      avg: 0
      total: 0
    system:
      max: 0
      avg: 0
      total: 0
  mvcc:
    trackers:
      max: 0
      avg: 0
      total: 0
    conflicts:
      max: 0
      avg: 0
      total: 0
    tuples:
      tracking:
        stories:
          count: 0
          total: 0
        retained:
          count: 0
          total: 0
      used:
        stories:
          count: 0
          total: 0
        retained:
          count: 0
          total: 0
      read_view:
        stories:
          count: 0
          total: 0
        retained:
          count: 0
          total: 0
...

tarantool> box.stat.memtx
---
- tx:
    txn:
      statements:
        max: 0
        avg: 0
        total: 0
      user:
        max: 0
        avg: 0
        total: 0
      system:
        max: 0
        avg: 0
        total: 0
    mvcc:
      trackers:
        max: 0
        avg: 0
        total: 0
      conflicts:
        max: 0
        avg: 0
        total: 0
      tuples:
        tracking:
          stories:
            count: 0
            total: 0
          retained:
            count: 0
            total: 0
        used:
          stories:
            count: 0
            total: 0
          retained:
            count: 0
            total: 0
        read_view:
          stories:
            count: 0
            total: 0
          retained:
            count: 0
            total: 0
...
```

</details>

`box.stat.memtx` first appeared in 2.10.0-beta2-259-g5a99429f8cf2 and hasn't been documented yet, see https://github.com/tarantool/doc/issues/2801.
