### ISSUE TITLE
Truncation ignored when casting into varchar

### ISSUE THREAD

**Issue by aatolstoy** [tarantool/tarantool#8644]
Hello,
I found out that using CAST() with `varchar` in Tarantool doesn't truncate the  result as expected, i.e. the X in `varchar(X)` is ignored.
How to reproduce:
```
tarantool> box.execute([[select cast('hello' as varchar(3))]])
---
- metadata:
  - name: COLUMN_1
    type: string
  rows:
  - ['hello']
```
The issue was reproduced at least with Tarantool 2.8 & 2.10
