### ISSUE TITLE
Hide useless error fields from unpack output

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#9101]
[Link to the design document](https://www.notion.so/tarantool/Error-subsystem-improvements-90faa0a4714b4143abaf8bed2c10b2fc?pvs=4#3f1a17a9673f408eaba2cdef28890886)

Some error fields only clutter the [`unpack`](https://www.tarantool.io/en/doc/latest/reference/reference_lua/box_error/error_object/#lua-function.error_object.unpack) output and bear no useful information:

- `custom_type` - not set for Tarantool errors; same as `type` for user-defined errors.
- `base_type` - same as `type` for Tarantool errors; `CustomError` for user-defined errors.
- `code` - only makes sense if it’s set; 0 if unset.

Suggestion:

- Hide `custom_type` and `base_type` from `unpack` output.
- Hide `code` from `unpack` output if it’s 0.

Before:

```yaml
tarantool> box.error.new{type = 'MyError', reason = 'foobar'}:unpack()
---
- code: 0
  base_type: CustomError
  type: MyError
  custom_type: MyError
  message: foobar
  trace:
  - file: '[string "return box.error.new{type = ''MyError'', reason..."]'
    line: 1
...
```

After:

```yaml
tarantool> box.error.new{type = 'MyError', reason = 'foobar'}:unpack()
---
- type: MyError
  message: foobar
  trace:
  - file: '[string "return box.error.new{type = ''MyError'', reason..."]'
    line: 1
...
```

The fields may still be accessed via the `.` operator of an error object, just like before. In case of `code` it means that if the code is 0, `e.code` will return 0, not `nil`.

Comment from Vladislav Shpilevoy re `base_type`:

> `base_type` was exposed to allow people get the real error type in case a user is trying to mimic `ClientError` or `SystemError` or something else internal using the custom type field.
> 

However, since we only hide `base_type` from the `unpack` output, not delete it completely, one can still figure out if an error is a true system error by accessing `base_type` via the `.` operator so removing it from the `unpack` output seems to be acceptable.

Since this may potentially break existing users, we’ll introduce the new [`compat`](https://www.tarantool.io/en/doc/latest/reference/reference_lua/compat/) module option `box_error_unpack_type_and_code` to revert to the old behavior.
