### ISSUE TITLE
CONFIRM without quorum leads to split-brain error

### ISSUE THREAD

**Issue by lowitea** [tarantool/tarantool#9138]
## My case:

There is a cartridge cluster with a storage replicaset with three nodes.

All spaces are in sync mode.

Stateful failover with etcd is enabled.

Election mode is manual. Function `box.ctl.promote()` is called inside `apply_config` if the node is the master.

During high load, the cpu ran out and a master in the replicaset stuck. The failover decided to switch the master. The new master also got stuck. And there were several such switches. At some point, the error "Split-Brain discovered: got a request from a foreign synchro queue owner" appeared in the replicaset.

## Possible cause:

A node while it was a master wrote a transaction in WAL and began obtaining quorum. At that moment master switching occurred, but the node managed to obtain quorum and write CONFIRM in its WAL. After writing, the node sent the WAL entry to other nodes in replicaset in which the limbo owner had already been changed.

<details> 
  <summary>screenshots</summary>
  Errors in Cartridge UI  

  <img src="https://github.com/tarantool/tarantool/assets/24208500/26b5cee6-e7f9-4c13-9456-cdf6abe3834e">
  
  storage-9-1  

  ![Pasted image 20230913132200](https://github.com/tarantool/tarantool/assets/24208500/b9f4cfff-9838-46a8-b005-7fa35c48313e)
  
  storage-9-2  

  ![Pasted image 20230913132209](https://github.com/tarantool/tarantool/assets/24208500/d415ca17-10ba-4921-810c-679d4e88b834)
  
  storage-9-3  

  ![Pasted image 20230913132221](https://github.com/tarantool/tarantool/assets/24208500/9904994e-aff6-4f6d-be08-405e15b7b71d)
</details>

Last WAL entries
```
---
HEADER:
  lsn: 85936
  replica_id: 3
  type: CONFIRM
  timestamp: 1694197746.2396
BODY:
- null
- 3
- 85930
---
HEADER:
  lsn: 85937
  replica_id: 3
  type: CONFIRM
  timestamp: 1694197747.5981
BODY:
- null
- 3
- 85935
...
```

* OS: RockyLinux
* OS Version: 8.5
* Architecture: amd64

Tarantool 2.11.0
