### ISSUE TITLE
Raft leader should step off when encounters ER_WAL_IO

### ISSUE THREAD

**Issue by sergepetrenko** [tarantool/tarantool#9399]
**Bug description**

Raft leader continues to send heartbeats even if it can't write anything, so it is seen by others as alive. As a result, once the leader encounters a disk error, it can't write anything, but the elections do not start.

**Steps to reproduce**

1. Start 3 nodes with `election_mode = 'candidate'`, grant necessary replication privileges
2. On the first chosen leader, issue `box.error.injection.set("ERRINJ_WAL_WRITE", true)`
3. Try to write something, for example:
```
tarantool> box.space._schema:replace{'a'}
2023-11-24 11:01:34.565 [13307] wal/101/main xlog.c:1276 E> ER_INJECTION: Error injection 'xlog write injection'
2023-11-24 11:01:34.565 [13307] main/103/interactive txn.c:1069 E> ER_WAL_IO: Failed to write to disk
---
- error: Failed to write to disk
...

```
4. Check `box.info.election` and `box.info.replication` on the leader. Nothing changes:
```
tarantool> box.info.election
---
- leader_idle: 0
  leader_name: null
  state: leader
  vote: 1
  term: 2
  leader: 1
...

tarantool> box.info.replication
---
- 1:
    id: 1
    uuid: 676834e6-1c9d-426d-92a5-419fa8087424
    lsn: 4
    name: null
  2:
    id: 2
    uuid: 6a8132e2-1ffa-4818-92f4-6caad586709c
    lsn: 0
    upstream:
      status: follow
      idle: 0.78926000000001
      peer: '3303'
      lag: 0.00019121170043945
    name: null
    downstream:
      status: follow
      idle: 0.81881099999964
      vclock: {1: 4}
      lag: 0.00066828727722168
  3:
    id: 3
    uuid: e7dece36-6ae9-46b3-9967-bf3afedfe950
    lsn: 0
    upstream:
      status: follow
      idle: 0.75874699999986
      peer: '3302'
      lag: 0.00017905235290527
    name: null
    downstream:
      status: follow
      idle: 0.7589109999999
      vclock: {1: 4}
      lag: 0
...

```

Reported as part of #9383
