### ISSUE TITLE
ER_PROTOCOL in relay when replicating transactions with last local row

### ISSUE THREAD

**Issue by sergepetrenko** [tarantool/tarantool#9491]
**Bug description**

Replication is broken on replica reconnect if master writes transactions where last row is local while the replica doesn't follow.

Tarantool version:

**Steps to reproduce**

Run two tarantool instances iteractively in clean directories.
```lua
-- Instance 1.
-- Step 1.
box.cfg{listen=3301}
box.schema.user.grant('guest', 'replication')
box.schema.space.create('glob'):create_index('pk')
box.schema.space.create('loc', {is_local=true}):create_index('pk')

-- Step 4.
box.begin() box.space.glob:replace{1} box.space.loc:replace{1} box.commit()
box.space.glob:replace{2}

-- Instance 2.
-- Step 2.
box.cfg{replication=3301}
-- Step 3.
box.cfg{replication=""}

-- Step 5.
box.cfg{replication=3301}
```
After step 5 replication won't start. Logs on both instances will contain the following error:
```
ER_PROTOCOL: Found a new transaction with previous one not yet committed
```
And `box.info.replication` on replica will show
```
tarantool> box.info.replication
---
- 1:
    id: 1
    uuid: 5b636832-905c-4ed3-98cc-5d17448a3ccf
    lsn: 6
    upstream:
      peer: '3301'
      lag: 0.00042891502380371
      status: stopped
      idle: 686.26692
      message: Found a new transaction with previous one not yet committed
  2:
    id: 2
    uuid: fc8d7386-bd1b-43e0-98db-4fd2edadb91d
    lsn: 0
...
```
