### ISSUE TITLE
config: grab passwords from env/file

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#9506]
We should give a user ability to hide passwords from config.

@R-omk proposed a structure like the following.

```yaml
config:
  context:
    myvar_1:
      from: env
      env: MYVAR_1
    myvar_2:
      from: file
      file: path/to/file # relative to process.work_dir

credentials:
  users:
    myuser_1:
      password: '{{ context.myvar_1 }}'
    myuser_2:
      password: '{{ context.myvar_2 }}'
```
