### ISSUE TITLE
config: fail to start replicaset with uuids specified

### ISSUE THREAD

**Issue by Serpentian** [tarantool/tarantool#9572]
Take the following config:

```yaml
credentials:
  users:
    client:
      password: 'secret'
      roles: [super]
    replicator:
      password: 'secret'
      roles: [replication]
 
iproto:
  listen:
    - uri: unix/:./var/run/{{ instance_name }}/tarantool.iproto
  advertise:
    peer:
      login: replicator

groups:
  storages:
    replication:
      failover: manual
    replicasets:
      storage-001:
        database:
          replicaset_uuid: '11111111-1111-1111-0011-111111111111'
        leader: storage-001-a
        instances:
          storage-001-a:
            database:
              instance_uuid: '22222222-2222-2222-0022-222222222222'
          storage-001-b:
            database:
              instance_uuid: '33333333-3333-3333-0033-333333333333
```

Leader fails to start with:

```
2023-12-28 17:34:58.397 [262582] main utils.c:679 E> LuajitError: builtin/config/applier/box_cfg.lua:192: attempt to index a nil value
```

Reported by @askalt.
