### ISSUE TITLE
config: delayed privilege grant/revoke doesn't clear an alert

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#9574]
Let's consider the following simple config.

```yaml
credentials:
  users:
    guest:
      roles: [super]
      privileges:
      - permissions: [read, write]
        spaces: [s]

iproto:
  listen:
  - uri: 'unix/:./var/run/{{ instance_name }}/tarantool.iproto'

app:
  file: app.lua

groups:
  group-001:
    replicasets:
      replicaset-001:
        instances:
          instance-001: {}
```

And run it with the following application (`app.lua`).

```lua
box.once('app', function()
    box.schema.space.create('s')
    box.space.s:create_index('pk')
end)
```

Next, start the instance.

```sh
./src/tarantool --name instance-001 --config config.yaml
```

And connect to the admin console.

```sh
tt connect ./var/run/instance-001/tarantool.control
```

Check the space and the privileges.

```yaml
# ./var/run/instance-001/tarantool.control> box.schema.user.info('guest')
---
- - - execute
    - role
    - public
  - - execute
    - role
    - super
  - - read,write
    - space
    - s
  - - session,usage
    - universe
    - 
...
```

`read, write` on space `s` is granted, everything is OK.

But,

```yaml
# ./var/run/instance-001/tarantool.control> require('config'):info()
---
- status: check_warnings
  meta: []
  alerts:
  - type: warn
    message: 'credentials.apply: space "s" hasn''t been created yet, ''box.schema.user.grant("guest",
      "read,write", "space", "s")'' will be applied later'
    timestamp: 2023-12-29T02:44:11.898258+0300
...
```
