### ISSUE TITLE
config: all except one delayed privilege alerts are missing

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#9586]
Let's consider the following config.

```yaml
credentials:
  users:
    guest:
      roles: [super]
      privileges:
      - permissions: [read, write]
        spaces: [s, t]
      - permissions: [execute]
        functions: [f, g]

iproto:
  listen:
  - uri: 'unix/:./var/run/{{ instance_name }}/tarantool.iproto'

groups:
  group-001:
    replicasets:
      replicaset-001:
        instances:
          instance-001: {}
```

Here we have privileges for spaces `s`, `t` and functions `f`, `g` to be granted at their creation.

However, the warning about delayed privilege granting is issued only for `f`.

```sh
$ tarantool --name instance-001 --config config.yaml
```

```sh
$ tt connect ./var/run/instance-001/tarantool.control
```

```yaml
# tarantool> require('config'):info()
# tarantool> config:info()
---
- status: check_warnings
  meta: []
  alerts:
  - type: warn
    message: 'credentials.apply: function "f" hasn''t been created yet, ''box.schema.user.grant("guest",
      "execute", "function", "f")'' will be applied later'
    timestamp: 2024-01-10T15:39:25.478785+0300
...
```

Looks like a regression from fa97cc0c12e9f9c051e7455c71d8be264a50d554.
