### ISSUE TITLE
Allow to retrieve cluster config with `config` module

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#9680]
The `config` module allows to get the current instance config. However, it's impossible to get the config of the cluster this instance is a part of. This would be really useful for implementing application sharding: an instance representing a router needs to know the list of all replica-sets and instances representing data shards so that the application developer wouldn't need to specify all the shard uris in the role config. Please extend the `config` module with this functionality. The `apply` method of the role should be able to fetch the actual (applied) configuration of the whole cluster.

**Comment by Totktonada** [comment]
For a while I can propose a workaround based on an internal API.

<details>
<summary><code>config.yaml</code></summary>

```yaml
credentials:
  users:
    replicator:
      password: secret
      roles: [replication]
    client:
      password: secret
      roles: [super]

iproto:
  listen:
  - uri: 'unix/:./{{ instance_name }}.iproto'
  advertise:
    peer:
      login: 'replicator'

replication:
  failover: election

roles: [foo]

groups:
  group-001:
    replicasets:
      replicaset-001:
        instances:
          instance-001: {}
          instance-002: {}
          instance-003: {}
      replicaset-002:
        instances:
          instance-004: {}
          instance-005: {}
          instance-006: {}
  group-002:
    replicasets:
      replicaset-003:
        instances:
          instance-007: {}
          instance-008: {}
          instance-009: {}
      replicaset-004:
        instances:
          instance-010: {}
          instance-011: {}
          instance-012: {}
```
</details>

<details>
<summary><code>Procfile</code> (if you're using <code>foreman</code> or <code>honcho</code>)</summary>

```procfile
instance-001: tarantool --config config.yaml --name instance-001
instance-002: tarantool --config config.yaml --name instance-002
instance-003: tarantool --config config.yaml --name instance-003
instance-004: tarantool --config config.yaml --name instance-004
instance-005: tarantool --config config.yaml --name instance-005
instance-006: tarantool --config config.yaml --name instance-006
instance-007: tarantool --config config.yaml --name instance-007
instance-008: tarantool --config config.yaml --name instance-008
instance-009: tarantool --config config.yaml --name instance-009
instance-010: tarantool --config config.yaml --name instance-010
instance-011: tarantool --config config.yaml --name instance-011
instance-012: tarantool --config config.yaml --name instance-012
```
</details>

<details>
<summary><code>foo.lua</code> (a role)</summary>

```lua
local config = require('config')
local log = require('log')

local instance_config = require('internal.config.instance_config')
local cluster_config = require('internal.config.cluster_config')

config.cconfig = function(self)
    local res = self._configdata_applied._cconfig
    assert(res ~= nil)
    return res
end

config.instances = function(self)
    local res = {}

    for group_name, group in pairs(self:cconfig().groups or {}) do
        for replicaset_name, replicaset in pairs(group.replicasets or {}) do
            for instance_name, _ in pairs(replicaset.instances or {}) do
                table.insert(res, {
                    instance_name = instance_name,
                    replicaset_name = replicaset_name,
                    group_name = group_name,
                })
            end
        end
    end

    return res
end

config.get = function(self, path, opts)
    local instance
    if opts ~= nil and opts.instance ~= nil then
        instance = opts.instance
    else
        instance = config._instance_name
    end

    local cconfig = self:cconfig()
    local found = cluster_config:find_instance(cconfig, instance)
    if found == nil then
        error(('Unknown instance %q'):format(instance))
    end

    local iconfig = cluster_config:instantiate(cconfig, instance)
    iconfig = instance_config:apply_default(iconfig)
    iconfig = instance_config:apply_vars(iconfig, {
        instance_name = instance,
        replicaset_name = found.replicaset_name,
        group_name = found.group_name,
    })

    return instance_config:get(iconfig, path)
end

local function apply()
    for _, def in ipairs(config:instances()) do
        local iproto_listen = config:get('iproto.listen', {instance = def.instance_name})
        log.info('%s %s %s %s', def.instance_name, def.replicaset_name,
            def.group_name, iproto_listen[1].uri)
    end
end

return {
    validate = function() end,
    apply = apply,
    stop = function() end,
}
```
</details>
