### ISSUE TITLE
Unexpected config status during startup and unexpected config status after applying credentials

### ISSUE THREAD

**Issue by ImeevMA** [tarantool/tarantool#9689]
Currently it is possible to get `check_errors` status during startup:
Config:
```yaml
credentials:
  users:
    guest:
      roles: [super]
    someone:
      privileges:
      - permissions: [execute]
        spaces: [first]

log:
  level: 0

iproto:
  listen:
  - uri: 'unix/:./{{ instance_name }}.iproto'

groups:
  group-001:
    replicasets:
      replicaset-001:
        instances:
          instance-001: {}
```
Reproducer:
```yaml
started
tarantool> require('config'):info()
---
- status: check_errors
  meta: []
  alerts:
  - type: error
    message: 'credentials.apply: box.schema.user.grant("someone", "execute", "space",
      "first") failed: Unsupported space privilege ''execute'''
    timestamp: 2024-02-14T13:42:59.431903+0300
  - type: warn
    message: box.schema.user.grant("someone", "execute", "space", "first") has failed
      because either the object has not been created yet, or the privilege write has
      failed (separate alert reported)
    timestamp: 2024-02-14T13:42:59.432832+0300
...

```

It is also possible to get the status `ready` while simultaneously having pending alerts:
Config:
```yaml
credentials:
  users:
    guest:
      roles: [super]
    someone:
      privileges:
      - permissions: [read]
        spaces: [first, second]

log:
  level: 0

iproto:
  listen:
  - uri: 'unix/:./{{ instance_name }}.iproto'

groups:
  group-001:
    replicasets:
      replicaset-001:
        instances:
          instance-001: {}
```
Reproducer:
```yaml
started
tarantool> require('config'):info()
---
- status: check_warnings
  meta: []
  alerts:
  - type: warn
    message: box.schema.user.grant("someone", "read", "space", "second") has failed
      because either the object has not been created yet, or the privilege write has
      failed (separate alert reported)
    timestamp: 2024-02-14T13:37:53.375946+0300
  - type: warn
    message: box.schema.user.grant("someone", "read", "space", "first") has failed
      because either the object has not been created yet, or the privilege write has
      failed (separate alert reported)
    timestamp: 2024-02-14T13:37:53.375959+0300
...

tarantool> _ = box.schema.space.create('first')
---
...

tarantool> require('config'):info()
---
- status: ready
  meta: []
  alerts:
  - type: warn
    message: box.schema.user.grant("someone", "read", "space", "second") has failed
      because either the object has not been created yet, or the privilege write has
      failed (separate alert reported)
    timestamp: 2024-02-14T13:37:58.733120+0300
...
```
