### ISSUE TITLE
config: add labels to schema 

### ISSUE THREAD

**Issue by Lord-KA** [tarantool/tarantool#9809]
Sometimes it is useful for end user or application to consider tags or labels set for the instance. In a [private discussion](https://www.notion.so/tarantool/b7a2c5a9dc0c4ef6a8de923f5c560ff3) it was decided to implement labels as a simple `schema.map[string]string` similar to cartridge:

```yaml
# New 3.1 top level field.
labels:
  zone: msk
  color: fuchsia
```

Note that `schema.map` are merged as sets:
```yaml
groups:
  g-1:
    replicasets:
      r-1:
        labels:
          foo: 'true'
          bar: 'true'
      instances:
        i-1:
          labels: # result -> [{bar: 'true', baz: 'true', foo: 'false'}]
            baz: 'true'
            foo: 'false'
```
