### ISSUE TITLE
Add functions for validation and comparison keys to `key_def` module

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#9863]
There are no functions to validate a key and compare two keys in the `key_def` module:

```yaml
tarantool> key_def
---
- merge: 'function: 0x40e6e2d8'
  extract_key: 'function: 0x40e6e1a8'
  new: 'function: 0x40e6e148'
  totable: 'function: 0x40e6e240'
  compare: 'function: 0x40e6e1f8'
  compare_with_key: 'function: 0x40e6e170'
...
```

We need them for https://github.com/tarantool/aeon/issues/20 and https://github.com/tarantool/aeon/issues/25. It should be fairly easy to add them because they're already available in C so we just need to export them to Lua.
