### ISSUE TITLE
config: verify that replicaset contains an instance.

### ISSUE THREAD

**Issue by Lord-KA** [tarantool/tarantool#9895]
There is a quite common mistake, when people misplace a section in config to a different level, creating confusion.
For example, here there is an empty replicaset `sharding` instead of sharding option for all replicasets: 
```yaml
groups:
  g-001:
    replicasets:
      sharding:
        roles:
        - storage
      r-001:
        instances:
          i-001: []
```
All of the ways to misplace the "global" configuration:
```yaml
# global                                                                        
groups:          
  # unintentional "sharding" group                                                                                                                                    
  g-001:                                                                        
    # global for a group                                                        
    replicasets:
      # unintentional "sharding" replicaset                                                                
      r-001:                                                                    
        # global for a replicaset                                               
        instances:
          # unintentional "sharding" instance                                                              
          i-001: {                                                              
            # "global" for an instance                                          
          }                                                                     
```

We should check the following:
* every group contains a replicaset (so there is no empty "sharding" group)
* every replicaset contains an instance (so there is no empty "sharding" replicaset)

Note that we can't check instance this way, because it doesn't have the succeeding level.
