### ISSUE TITLE
Add Lua trace when throwing error raised in C to Lua

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#9914]
If a built-in Tarantool Lua function implemented in C (e.g. `space:insert`) raises an exception, the exception trace points to the C code, not to the Lua code that called the function, for example:

```Lua
-- test.lua
local yaml = require('yaml')

box.cfg{log_level = 'warn'}

local s = box.schema.create_space('test')
s:create_index('pk')
s:insert({1, 1})

local ok, err = pcall(s.insert, s, {1, 2})
assert(not ok)
print(yaml.encode(err:unpack()))

os.exit(0)
```

Output:

```yaml
---
code: 3
base_type: ClientError
message: Duplicate key exists in unique index "pk" in space "test" with old tuple
  - [1, 1] and new tuple - [1, 2]
new_tuple: [1, 2]
trace:
- file: ./src/box/memtx_tree.cc
  line: 1160
old_tuple: [1, 1]
type: ClientError
space: test
index: pk
...
```

This isn't really helpful. Apparently, in this example the user would like to see the trace pointing to `test.lua:10`.

The suggestion is to add the trace of the calling Lua function when re-throwing an error raised in C code to Lua:

```yaml
trace:
- file: ./src/box/memtx_tree.cc
  line: 1160
- file: test.lua
  line: 10
```

To achieve that, we probably need to patch [`luaT_error`](https://github.com/tarantool/tarantool/blob/de80e0264f7deb58ea86ef85b37b92653a803430/src/lua/error.c#L97) and a few Lua FFI wrappers.

Similar issues:
- #677
- #4904
